- distribution/LICENSE-BIN
- distribution/pom.xml
- distribution/release-fescar.xml
- server/pom.xml
- server/src/main/resources/application.conf
> add server distribution

- core/src/main/java/com/alibaba/fescar/core/rpc/netty/AbstractRpcRemotingServer.java
- core/src/main/java/com/alibaba/fescar/core/rpc/netty/NettyServerConfig.java
fix listenPort allow user defined
> fix listenPort allow user defined

- core/src/main/java/com/alibaba/fescar/core/service/AddressWatcher.java
- core/src/main/java/com/alibaba/fescar/core/service/ConfigurationKeys.java
- core/src/main/java/com/alibaba/fescar/core/service/ServiceManager.java
- core/src/main/java/com/alibaba/fescar/core/service/ServiceManagerStaticConfigImpl.java
- core/src/main/log4j.properties
- core/src/main/logback.xml
- dubbo/src/main/java/com/alibaba/fescar/dubbo/TransactionPropagationFilter.java
- server/src/main/java/com/alibaba/fescar/server/coordinator/DefaultCoordinator.java
- tm/src/main/java/com/alibaba/fescar/tm/DefaultTransactionManager.java
- tm/src/main/java/com/alibaba/fescar/tm/TMClient.java
- tm/src/main/java/com/alibaba/fescar/tm/api/DefaultFailureHandlerImpl.java
- tm/src/main/java/com/alibaba/fescar/tm/api/DefaultGlobalTransaction.java
- tm/src/main/java/com/alibaba/fescar/tm/api/FailureHandler.java
- tm/src/main/java/com/alibaba/fescar/tm/api/GlobalTransaction.java
- tm/src/main/java/com/alibaba/fescar/tm/api/GlobalTransactionRole.java
- tm/src/main/java/com/alibaba/fescar/tm/api/TransactionalExecutor.java
- tm/src/main/java/com/alibaba/fescar/tm/api/TransactionalTemplate.java
- tm/src/test/java/com/alibaba/fescar/tm/api/APITest.java
> add copyright and javadoc

- .gitignore
- CHANGELOG.md
add ignore, release 0.1.0 changelog
> add ignore, release 0.1.0 changelog

- README.md
I have spotted a few grammatical errors (and typos) in `README.md`, this PR fixes these issues.
> Fix grammar issues in README.md

- common/src/main/java/com/alibaba/fescar/common/Constants.java
Signed-off-by: zsongshu <zsongshu@qq.com>
> delete unused import

- examples/src/main/java/com/alibaba/fescar/tm/dubbo/impl/AccountServiceImpl.java
- examples/src/main/java/com/alibaba/fescar/tm/dubbo/impl/BusinessServiceImpl.java
- examples/src/main/java/com/alibaba/fescar/tm/dubbo/impl/OrderServiceImpl.java
- examples/src/main/java/com/alibaba/fescar/tm/dubbo/impl/StorageServiceImpl.java
- examples/src/main/resources/application.conf
1. Add the vm args when running the dubbo service in the examples. Fix the bug: java.net.SocketException: Can't assign requested address.
2. Add the application.conf，fix the wrong (can not connect the fescar) when running the BusinessServiceImpl.
> perfect demo

- test/pom.xml
fix spring potential security vulnerabilities, upgrade 4.3.18+
> fix spring potential security vulnerabilities

- .gitignore
Please answer these questions before submitting pull request
- Why submit this pull request?
___
- .gitignore ignores the distribution module does not need to track file
> .gitignore ignores the distribution module does not need to track file

- server/src/main/java/com/alibaba/fescar/server/store/TransactionWriteStore.java
add getSessionInstanceByOperation switch default
> add getSessionInstanceByOperation switch default

- .github/ISSUE_TEMPLATE/BUG_REPORT.md
- core/src/main/java/com/alibaba/fescar/core/rpc/netty/NettyBaseConfig.java
Please make sure you have read and understood the contributing guidelines
fixes #117
> fixes #117

- rm-datasource/src/main/java/com/alibaba/fescar/rm/datasource/sql/SQLVisitorFactory.java
Please make sure you have read and understood the contributing guidelines
fix #114 , rm main()
> fixes #114

- common/src/main/java/com/alibaba/fescar/common/loader/EnhancedServiceLoader.java
- server/src/main/java/com/alibaba/fescar/server/session/BranchSession.java
Remove redundant semicolons and modify non-standard names
> Remove redundant semicolons and modify non-standard names

- core/src/main/java/com/alibaba/fescar/core/rpc/netty/NettyBaseConfig.java
> fix issue #122

- server/src/main/java/com/alibaba/fescar/server/store/FileTransactionStoreManager.java
> fix file.RenameTo->Files.move

- core/src/main/java/com/alibaba/fescar/core/rpc/netty/NettyBaseConfig.java
> fixes #121

- .gitignore
- .travis.yml
- README.md
- pom.xml
add travis and codecov config
https://github.com/alibaba/fescar/issues/73
Ci  success 
No
> #73 add travis config

- server/src/main/java/com/alibaba/fescar/server/session/BranchSession.java
delete BranchSession main
fix #135
> fix #135 delete BranchSession main

- server/src/main/java/com/alibaba/fescar/server/coordinator/DefaultCoordinator.java
fix  param position err
fixes #137
> fix #137 param position err

- core/src/main/java/com/alibaba/fescar/core/rpc/netty/AbstractRpcRemotingServer.java
delete defaultEventExecutorGroup
fixes #142
> fix #142 delete defaultEventExecutorGroup

- rm-datasource/src/main/java/com/alibaba/fescar/rm/datasource/ConnectionContext.java
- rm-datasource/src/main/java/com/alibaba/fescar/rm/datasource/ConnectionProxy.java
- rm-datasource/src/main/java/com/alibaba/fescar/rm/datasource/exec/AbstractDMLBaseExecutor.java
- server/src/main/java/com/alibaba/fescar/server/lock/DefaultLockManagerImpl.java
When local branch change nothing, the RC will rise an NullpointerException,
when find parameter lockKeys is null, then will not try to check conflict keys
no
lack in fully design test packages, i don't know where to place it 
i check commit/rollback with changes and commit/rollback with no changes in local branch;
> fix: When local branch change nothing, the RC will rise an NullpointerException

- README.md
remove mistake twitter icon
No
> remove mistake twitter icon

- rm-datasource/src/main/java/com/alibaba/fescar/rm/datasource/undo/UndoLogManager.java
Unify `undo_log` table name variable
> fix: Unify `undo_log` table name variable

- spring/src/main/java/com/alibaba/fescar/spring/annotation/GlobalTransactionScanner.java
1.Fix the problem of duplicate assign new instance of field 'interceptor'
2.Remove the unnecessary type parameter
3.Let static field 'PROXYED_SET' just contains the names of object of class that has methods annotated by @GlobalTransactional
> Fix 3 problems of GlobalTransactionScanner class

- core/src/main/java/com/alibaba/fescar/core/exception/TransactionExceptionCode.java
- core/src/main/java/com/alibaba/fescar/core/model/GlobalStatus.java
- core/src/main/java/com/alibaba/fescar/core/protocol/AbstractMessage.java
- server/src/main/java/com/alibaba/fescar/server/coordinator/CoreFactory.java
- server/src/main/java/com/alibaba/fescar/server/coordinator/DefaultCoordinator.java
- server/src/main/java/com/alibaba/fescar/server/coordinator/DefaultCore.java
1. Optimize the slf4j logger output as followed:
```java
logger.info("Hello {}", str);
```
2. Remove some unnecessary `else` block code.
3. Remove some unnecessary static code.
> Optimize the slf4j logger output.

- spring/src/main/java/com/alibaba/fescar/spring/annotation/GlobalTransactionScanner.java
- spring/src/main/java/com/alibaba/fescar/spring/annotation/GlobalTransactionalInterceptor.java
1.Add static final default FailureHandler to scanner and interceptor
2.Move static final field to the head of other fields
#208
> Add static final default FailureHandler; make code normalized

- pom.xml
- server/pom.xml
- server/src/test/java/com/alibaba/fescar/server/session/BranchSessionTest.java
- server/src/test/java/com/alibaba/fescar/server/session/DefaultSessionManagerTest.java
- server/src/test/java/com/alibaba/fescar/server/session/FileBasedSessionManagerTest.java
- server/src/test/java/com/alibaba/fescar/server/session/GlobalSessionTest.java
add  unit test for session package
> add  unit test for session package

- examples/pom.xml
- examples/src/main/resources/dubbo-account-service.xml
- examples/src/main/resources/dubbo-order-service.xml
- examples/src/main/resources/dubbo-storage-service.xml
- pom.xml
add zk support for dubbo example
fixes #250
> fixes #250 add zk support

- core/src/main/java/com/alibaba/fescar/core/exception/TransactionExceptionCode.java
- core/src/main/java/com/alibaba/fescar/core/model/BranchStatus.java
- core/src/main/java/com/alibaba/fescar/core/model/GlobalStatus.java
- core/src/main/java/com/alibaba/fescar/core/rpc/DefaultServerMessageListenerImpl.java
1. remove unnecessary check
2. change some constants to capital letter
> remove unnecessary check and change some constants to capital letter

- spring/pom.xml
Remove duplicate spring dependencies
> spring 依赖重复

- server/src/main/java/com/alibaba/fescar/server/coordinator/DefaultCore.java
deal exception scenes of retry rollback failure 
fix #266
> #266 deal exception scenes of retry rollback failure

- server/src/test/java/com/alibaba/fescar/server/lock/LockManagerTest.java
- server/src/test/java/com/alibaba/fescar/server/store/FileTransactionStoreManagerTest.java
add lock manager test
fixes##192
> add lock manager test

- server/src/test/java/com/alibaba/fescar/server/coordinator/DefaultCoreTest.java
- server/src/test/java/com/alibaba/fescar/server/lock/DefaultLockManagerImplTest.java
add unit test for server package LockManager and DefaultCore
> add unit test for server package LockManager and DefaultCore

- rm-datasource/src/test/java/com/alibaba/fescar/rm/datasource/sql/druid/AbstractMySQLRecognizerTest.java
- rm-datasource/src/test/java/com/alibaba/fescar/rm/datasource/sql/druid/MySQLDeleteRecognizerTest.java
- rm-datasource/src/test/java/com/alibaba/fescar/rm/datasource/sql/druid/MySQLInsertRecognizerTest.java
- rm-datasource/src/test/java/com/alibaba/fescar/rm/datasource/sql/druid/MySQLSelectForUpdateRecognizerTest.java
- rm-datasource/src/test/java/com/alibaba/fescar/rm/datasource/sql/druid/MySQLUpdateRecognizerTest.java
add mysql recognizer unit test
fixes##192
> mysql_recognizer unit_test

- rm-datasource/src/main/java/com/alibaba/fescar/rm/datasource/DataSourceManager.java
fixed branchRegister use branchType
> fixed branchRegister use branchType

- config/src/main/java/com/alibaba/fescar/config/FileConfiguration.java
back task read config when timeout should break
fix #257 when timeout should break
> fix #257 when timeout should break

- core/src/main/java/com/alibaba/fescar/core/protocol/AbstractMessage.java
- core/src/main/java/com/alibaba/fescar/core/protocol/transaction/AbstractBranchEndRequest.java
- core/src/main/java/com/alibaba/fescar/core/protocol/transaction/AbstractBranchEndResponse.java
- core/src/main/java/com/alibaba/fescar/core/protocol/transaction/BranchRegisterRequest.java
- core/src/test/java/com/alibaba/fescar/core/message/BranchCommitRequestTest.java
- core/src/test/java/com/alibaba/fescar/core/message/BranchCommitResponseTest.java
- core/src/test/java/com/alibaba/fescar/core/message/BranchRegisterRequestTest.java
- examples/src/main/resources/dubbo-account-service.xml
- examples/src/main/resources/dubbo-order-service.xml
- examples/src/main/resources/dubbo-storage-service.xml
- examples/src/main/resources/jdbc.properties
- rm-datasource/src/main/java/com/alibaba/fescar/rm/datasource/exec/InsertExecutor.java
- rm-datasource/src/main/java/com/alibaba/fescar/rm/datasource/exec/PlainExecutor.java
- rm-datasource/src/main/java/com/alibaba/fescar/rm/datasource/exec/UpdateExecutor.java
- rm-datasource/src/main/java/com/alibaba/fescar/rm/datasource/sql/druid/MySQLInsertRecognizer.java
- rm-datasource/src/main/java/com/alibaba/fescar/rm/datasource/sql/struct/TableMetaCache.java
- rm-datasource/src/test/java/com/alibaba/fescar/rm/datasource/SQLVisitorFactoryTest.java
- server/src/main/java/com/alibaba/fescar/server/coordinator/DefaultCoordinator.java
- server/src/main/java/com/alibaba/fescar/server/coordinator/DefaultCore.java
- server/src/test/java/com/alibaba/fescar/server/session/BranchSessionTest.java
- server/src/test/java/com/alibaba/fescar/server/session/DefaultSessionManagerTest.java
- server/src/test/java/com/alibaba/fescar/server/session/FileBasedSessionManagerTest.java
- server/src/test/java/com/alibaba/fescar/server/session/GlobalSessionTest.java
- test/src/main/java/com/alibaba/fescar/test/DataSourceBasicTest.java
> release 0.1.2

- examples/src/main/java/com/alibaba/fescar/tm/dubbo/impl/AccountServiceImpl.java
> Correct the class of Logger in AccountServiceImpl

- distribution/pom.xml
- examples/pom.xml
- pom.xml
- test/pom.xml
> add maven package

- README.md
> add ecosystem address

- rm-datasource/src/test/java/com/alibaba/fescar/rm/datasource/sql/struct/TableMetaTest.java
table_meta unit_test
fixes #192
> table_meta unit_test

- README.md
> add contributor icon

- server/pom.xml
wins fescar-server.bat $EXTRA_JVM_ARGUMENTS error
fixes #373 #302 wins fescar-server.bat $EXTRA_JVM_ARGUMENTS error
> fix #373 #302 wins fescar-server.bat $EXTRA_JVM_ARGUMENTS error

- common/pom.xml
- config/pom.xml
- core/pom.xml
- distribution/pom.xml
- dubbo/pom.xml
- pom.xml
- rm-datasource/pom.xml
- server/pom.xml
- spring/pom.xml
- test/pom.xml
- tm/pom.xml
Release 0.1.4
#375 Release 0.1.4
> Release 0.1.4

- common/pom.xml
- config/pom.xml
- core/pom.xml
- core/src/main/java/com/alibaba/fescar/core/protocol/Version.java
- distribution/pom.xml
- dubbo/pom.xml
- pom.xml
- rm-datasource/pom.xml
- server/pom.xml
- spring/pom.xml
- test/pom.xml
- tm/pom.xml
change version to 0.2.0-SNAPSHOT
fix #381 change version to 0.2.0-SNAPSHOT
> fix #381 change version to 0.2.0-SNAPSHOT

- discovery/src/main/java/com/alibaba/fescar/discovery/loadbalance/RandomLoadBalance.java
- discovery/src/main/java/com/alibaba/fescar/discovery/loadbalance/RoundRobinLoadBalance.java
- discovery/src/test/java/com/alibaba/fescar/discovery/loadbalance/LoadBalanceTest.java
add Random and RoundRobin LoadBalance 
fix #407 
provide the test  com.alibaba.fescar.discovery.loadbalance.LoadBalanceTest
> add Random and RoundRobin LoadBalance

- config/src/main/java/com/alibaba/fescar/config/ConfigType.java
- config/src/main/java/com/alibaba/fescar/config/ConfigurationFactory.java
- config/src/main/java/com/alibaba/fescar/config/EurekaConfiguration.java
- discovery/pom.xml
- discovery/src/main/java/com/alibaba/fescar/discovery/registry/CustomEurekaInstanceConfig.java
- discovery/src/main/java/com/alibaba/fescar/discovery/registry/EurekaRegistryServiceImpl.java
- discovery/src/main/java/com/alibaba/fescar/discovery/registry/RegistryFactory.java
- server/src/main/resources/registry.conf
实现eureka 注册中心（不包含配置中心）
eureka注册中心实现，不包含配置中心，配置中心暂时无法实现。遗留问题为注册后不能直接查看到实例信息，需要等下一次心跳更新实例信息
> 实现eureka注册中心

- metrics/README.md
- metrics/metrics-api/pom.xml
- metrics/pom.xml
- pom.xml
Add Metrics Doc
https://github.com/alibaba/fescar/issues/384
There is no code submitted yet
> Feature Metrics Readme

- common/src/main/java/com/alibaba/fescar/common/exception/EurekaRegistryException.java
- discovery/src/main/java/com/alibaba/fescar/discovery/registry/EurekaRegistryServiceImpl.java
- server/src/main/resources/registry.conf
set refresh application time is 5s,and add instance weight config，optimization the code
> set refresh application time is 5s,and add instance weight config，optimization the code

- metrics/README.md
- metrics/metrics-api/src/main/java/com/alibaba/fescar/metrics/Clock.java
- metrics/metrics-api/src/main/java/com/alibaba/fescar/metrics/Constants.java
- metrics/metrics-api/src/main/java/com/alibaba/fescar/metrics/Counter.java
- metrics/metrics-api/src/main/java/com/alibaba/fescar/metrics/Gauge.java
- metrics/metrics-api/src/main/java/com/alibaba/fescar/metrics/Id.java
- metrics/metrics-api/src/main/java/com/alibaba/fescar/metrics/Measurement.java
- metrics/metrics-api/src/main/java/com/alibaba/fescar/metrics/Meter.java
- metrics/metrics-api/src/main/java/com/alibaba/fescar/metrics/Publisher.java
- metrics/metrics-api/src/main/java/com/alibaba/fescar/metrics/Registry.java
- metrics/metrics-api/src/main/java/com/alibaba/fescar/metrics/Summary.java
- metrics/metrics-api/src/main/java/com/alibaba/fescar/metrics/SystemClock.java
- metrics/metrics-api/src/main/java/com/alibaba/fescar/metrics/Timer.java
- metrics/metrics-prometheus/pom.xml
- pom.xml
add basic metrics api implement
https://github.com/alibaba/fescar/issues/384
only interfaces
will verify it in prometheus implement
> metrics api module implement

- metrics/metrics-api/src/main/java/com/alibaba/fescar/metrics/Clock.java
- metrics/metrics-api/src/main/java/com/alibaba/fescar/metrics/Counter.java
- metrics/metrics-api/src/main/java/com/alibaba/fescar/metrics/Id.java
- metrics/metrics-api/src/main/java/com/alibaba/fescar/metrics/Measurement.java
- metrics/metrics-api/src/main/java/com/alibaba/fescar/metrics/Registry.java
- metrics/metrics-api/src/main/java/com/alibaba/fescar/metrics/Summary.java
- metrics/metrics-api/src/main/java/com/alibaba/fescar/metrics/SystemClock.java
- metrics/metrics-prometheus/pom.xml
- metrics/metrics-prometheus/src/main/java/com/alibaba/fescar/metrics/DefaultCounter.java
- metrics/metrics-prometheus/src/main/java/com/alibaba/fescar/metrics/DefaultGauge.java
- metrics/metrics-prometheus/src/main/java/com/alibaba/fescar/metrics/DefaultRegistry.java
- metrics/metrics-prometheus/src/main/java/com/alibaba/fescar/metrics/DefaultSummary.java
- metrics/metrics-prometheus/src/main/java/com/alibaba/fescar/metrics/DefaultTimer.java
- metrics/metrics-prometheus/src/main/java/com/alibaba/fescar/metrics/SummaryValue.java
- metrics/metrics-prometheus/src/main/java/com/alibaba/fescar/metrics/TimerValue.java
- metrics/metrics-prometheus/src/test/java/com/alibaba/fescar/metrics/FixedClock.java
- metrics/metrics-prometheus/src/test/java/com/alibaba/fescar/metrics/TestDefaultCounter.java
- metrics/metrics-prometheus/src/test/java/com/alibaba/fescar/metrics/TestDefaultGauge.java
- metrics/metrics-prometheus/src/test/java/com/alibaba/fescar/metrics/TestDefaultRegistry.java
- metrics/metrics-prometheus/src/test/java/com/alibaba/fescar/metrics/TestDefaultSummary.java
- metrics/metrics-prometheus/src/test/java/com/alibaba/fescar/metrics/TestDefaultTimer.java
- metrics/pom.xml
Signed-off-by: zhengyangyong <yangyong.zheng@qq.com>
add default meter implements
https://github.com/alibaba/fescar/issues/384
> add default meter implements

- common/src/main/java/com/alibaba/fescar/common/util/NetUtil.java
- config/pom.xml
- config/src/main/java/com/alibaba/fescar/config/ApolloConfiguration.java
- config/src/main/java/com/alibaba/fescar/config/ConfigType.java
- config/src/main/java/com/alibaba/fescar/config/ConfigurationFactory.java
- config/src/main/resources/registry.conf
- discovery/pom.xml
- discovery/src/main/java/com/alibaba/fescar/discovery/registry/RedisListener.java
- discovery/src/main/java/com/alibaba/fescar/discovery/registry/RedisRegistryServiceImpl.java
- discovery/src/main/java/com/alibaba/fescar/discovery/registry/RegistryFactory.java
- discovery/src/test/java/com/alibaba/fescar/discovery/loadbalance/LoadBalanceFactoryTest.java
- discovery/src/test/java/resources/apollo.properties
- pom.xml
add apollo configuration center and redis registry support，Currently using apollo as the configuration center by default when using the redis registry
> add apollo configuration center and redis registry support

- discovery/src/main/java/com/alibaba/fescar/discovery/registry/RedisRegistryServiceImpl.java
[codeReview] redis registry code format parseInt
fix #479 [codeReview] redis registry code format parseInt
> fix #479 [codeReview] redis registry code format parseInt

- discovery/src/main/java/com/alibaba/fescar/discovery/registry/RedisRegistryServiceImpl.java
close when Jedis not work any more 
fix #481
> fix #481 close when Jedis not work any more

- common/pom.xml
- common/src/test/java/com/alibaba/fescar/common/StringUtilsTest.java
- common/src/test/java/com/alibaba/fescar/common/XIDTest.java
- common/src/test/java/com/alibaba/fescar/common/thread/RejectedPolicysTest.java
- config/pom.xml
- config/src/test/java/com/alibaba/fescar/config/FileConfigurationTest.java
- config/src/test/java/com/alibaba/fescar/config/NacosConfigurationTest.java
- pom.xml
change test to AssertJ 
fix #195
> fix #195 modified ut with AssertJ

- core/src/test/java/com/alibaba/fescar/core/protocol/MessageFutureTest.java
add test case for  MessageFuture
> [Test-1] add test for MessageFuture

- core/src/test/java/com/alibaba/fescar/core/protocol/RpcMessageTest.java
add test case for RpcMessage
fix #195
> [Test-1] add test for RpcMessage

- core/src/test/java/com/alibaba/fescar/core/context/ContextCoreTest.java
add test case  for ContextCore
fix #195
> [Test-1] add test for ContextCore

- core/src/test/java/com/alibaba/fescar/core/context/RootContextTest.java
add test case for RootContext
fix #195
> [Test-1] add test for RootContext

- common/src/test/java/com/alibaba/fescar/common/util/BlobUtilsTest.java
add test for BlobUtils
fix #195 
already add
run ut
> [Test-1] add test for BlobUtils

- common/src/test/java/com/alibaba/fescar/common/loader/ChineseHello.java
- common/src/test/java/com/alibaba/fescar/common/loader/EnglishHello.java
- common/src/test/java/com/alibaba/fescar/common/loader/EnhancedServiceLoaderTest.java
- common/src/test/java/com/alibaba/fescar/common/loader/FrenchHello.java
- common/src/test/java/com/alibaba/fescar/common/loader/Hello.java
- common/src/test/resources/META-INF/fescar/com.alibaba.fescar.common.loader.Hello
- common/src/test/resources/META-INF/fescar/frenchhello/com.alibaba.fescar.common.loader.Hello
- common/src/test/resources/META-INF/services/com.alibaba.fescar.common.loader.Hello
add test for EnhancedServiceLoader
Ⅱ. Does this pull request fix one issue?
fix #195
Ⅲ. Why don't you add test cases (unit test/integration test)?
already add
Ⅳ. Describe how to verify it
run ut
Ⅴ. Special notes for reviews
> [Test-1] add test for EnhancedServiceLoader

- common/src/test/java/com/alibaba/fescar/common/XIDTest.java
- common/src/test/java/com/alibaba/fescar/common/util/NetUtilTest.java
- common/src/test/java/com/alibaba/fescar/common/util/StringUtilsTest.java
add test for NetUtil
fix #195 
already add
run ut first
> [Test-1] add test for NetUtil

- config/src/test/java/com/alibaba/fescar/config/ConfigTypeTest.java
Add unit test to ConfigType
fix #195
> [Test-1] Add test cases for ConfigType

- common/src/test/java/com/alibaba/fescar/common/thread/NamedThreadFactoryTest.java
add test for NamedThreadFactory
fix #195 
already add
run ut first
> [Test-1] add test for NamedThreadFactory

- common/src/main/java/com/alibaba/fescar/common/exception/EurekaRegistryException.java
- config/src/main/java/com/alibaba/fescar/config/ConfigType.java
- discovery/pom.xml
- discovery/src/main/java/com/alibaba/fescar/discovery/registry/CustomEurekaInstanceConfig.java
- discovery/src/main/java/com/alibaba/fescar/discovery/registry/EurekaRegistryServiceImpl.java
- discovery/src/main/java/com/alibaba/fescar/discovery/registry/RegistryFactory.java
- discovery/src/main/java/com/alibaba/fescar/discovery/registry/RegistryType.java
- pom.xml
- server/src/main/resources/registry.conf
> Feature registry eurka

- core/src/main/java/com/alibaba/fescar/core/protocol/HeartbeatMessage.java
changed variables define
no
I think constant use final is better
> normative variables,i think it is final may be better

- rm-datasource/src/main/java/com/alibaba/fescar/rm/datasource/exec/DeleteExecutor.java
- rm-datasource/src/main/java/com/alibaba/fescar/rm/datasource/exec/UpdateExecutor.java
fixes #312.supports UPDATE & DELETE clause without where condition.
fixes #312
> fixes #312.supports UPDATE & DELETE clause without where condition.

- common/src/main/java/com/alibaba/fescar/common/thread/RejectedPolicies.java
- common/src/main/java/com/alibaba/fescar/common/util/NetUtil.java
- common/src/main/java/com/alibaba/fescar/common/util/StringUtils.java
- common/src/test/java/com/alibaba/fescar/common/thread/RejectedPoliciesTest.java
- common/src/test/java/com/alibaba/fescar/common/util/StringUtilsTest.java
- core/src/main/java/com/alibaba/fescar/core/rpc/ChannelManager.java
- core/src/main/java/com/alibaba/fescar/core/rpc/netty/TmRpcClient.java
- core/src/main/java/com/alibaba/fescar/core/service/ServiceManagerStaticConfigImpl.java
- discovery/src/main/java/com/alibaba/fescar/discovery/registry/FileRegistryServiceImpl.java
- discovery/src/main/java/com/alibaba/fescar/discovery/registry/RedisRegistryServiceImpl.java
- rm-datasource/src/main/java/com/alibaba/fescar/rm/datasource/exec/SelectForUpdateExecutor.java
- rm-datasource/src/main/java/com/alibaba/fescar/rm/datasource/sql/struct/TableMetaCache.java
- server/src/main/java/com/alibaba/fescar/server/lock/DefaultLockManagerImpl.java
- spring/src/main/java/com/alibaba/fescar/spring/annotation/GlobalTransactionScanner.java
- spring/src/main/java/com/alibaba/fescar/spring/annotation/GlobalTransactionalInterceptor.java
- spring/src/test/java/com/alibaba/fescar/spring/annotation/BusinessImpl.java
- spring/src/test/java/com/alibaba/fescar/spring/annotation/BusinessProxy.java
This PR contains some small refine and fixes:
(1) renaming `isEmpty` to `isNullOrEmpty`
(2) renaming `RejectedPolicys ` to `RejectedPolicies `
(3) refining some static final variables
> Minor refine and fix

- pom.xml
- rm-datasource/src/main/java/com/alibaba/fescar/rm/datasource/ConnectionContext.java
- rm-datasource/src/main/java/com/alibaba/fescar/rm/datasource/exec/BaseTransactionalExecutor.java
- rm-datasource/src/test/java/com/alibaba/fescar/rm/datasource/exec/BaseTransactionalExecutorTest.java
change the append And replace Stringbuffer to StringBuild when thread safe
> fix #566 change the append

- config/src/test/java/com/alibaba/fescar/config/ConfigurationFactoryTest.java
2.[Test-1] Add test cases for ConfigurationFactory
Add test cases for ConfigurationFactory
fixes #188
> [Test-1] Add test cases for ConfigurationFactory

- config/src/test/java/com/alibaba/fescar/config/ConfigTypeTest.java
- core/src/test/java/com/alibaba/fescar/core/model/BranchStatusTest.java
- core/src/test/java/com/alibaba/fescar/core/model/BranchTypeTest.java
- core/src/test/java/com/alibaba/fescar/core/model/GlobalStatusTest.java
Add unit test cases to BranchStatus, BranchType and GlobalStatus.
fix #195
> [Test-1] Add unit test cases to BranchStatus, BranchType and GlobalStatus.

- config/pom.xml
- config/src/main/java/com/alibaba/fescar/config/ConfigType.java
- config/src/main/java/com/alibaba/fescar/config/ConfigurationFactory.java
- config/src/main/java/com/alibaba/fescar/config/ZKConfiguration.java
- config/src/main/resources/registry.conf
- discovery/src/main/java/com/alibaba/fescar/discovery/registry/RegistryFactory.java
- discovery/src/main/java/com/alibaba/fescar/discovery/registry/RegistryType.java
- discovery/src/main/java/com/alibaba/fescar/discovery/registry/ZKRegisterServiceImpl.java
- server/src/main/resources/registry.conf
add zookeeper as register and config center
> make zookeeper as register and config center (#495)

- config/pom.xml
> Fix conflict of config/pom.xml

- rm-datasource/src/main/java/com/alibaba/fescar/rm/datasource/exec/DeleteExecutor.java
- rm-datasource/src/main/java/com/alibaba/fescar/rm/datasource/undo/mysql/keyword/MySQLKeywordChecker.java
i have tested for DeleteExecutor,InsertExecutor and UpdateExecutor,and this bug only occurs in DeleteExecutor.
fixes #625
> fixes #625 Optimization code of MySQL keyword checking

- discovery/src/main/java/com/alibaba/fescar/discovery/registry/EurekaRegistryServiceImpl.java
…ecoupling register and lookup
fix: for eureka register ;if not register,lookup will be error
> fix eureka subscribe role not inited on lookup method

- core/src/test/java/com/alibaba/fescar/core/protocol/transaction/GlobalBeginResponseTest.java
add test case for GlobalBeginResponse
fix #193
> [Test-1] Add test case for GlobalBeginResponse

- core/src/main/java/com/alibaba/fescar/core/rpc/ChannelManager.java
- bugfix : applicationIdMap may be null
> fix applicationIdMap may be null

- rm-datasource/src/main/java/com/alibaba/fescar/rm/datasource/StatementProxy.java
support for automatic table creation with JPA
#587
> fix #587 support for automatic table creation with JPA

- README.md
> Modify History of Readme

- server/src/main/java/com/alibaba/fescar/server/store/StoreConfig.java
> fix:fommatted StoreConfig code

- spring/src/main/java/com/alibaba/fescar/spring/util/SpringProxyUtils.java
- spring/src/main/java/com/alibaba/fescar/spring/util/TCCBeanParserUtils.java
- tcc/src/main/java/com/alibaba/fescar/rm/tcc/TCCResource.java
- tcc/src/main/java/com/alibaba/fescar/rm/tcc/api/BusinessActionContext.java
- tcc/src/main/java/com/alibaba/fescar/rm/tcc/api/BusinessActivityContext.java
- tcc/src/main/java/com/alibaba/fescar/rm/tcc/interceptor/ActionContextUtil.java
- tcc/src/main/java/com/alibaba/fescar/rm/tcc/interceptor/ActionInterceptorHandler.java
- tcc/src/main/java/com/alibaba/fescar/rm/tcc/remoting/RemotingDesc.java
- tcc/src/main/java/com/alibaba/fescar/rm/tcc/remoting/parser/DefaultRemotingParser.java
#732  Remove TCC chinese comments
> Remove TCC chinese comments

- spring/src/main/java/com/alibaba/fescar/spring/tcc/TccActionInterceptor.java
the  targetArguments  and the methodArgs are the same array object。so i delete the invalid code.
> delete invalid tcccode

- README.md
> update fescar version

- core/src/test/java/io/seata/core/protocol/MergeResultMessageTest.java
add test for MergeResultMessage
for coverage
> add test for MergeResultMessage

- core/src/main/java/io/seata/core/protocol/transaction/AbstractBranchEndRequest.java
fixes https://github.com/seata/seata/issues/832
review it
> fix bug for read data

- rm-datasource/src/main/java/io/seata/rm/datasource/AsyncWorker.java
> bugfix:use queue instead of list to avoid concurrent modify exception

- spring/src/main/java/io/seata/spring/util/SpringProxyUtils.java
> The GlobalTransactionScanner can't generate the proxy of dubbo:reference

- rm-datasource/src/main/java/io/seata/rm/datasource/exec/UpdateExecutor.java
UpdateExecutort afterImage his select for update do without
> bugfix:remove UpdateExecutort#afterImage for update

- common/src/main/java/io/seata/common/exception/FrameworkErrorCode.java
- common/src/main/java/io/seata/common/exception/FrameworkException.java
- common/src/main/java/io/seata/common/util/ReflectionUtil.java
- common/src/test/java/io/seata/common/exception/FrameworkExceptionTest.java
- core/src/main/java/io/seata/core/rpc/netty/AbstractRpcRemoting.java
- core/src/main/java/io/seata/core/rpc/netty/AbstractRpcRemotingClient.java
- core/src/main/java/io/seata/core/rpc/netty/RmMessageListener.java
- core/src/main/java/io/seata/core/rpc/netty/RmRpcClient.java
- core/src/main/java/io/seata/core/rpc/netty/TmRpcClient.java
- discovery/seata-discovery-redis/src/main/java/io/seata/discovery/registry/redis/RedisRegistryServiceImpl.java
- tcc/src/main/java/io/seata/rm/tcc/TCCResourceManager.java
- tcc/src/main/java/io/seata/rm/tcc/api/BusinessActionContext.java
- tcc/src/main/java/io/seata/rm/tcc/remoting/Protocols.java
1.prevent users from changing constant value 
2.add some NPE check
> avoid some possible risk

- codec/codec-protobuf/pom.xml
- codec/codec-protobuf/src/main/java/io/seata/codec/protobuf/ProtobufCodec.java
- codec/codec-protobuf/src/main/java/io/seata/codec/protobuf/ProtobufHelper.java
- codec/codec-protobuf/src/main/java/io/seata/codec/protobuf/ProtobufSerialzer.java
- codec/codec-protobuf/src/main/resources/META-INF/services/io.seata.core.codec.Codec
- codec/codec-seata/pom.xml
- codec/codec-seata/src/main/java/io/seata/codec/seata/SeataCodec.java
- codec/pom.xml
- core/src/main/java/io/seata/core/codec/Codec.java
- core/src/main/java/io/seata/core/codec/CodecFactory.java
- core/src/main/java/io/seata/core/protocol/AbstractIdentifyRequest.java
- core/src/main/java/io/seata/core/protocol/AbstractIdentifyResponse.java
- core/src/main/java/io/seata/core/protocol/AbstractResultMessage.java
- core/src/main/java/io/seata/core/protocol/MergeResultMessage.java
- core/src/main/java/io/seata/core/protocol/MergedWarpMessage.java
- core/src/main/java/io/seata/core/protocol/RegisterRMRequest.java
- core/src/main/java/io/seata/core/protocol/transaction/AbstractBranchEndRequest.java
- core/src/main/java/io/seata/core/protocol/transaction/AbstractBranchEndResponse.java
- core/src/main/java/io/seata/core/rpc/netty/MessageCodecHandler.java
> Fix conflict

- pom.xml
fixes https://github.com/seata/seata/issues/995
> fix maven-surefire-plugin compile error in mac

- spring/src/main/java/io/seata/spring/annotation/GlobalTransactionalInterceptor.java
Simplify the joining string method and replace anonymous inner type with lambda
no
> Polish code, replace with lambda and joining method

- rm-datasource/src/main/java/io/seata/rm/datasource/sql/struct/TableMeta.java
- rm-datasource/src/main/java/io/seata/rm/datasource/sql/struct/TableMetaCache.java
- rm-datasource/src/main/java/io/seata/rm/datasource/sql/struct/TableRecords.java
- Simplified some code.
- Avoid using anonymous list class.
No.
> Code clean up and avoid use anonymous class.

- rm-datasource/src/main/java/io/seata/rm/datasource/ConnectionContext.java
fixes https://github.com/seata/seata/issues/1044
> avoid duplicate lock key

- bom/pom.xml
upgrade fastjson and nacos-client
ci pass
> upgrade fastjson and nacos-client

- config/seata-config-core/src/main/resources/file.conf
- core/src/main/java/io/seata/core/constants/ConfigurationKeys.java
- rm-datasource/src/main/java/io/seata/rm/datasource/undo/AbstractUndoExecutor.java
- server/src/main/resources/file.conf
- server/src/main/resources/nacos-config.txt
- test/src/test/resources/file.conf
- Add switch of undo data validation.
Last PR of #1049 
Fix #1049
> Add switch of undo data validation.

- README.md
updates seata's version in README.md
> updates seata's version in README.md

- pom.xml
- server/src/test/java/io/seata/server/coordinator/DefaultCoreTest.java
bugfix:DefaultCoreTest.branchRegisterTest
fix #1199
> bugfix:DefaultCoreTest.branchRegisterTest

- rm-datasource/src/main/java/io/seata/rm/datasource/undo/parser/ProtostuffUndoLogParser.java
All overriding methods must be preceded by @Override annotations.
> All overriding methods must be preceded by @Override annotations.

- server/src/main/resources/db_store.sql
> perfect sql

- CONTRIBUTING.md
docs: add doc about contribution
> docs: add doc about contribution

- discovery/seata-discovery-redis/src/main/java/io/seata/discovery/registry/redis/RedisRegistryServiceImpl.java
bugfix: when instances empty,CLUSTER_ADDRESS_MAP add empty set
> bugfix: when instances empty,CLUSTER_ADDRESS_MAP add empty set

- all/pom.xml
- bom/pom.xml
- pom.xml
> change version to 0.7.0 to release

- README.md
- all/pom.xml
- bom/pom.xml
- core/src/main/java/io/seata/core/protocol/Version.java
- pom.xml
- spring/pom.xml
- spring/src/main/java/io/seata/spring/annotation/GlobalTransactionScanner.java
> release 0.7.1

- core/src/main/java/io/seata/core/protocol/RpcMessage.java
- core/src/main/java/io/seata/core/rpc/netty/v1/ProtocolV1Decoder.java
- test/src/test/java/io/seata/core/rpc/netty/v1/ClientChannelHandler.java
- test/src/test/java/io/seata/core/rpc/netty/v1/ProtocolV1Client.java
- test/src/test/java/io/seata/core/rpc/netty/v1/ProtocolV1CodecTest.java
- test/src/test/java/io/seata/core/rpc/netty/v1/ServerChannelHandler.java
- test/src/test/resources/logback.xml
- Add test case of new rpc protocol. 
- Change field type of RpcMessage#headMap to `HashMap`, because of `HashMap` can save the `null` value and RpcMessage only use in one single thread.
> test: Add test case for rpc protocol.

- rm-datasource/src/main/java/io/seata/rm/datasource/DataCompareUtils.java
add log
Easy to troubleshoot rollback failure reasons.
> add compareRows failed log

- config/seata-config-nacos/src/main/java/io/seata/config/nacos/NacosConfiguration.java
- config/seata-config-nacos/src/main/java/io/seata/config/nacos/NacosConfigurationProvider.java
- rm-datasource/src/test/java/io/seata/rm/datasource/sql/druid/AbstractMySQLRecognizerTest.java
fix ClassNotFound problem for Nacos config Implementation.
#1394 
Thanks to @zhuyoufeng
> bugfix:fix ClassNotFound problem for Nacos config Implementation.

- rm-datasource/src/main/java/io/seata/rm/datasource/sql/struct/TableMetaCache.java
Fix TableMetaCache refresh problem in multiple datasource.
#1480
> bugfix: TableMetaCache refresh problem in multiple datasource

- all/pom.xml
- bom/pom.xml
- core/src/main/java/io/seata/core/protocol/Version.java
- pom.xml
version: change version to 0.8.1-SNAPSHOT
> version: change version to 0.8.1-SNAPSHOT

- all/pom.xml
- bom/pom.xml
add seata-all dependencies
fix https://github.com/seata/seata-samples/issues/209
> add seata-all dependencies

- rm-datasource/src/main/java/io/seata/rm/datasource/ConnectionContext.java
- rm-datasource/src/main/java/io/seata/rm/datasource/exec/AbstractDMLBaseExecutor.java
bugfix: when getAfterImage error, trx autocommit
fixes #1519
> bugfix: when getAfterImage error, trx autocommit

- codec/seata-codec-protobuf/src/main/java/io/seata/codec/protobuf/ProtobufHelper.java
- common/src/test/java/io/seata/common/util/BlobUtilsTest.java
- core/src/main/java/io/seata/core/rpc/netty/NettyPoolKey.java
- discovery/seata-discovery-core/src/test/java/io/seata/discovery/loadbalance/LoadBalanceFactoryTest.java
- discovery/seata-discovery-redis/src/main/java/io/seata/discovery/registry/redis/RedisListener.java
- test/src/test/java/io/seata/core/rpc/netty/v1/HeadMapSerializerTest.java
- test/src/test/java/io/seata/core/rpc/netty/v1/ProtocolV1Client.java
- test/src/test/java/io/seata/core/rpc/netty/v1/ProtocolV1CodecTest.java
> optimize: fix typo

- codec/seata-codec-seata/src/test/resources/registry.conf
- config/seata-config-core/src/main/resources/registry.conf
- server/src/main/java/io/seata/server/session/AbstractSessionManager.java
- server/src/main/resources/registry.conf
- test/src/test/resources/registry.conf
> optimize: AbstractSessionManager debug log is wrong

- bom/pom.xml
Security issue: upgrade fastjson version to 1.2.60 (https://github.com/alibaba/fastjson/releases/tag/1.2.60) for security issue
yes
>  Security issue: upgrade fastjson version to 1.2.60 for security issue

- README.md
- all/pom.xml
- bom/pom.xml
- core/src/main/java/io/seata/core/protocol/Version.java
- pom.xml
> release 0.8.1

- server/src/main/java/io/seata/server/ParameterParser.java
> Modify punctuation marks

- common/src/main/java/io/seata/common/loader/EnhancedServiceLoader.java
- common/src/main/java/io/seata/common/util/CollectionUtils.java
- core/src/main/java/io/seata/core/rpc/ChannelManager.java
- rm-datasource/src/main/java/io/seata/rm/datasource/sql/struct/TableMetaCacheOracle.java
- rm-datasource/src/main/java/io/seata/rm/datasource/undo/AbstractUndoExecutor.java
- rm-datasource/src/test/java/io/seata/rm/datasource/undo/UndoLogManagerTest.java
- rm-datasource/src/test/java/io/seata/rm/datasource/undo/parser/JacksonUndoLogParserTest.java
- server/src/main/java/io/seata/server/lock/memory/MemoryLocker.java
> optimize: Based on Java 5 optimization

- tm/src/main/java/io/seata/tm/api/DefaultGlobalTransaction.java
> bugfix: clean xid when tm commit or rollback failed

- rm-datasource/src/main/java/io/seata/rm/datasource/undo/AbstractUndoLogManager.java
- rm-datasource/src/main/java/io/seata/rm/datasource/undo/mysql/MySQLUndoLogManager.java
- rm-datasource/src/main/java/io/seata/rm/datasource/undo/oracle/OracleUndoLogManager.java
abstract common undolog manager method in mysql and oracle
fixes #1645
> optimize: abstract common undolog manager method

- rm-datasource/src/main/java/io/seata/rm/datasource/undo/AbstractUndoLogManager.java
undo support oracle table meta cache
> fix: undo support oracle table meta cache

- common/src/test/java/io/seata/common/exception/StoreExceptionTest.java
- common/src/test/java/io/seata/common/thread/NamedThreadFactoryTest.java
- common/src/test/java/io/seata/common/thread/PositiveAtomicCounterTest.java
- common/src/test/java/io/seata/common/util/CollectionUtilsTest.java
Enhance the test coverage of `seata-common` module.
It's a partial fix of #187 .
It adds tests... 😄 
Run tests and coverage of `seata-common` module.
Some cases are very hard to cover, also we have code that will be never executed, may be the code should be refactored....
> test: enhance test coverage of seata common

- all/pom.xml
- bom/pom.xml
- core/src/main/java/io/seata/core/protocol/Version.java
- pom.xml
> version: change version to 1.0.0-SNAPSHOT

- discovery/seata-discovery-eureka/src/main/java/io/seata/discovery/registry/eureka/EurekaRegistryServiceImpl.java
- discovery/seata-discovery-nacos/src/main/java/io/seata/discovery/registry/nacos/NacosRegistryServiceImpl.java
- discovery/seata-discovery-redis/src/main/java/io/seata/discovery/registry/redis/RedisRegistryServiceImpl.java
- discovery/seata-discovery-sofa/src/main/java/io/seata/discovery/registry/sofa/SofaRegistryServiceImpl.java
- discovery/seata-discovery-zk/src/main/java/io/seata/discovery/registry/zk/ZookeeperRegisterServiceImpl.java
- spring/src/main/java/io/seata/spring/tcc/TccActionInterceptor.java
> optimize: simplify code

- spring/src/main/java/io/seata/spring/annotation/GlobalTransactionScanner.java
The current auto proxy of datasource does not work for multiple-datasource,this PR will fix it.
#1792 
i've done integration test.
> bugfix:fix auto proxy for multiple-datasource does not work

- codecov.yml
optimize: adjust codecov configuration
cat codecov.yml | curl --data-binary @- https://codecov.io/validate
> optimize: adjust codecov configuration

- codecov.yml
> optimize:update codecov.yml

- rm-datasource/src/main/java/io/seata/rm/datasource/undo/UndoExecutorFactory.java
More and more database types will be supported in the future, so I recommend putting them in a Set.
> optimize: encapsulation determines the supported database type

- .travis.yml
- server/pom.xml
Fixed issue of doesn't match environment when build docker image
> fixed issue of doesn't match environment when build docker image

- core/src/main/java/io/seata/core/store/db/LogStoreSqls.java
- distribution/pg/db_undo_log_pg.sql
- rm-datasource/src/main/java/io/seata/rm/datasource/sql/druid/postgresql/BasePostgresqlRecognizer.java
- rm-datasource/src/main/java/io/seata/rm/datasource/undo/postgresql/PostgresqlUndoLogManager.java
support PostgreSQL
#1279 #1170 #1641 #1972
> support postgresql

- .gitignore
- README.md
- all/pom.xml
- bom/pom.xml
- core/src/main/java/io/seata/core/protocol/Version.java
- pom.xml
change version to 1.1.0-SNAPSHOT and add logs
> change version to 1.1.0-SNAPSHOT and add logs

- server/src/main/java/io/seata/server/coordinator/DefaultCoordinator.java
Optimize some word spelling.
no
> optimize: some typos

- saga/seata-saga-engine-store/src/main/java/io/seata/saga/engine/store/db/DbAndReportTcStateLogStore.java
Bugfix: Saga report branch status incorrect when service retried succeed
#2144
> bugfix: Saga report branch status incorrect when service retried succeed

- core/src/main/java/io/seata/core/store/db/LogStoreDataBaseDAO.java
- core/src/main/java/io/seata/core/store/db/LogStoreSqls.java
change wrong word "qurey" to "query"
> optimize: fix query typo

- rm-datasource/src/main/java/io/seata/rm/datasource/sql/struct/cache/OracleTableMetaCache.java
- rm-datasource/src/test/java/io/seata/rm/datasource/sql/struct/cache/OracleTableMetaCacheTest.java
fix oracle get table meta fail
#2282
> bugfix: fix oracle get table meta fail

- README.md
doc: supplement using organization logs
> doc: supplement using organization logs

- core/src/main/java/io/seata/core/logger/StackTraceLogger.java
- rm-datasource/src/main/java/io/seata/rm/datasource/DataSourceManager.java
> optimize: StackTraceLogger param

- core/src/main/java/io/seata/core/context/RootContext.java
- integration/dubbo-alibaba/src/main/java/io/seata/integration/dubbo/alibaba/AlibabaDubboTransactionPropagationFilter.java
- integration/dubbo/src/main/java/io/seata/integration/dubbo/ApacheDubboTransactionPropagationFilter.java
- rm-datasource/src/main/java/io/seata/rm/datasource/exec/ExecuteTemplate.java
- saga/seata-saga-engine-store/src/main/java/io/seata/saga/engine/store/db/DbAndReportTcStateLogStore.java
- saga/seata-saga-tm/src/main/java/io/seata/saga/tm/DefaultSagaTransactionalTemplate.java
- spring/src/main/java/io/seata/spring/annotation/GlobalTransactional.java
- spring/src/main/java/io/seata/spring/annotation/GlobalTransactionalInterceptor.java
- spring/src/main/java/io/seata/spring/tcc/TccActionInterceptor.java
- test/src/test/java/io/seata/saga/engine/mock/MockGlobalTransaction.java
- tm/src/main/java/io/seata/tm/api/DefaultGlobalTransaction.java
- tm/src/main/java/io/seata/tm/api/GlobalTransaction.java
- tm/src/main/java/io/seata/tm/api/GlobalTransactionContext.java
- tm/src/main/java/io/seata/tm/api/TransactionalTemplate.java
- tm/src/main/java/io/seata/tm/api/transaction/TransactionInfo.java
- tm/src/test/java/io/seata/tm/api/APITest.java
- tm/src/test/java/io/seata/tm/api/TransactionTemplateTest.java
…saction mode switching (#2307)"
This reverts commit b1a19a3a90c0792d64bcdafa6a5aced1b9401a95.
#2307  bug：provider's xid missing.
> revert  pr #2307

- script/config-center/apollo/apollo-config.sh
- script/config-center/consul/consul-config.sh
- script/config-center/etcd3/etcd3-config.sh
- script/config-center/nacos/nacos-config.sh
- script/config-center/zk/zk-config.sh
> bugfix: fix configuration item containing spaces

- common/src/main/java/io/seata/common/util/StringUtils.java
- common/src/test/java/io/seata/common/util/StringUtilsTest.java
StringUtils.toString(o) the o class contains self's class, appears stack overflow error.
fixes #2423
> bugfix: StringUtils.toString(o)  stackoverflowerror.

- README.md
- all/pom.xml
- bom/pom.xml
- core/src/main/java/io/seata/core/protocol/Version.java
- pom.xml
vote: vote for release Seata 1.2.0
> release: release 1.2.0

- all/pom.xml
- bom/pom.xml
- core/src/main/java/io/seata/core/protocol/Version.java
- pom.xml
version: change version to 1.3.0-SNAPSHOT
> version: change version to 1.3.0-SNAPSHOT

- common/src/main/java/io/seata/common/loader/EnhancedServiceLoader.java
Remove the unused variable: `result`
> optimize: remove the unused variable

- common/src/main/java/io/seata/common/util/IdWorker.java
- server/src/main/java/io/seata/server/UUIDGenerator.java
- server/src/test/java/io/seata/server/UUIDGeneratorOverflowTest.java
modify IdWorker position to make it reasonable
> optimize: modify IdWorker position to make it reasonable

- all/pom.xml
The postgre driver would include in seata-all.jar when packaging
> optimize: change pg driver scope to provide

- saga/seata-saga-engine/src/main/java/io/seata/saga/engine/pcext/handlers/SubStateMachineHandler.java
- test/src/test/java/io/seata/saga/engine/db/StateMachineDBTests.java
bugfix: Wrong constant used in the saga SubStateMachineHandler
顺便Disabled掉一个test
> bugfix: fix wrong constant used in the saga SubStateMachineHandler

- README.md
- all/pom.xml
- bom/pom.xml
- core/src/main/java/io/seata/core/protocol/Version.java
- pom.xml
> release: release 1.3.0

- all/pom.xml
- bom/pom.xml
- core/src/main/java/io/seata/core/protocol/Version.java
- pom.xml
- server/src/main/resources/file.conf
version: change version to 1.4.0-SNAPSHOT
change the default value for DB max conn.
> version: change version to 1.4.0-SNAPSHOT

- core/src/main/java/io/seata/core/constants/DefaultValues.java
- core/src/main/java/io/seata/core/store/db/AbstractDataSourceProvider.java
- server/src/main/java/io/seata/server/storage/db/lock/DataBaseLockManager.java
- server/src/main/java/io/seata/server/storage/db/store/DataBaseTransactionStoreManager.java
> Revert "optimize: Added some configuration items to keep consistent with official documents"

- README.md
Update seate user’s website logo url.
> docs: Update seate user’s website logo url.

- rm-datasource/src/main/java/io/seata/rm/datasource/exec/BaseTransactionalExecutor.java
fix build image wrong when where condition contains "\n"
fixes #3164
> bugfix: remove next line to space

- README.md
- all/pom.xml
- bom/pom.xml
- core/src/main/java/io/seata/core/protocol/Version.java
- pom.xml
[vote]: vote for release 1.4.0
> [release]: release for 1.4.0

- all/pom.xml
- bom/pom.xml
- core/src/main/java/io/seata/core/protocol/Version.java
- pom.xml
version: change version to 1.5.0-SNAPSHOT
> version: change version to 1.5.0-SNAPSHOT

- integration/http/src/test/java/io/seata/integration/http/MockResponse.java
- rm-datasource/src/main/java/io/seata/rm/datasource/exec/BaseTransactionalExecutor.java
- saga/seata-saga-engine/src/main/java/io/seata/saga/engine/sequence/SpringJvmUUIDSeqGenerator.java
optimize: StringBuffer to StringBuilder
> optimize: replace StringBuffer to StringBuilder

- integration/http/src/main/java/io/seata/integration/http/TransactionPropagationIntercepter.java
- integration/http/src/main/java/io/seata/integration/http/TransactionPropagationInterceptor.java
- integration/http/src/test/java/io/seata/integration/http/MockWebServer.java
- seata-spring-boot-starter/src/main/java/io/seata/spring/boot/autoconfigure/HttpAutoConfiguration.java
> optimize: modify TransactionPropagationInterceptor name

- server/src/test/java/io/seata/server/coordinator/DefaultCoordinatorMetricsTest.java
> bugfix: the problem test case

- all/pom.xml
- compressor/seata-compressor-all/pom.xml
bugfix: fix deploy staging rule check failed
fix #3356
> bugfix: fix deploy staging rule check failed

- .github/workflows/build.yml
optimize: add github action secrets env for dockerHub
fix #3368
> optimize: add github action secrets env for dockerHub

- changes/1.5.0.md
- changes/en-us/1.5.0.md
- sqlparser/seata-sqlparser-core/src/main/java/io/seata/sqlparser/SQLType.java
> optimize: SQLType INSERT INGORE typo

- changes/en-us/1.5.0.md
> bugfix: reversion the deleted md

- core/src/main/java/io/seata/core/logger/StackTraceLogger.java
- rm-datasource/src/main/java/io/seata/rm/datasource/sql/struct/cache/AbstractTableMetaCache.java
- server/src/main/java/io/seata/server/coordinator/AbstractCore.java
- server/src/test/java/io/seata/server/coordinator/DefaultCoordinatorTest.java
- server/src/test/java/io/seata/server/coordinator/DefaultCoreTest.java
- server/src/test/java/io/seata/server/event/DefaultCoreForEventBusTest.java
bugfix: fix test case NPE and StackTraceLogger's log.
BUG修复：
1. 修复测试用例空指针异常。
2. 修正`StackTraceLogger`中错误的日志格式。
> bugfix: fix test case NPE and StackTraceLogger's log

- server/src/main/java/io/seata/server/storage/db/store/LogStoreDataBaseDAO.java
When using Oracle or PostgreSQL as the database,  can't query column info
fixes #3496
> bugfix: oracle and postgreSQL can't query column info(#3496)

- README.md
- changes/1.5.0.md
- changes/en-us/1.5.0.md
- distribution/release-seata.xml
fix server distribution missing files
fix #3539 #3534
> bugfix: fix server distribution missing files

- changes/1.5.0.md
- changes/en-us/1.5.0.md
- script/client/at/db/mysql.sql
- script/client/at/db/oracle.sql
- script/client/at/db/postgresql.sql
- script/server/db/mysql.sql
- script/server/db/oracle.sql
- script/server/db/postgresql.sql
> optimize: unified the length of xid in scripts

- rm-datasource/src/test/java/io/seata/rm/datasource/exec/MySQLInsertExecutorTest.java
fix UnfinishedStubbingException of unit test case.
> bugfix:fix UnfinishedStubbingException of UT

- core/src/main/java/io/seata/core/event/EventBus.java
> docs: fix typo

- changes/1.5.0.md
- changes/en-us/1.5.0.md
- script/client/spring/application.properties
- script/client/spring/application.yml
> optimize: supplement missing configuration and new version documents

- changes/1.5.0.md
- changes/en-us/1.5.0.md
- config/seata-config-apollo/src/main/java/io/seata/config/apollo/ApolloConfiguration.java
fix:NPE about apollo setProperty
fixes #3677 
fixes #3684
> bugfix:fix NPE and cluster key about apollo

- .github/workflows/build.yml
> optimize: optimize github actions

- changes/1.5.0.md
- changes/en-us/1.5.0.md
- server/src/main/resources/application.example.yml
bugfix: fix the Server can't find redis-host property
fix #3791
> bugfix: fix the Server can't find redis-host property

- dependencies/pom.xml
- server/pom.xml
- server/src/test/java/io/seata/server/lock/redis/RedisLockManagerTest.java
- server/src/test/java/io/seata/server/session/redis/RedisSessionManagerTest.java
rollback pr with sequence number 3699
> optimize:rollback pr with sequence number 3699

- changes/1.5.0.md
- changes/en-us/1.5.0.md
- common/src/main/java/io/seata/common/util/ReflectionUtil.java
optimize: optimize: cache reflection results of the fields and methods.
---
缓存Field和Method的反射结果。
> optimize: cache reflection results of the fields and methods

- changes/1.5.0.md
- changes/en-us/1.5.0.md
- sqlparser/seata-sqlparser-druid/src/main/java/io/seata/sqlparser/druid/mysql/MySQLUpdateRecognizer.java
- sqlparser/seata-sqlparser-druid/src/main/java/io/seata/sqlparser/druid/oracle/OracleUpdateRecognizer.java
- sqlparser/seata-sqlparser-druid/src/main/java/io/seata/sqlparser/druid/postgresql/PostgresqlUpdateRecognizer.java
optimize:replace @Deprecated getOwnernName to getOwnerName in druid
#3953
> optimize:replace @Deprecated getOwnernName to getOwnerName in druid

- changes/1.5.0.md
- changes/en-us/1.5.0.md
- seata-spring-autoconfigure/seata-spring-autoconfigure-server/src/main/java/io/seata/spring/boot/autoconfigure/properties/server/store/StoreDBProperties.java
- server/src/main/resources/application.example.yml
> bugfix: add distributed lock properties for spring boot

- changes/1.5.0.md
- changes/en-us/1.5.0.md
- rm-datasource/src/main/java/io/seata/rm/datasource/AsyncWorker.java
bugfix: fix delete undo log connection already closed
fix #4173
> bugfix: fix delete undo log connection already closed

- changes/1.5.0.md
- changes/en-us/1.5.0.md
- common/src/main/java/io/seata/common/util/LowerCaseLinkHashMap.java
- rm-datasource/src/main/java/io/seata/rm/datasource/sql/struct/TableMeta.java
> bugfix: fix could not rollback when insert field list is empty

- changes/1.5.0.md
- changes/en-us/1.5.0.md
- common/src/main/java/io/seata/common/DefaultValues.java
- core/src/main/java/io/seata/core/lock/AbstractLocker.java
- core/src/main/java/io/seata/core/lock/Locker.java
- core/src/main/java/io/seata/core/store/LockStore.java
- core/src/main/java/io/seata/core/store/db/sql/lock/AbstractLockStoreSql.java
- core/src/main/java/io/seata/core/store/db/sql/lock/LockStoreSql.java
- core/src/test/java/io/seata/core/store/db/sql/lock/LockStoreSqlFactoryTest.java
- server/src/main/java/io/seata/server/coordinator/DefaultCore.java
- server/src/main/java/io/seata/server/session/GlobalSession.java
- server/src/main/java/io/seata/server/storage/db/lock/DataBaseLockManager.java
- server/src/main/java/io/seata/server/storage/db/lock/DataBaseLocker.java
- server/src/main/java/io/seata/server/storage/db/lock/LockStoreDataBaseDAO.java
- server/src/main/java/io/seata/server/storage/redis/lock/RedisLockManager.java
- server/src/main/java/io/seata/server/storage/redis/lock/RedisLocker.java
- server/src/test/java/io/seata/server/coordinator/DefaultCoreTest.java
- server/src/test/java/io/seata/server/event/DefaultCoreForEventBusTest.java
…cumstances.
fixes #4182  #4232
> bugfix: data remanence problems in lock and branch under specific circumstances.

- changes/1.5.0.md
- changes/en-us/1.5.0.md
- config/seata-config-nacos/src/main/java/io/seata/config/nacos/NacosConfiguration.java
- discovery/seata-discovery-nacos/src/main/java/io/seata/discovery/registry/nacos/NacosRegistryServiceImpl.java
- script/client/conf/registry.conf
- script/client/spring/application.properties
- script/client/spring/application.yml
- seata-spring-autoconfigure/seata-spring-autoconfigure-core/src/main/java/io/seata/spring/boot/autoconfigure/properties/config/ConfigNacosProperties.java
- seata-spring-autoconfigure/seata-spring-autoconfigure-core/src/main/java/io/seata/spring/boot/autoconfigure/properties/registry/RegistryNacosProperties.java
- server/src/main/resources/application.example.yml
optimize: support authentication of MSE-Nacos with ak/sk
fix #4283
> optimize: support authentication of MSE-Nacos with ak/sk

- metrics/README.md
修复 metrices 模块 README.md 的配置遗漏问题
> docs: fix the README.md of metrices module

- common/src/main/java/io/seata/common/ConfigurationKeys.java
- config/seata-config-nacos/src/main/java/io/seata/config/nacos/NacosConfiguration.java
- discovery/seata-discovery-nacos/src/main/java/io/seata/discovery/registry/nacos/NacosRegistryServiceImpl.java
- server/src/main/java/io/seata/server/session/SessionHelper.java
> optimize: optimize nacos config and naming properties

- server/src/main/java/io/seata/server/coordinator/DefaultCoordinator.java
- server/src/test/java/io/seata/server/coordinator/DefaultCoordinatorTest.java
- server/src/test/java/io/seata/server/event/DefaultCoreForEventBusTest.java
- server/src/test/java/io/seata/server/session/db/DataBaseSessionManagerTest.java
- server/src/test/java/io/seata/server/store/db/LogStoreDataBaseDAOTest.java
> bugfix: fix test case

- build/pom.xml
> optimize: some fix  in release 1.5.0

- changes/1.5.0.md
- changes/en-us/1.5.0.md
> doc: update change.md (#4612)

- changes/en-us/develop.md
- changes/zh-cn/develop.md
- spring/src/main/java/io/seata/spring/annotation/GlobalTransactionalInterceptor.java
set GlobalTransactional.rollbackForClassName into AspectTransactional.rollbackForClassName.
> bugfix: set wrong value to rollbackForClassName

- README.md
- build/pom.xml
- changes/en-us/develop.md
- changes/zh-cn/develop.md
- core/src/main/java/io/seata/core/protocol/Version.java
- discovery/seata-discovery-nacos/src/main/java/io/seata/discovery/registry/nacos/NacosRegistryServiceImpl.java
vote for release 1.5.2(https://github.com/seata/seata/milestone/22)
vote result:
@a364176773 @caohdgege @slievrly binding +3
> release: release for 1.5.2

- all/pom.xml
- build/pom.xml
- changes/en-us/1.5.2.md
- changes/en-us/develop.md
- changes/zh-cn/1.5.2.md
- changes/zh-cn/develop.md
- core/src/main/java/io/seata/core/protocol/Version.java
- pom.xml
- server/pom.xml
optimize mysql8 dependencies for seataio/seata-server docker image
fix #4712 
docker run --name=seata-1.5.2 -v /Users/xxxxxx/resources:/seata-server/resources -d seataio/seata-server:1.5.2
> optimize: optimize mysql8 dependencies for seataio/seata-server image

- changes/en-us/develop.md
- changes/zh-cn/develop.md
- config/seata-config-zk/pom.xml
- discovery/seata-discovery-zk/pom.xml
- seata-spring-boot-starter/pom.xml
- server/pom.xml
移除对log4j的依赖
exclude log4j dependencies
fixes #4404
> optimize: exclude log4j dependencies

- .github/workflows/publishes.yml
- build/pom.xml
- changes/en-us/develop.md
- changes/zh-cn/develop.md
- distribution/Dockerfile
optimize: optimize build and fix the base image.
优化：优化构建配置，并修正docker镜像的基础镜像.
fixes #4960
> optimize: optimize build and fix the base image

- changes/en-us/develop.md
- changes/zh-cn/develop.md
- server/src/main/java/io/seata/server/Server.java
- server/src/main/java/io/seata/server/ServerApplicationListener.java
[remove useless code](https://github.com/seata/seata/commit/ed75c1eca07f3e2c9ecab2bb000c64b12b7624f0)
> optimize: remove useless code

- server/src/main/java/io/seata/server/storage/redis/store/RedisLuaTransactionStoreManager.java
- server/src/main/java/io/seata/server/storage/redis/store/RedisTransactionStoreManager.java
- server/src/main/resources/lua/redisStore/deleteTransactionDO.lua
- server/src/main/resources/lua/redisStore/insertTransactionDO.lua
- server/src/main/resources/lua/redisStore/updateGlobalTransactionDO.lua
> feat: redis lua mode support sorted set by timeout

- changes/en-us/develop.md
- changes/zh-cn/develop.md
- rm-datasource/src/main/java/io/seata/rm/datasource/exec/mysql/MySQLInsertOnDuplicateUpdateExecutor.java
> bugfix: error placeholder index in insert on duplicate executor

- changes/en-us/develop.md
- changes/zh-cn/develop.md
- rm-datasource/src/main/java/io/seata/rm/datasource/ConnectionContext.java
> bugfix:NPE caused when there is no @GlobalTransactional annotation on the RM side 

- build/pom.xml
- core/src/main/java/io/seata/core/protocol/Version.java
> optimize: change the version to 1.6.1-SNAPSHOT

- README.md
- build/pom.xml
- changes/en-us/1.6.1.md
- changes/en-us/develop.md
- changes/zh-cn/1.6.1.md
- changes/zh-cn/develop.md
- core/src/main/java/io/seata/core/protocol/Version.java
- saga/seata-saga-statemachine-designer/package-lock.json
vote for release 1.6.1(https://github.com/seata/seata/milestone/26)
vote result:  vote passed
@slievrly  +1 binding
@wangliang181230  +1 binding
@a364176773  +1 binding
> release: release for 1.6.1

- build/pom.xml
- dependencies/pom.xml
- server/pom.xml
> test: fix `test-compile` fails when the version of the `spring-boot` is lower than `2.4.0`

- changes/en-us/develop.md
- changes/zh-cn/develop.md
- console/src/main/java/io/seata/console/utils/JwtTokenUtils.java
- core/src/main/java/io/seata/core/exception/AbstractExceptionHandler.java
- rm-datasource/src/main/java/io/seata/rm/datasource/DataSourceManager.java
- rm-datasource/src/main/java/io/seata/rm/datasource/xa/ResourceManagerXA.java
- server/src/main/java/io/seata/server/coordinator/DefaultCoordinator.java
- server/src/main/java/io/seata/server/coordinator/DefaultCore.java
- server/src/main/java/io/seata/server/session/SessionHolder.java
> optimize: log message level

- changes/en-us/develop.md
- changes/zh-cn/develop.md
- common/src/main/java/io/seata/common/loader/EnhancedServiceLoader.java
issue5228中遇到的问题，无法通过seata日志直接定位到问题根因。
主要原因在于EnhancedServiceLoader.loadFile#cahtch 中的日志打印没有打印详细堆栈信息。
优化了日志打印。
fixes #5228
> optimize: print Stack Trace in EnhancedServiceLoader.loadFile#catch

- changes/en-us/develop.md
- changes/zh-cn/develop.md
- server/src/main/java/io/seata/server/coordinator/DefaultCoordinator.java
- server/src/main/java/io/seata/server/session/GlobalSession.java
- server/src/main/java/io/seata/server/session/SessionHelper.java
- server/src/main/java/io/seata/server/session/SessionLifecycle.java
- server/src/test/java/io/seata/server/session/GlobalSessionTest.java
If `server.session.enable-branch-async-remove` is true, delete the branch asynchronously and unlock it synchronously.
fixes  #4580
> optimize: unlock branch synchronously.

- changes/en-us/2.0.0.md
- changes/zh-cn/2.0.0.md
- core/src/main/java/io/seata/core/rpc/processor/server/ServerOnRequestProcessor.java
fixes #5279 
https://github.com/seata/seata/commit/913ec96fb4e388c0fc0bbc6449b374135745efeb
> bugfix: parallel request handle throw IndexOutOfBoundsException

- changes/en-us/2.0.0.md
- changes/zh-cn/2.0.0.md
- server/src/main/java/io/seata/server/session/SessionHolder.java
- server/src/main/java/io/seata/server/storage/db/session/DataBaseSessionManager.java
- server/src/main/java/io/seata/server/storage/redis/session/RedisSessionManager.java
清除 sessionmanager的多例模式，不再判断taskname
https://github.com/seata/seata/issues/4857
> optimize: clean multi-sessionmanager-instance pattern

- changes/en-us/develop.md
- changes/zh-cn/develop.md
- distribution/bin/seata-server.bat
- distribution/bin/seata-server.sh
Remove startup script the -Xmn configuration
fixes #5290
> optimize: remove startup script the -Xmn configuration

- changes/en-us/2.0.0.md
- changes/zh-cn/2.0.0.md
- common/src/test/java/io/seata/common/holder/ObjectHolderTest.java
- common/src/test/java/io/seata/common/io/FileLoaderTest.java
- common/src/test/java/io/seata/common/util/StringUtilsTest.java
- common/src/test/resources/io/TestFile.txt
Add unit tests of the following classes:
添加如下类的单元测试:
io.seata.common.io.FileLoader
io.seata.common.holder.ObjectHolder
io.seata.common.util.StringUtils
fixes #5305
> test: add unit test[FileLoader, ObjectHolder, StringUtils]

- changes/en-us/2.0.0.md
- changes/zh-cn/2.0.0.md
- server/src/main/java/io/seata/server/storage/file/session/FileSessionManager.java
remove RollbackRetryTimeout sessions during in file storage recover
fix #5298
> bugfix: remove RollbackRetryTimeout sessions during in file storage recover

- changes/en-us/2.0.0.md
- changes/zh-cn/2.0.0.md
- distribution/bin/seata-server.sh
fix G1 jvm parameter in jdk8
fixes #5317
> bugfix: fix G1 jvm parameter in jdk8

- changes/en-us/2.0.0.md
- changes/zh-cn/2.0.0.md
- common/src/main/java/io/seata/common/loader/EnhancedServiceLoader.java
> optimize: optimize EnhancedServiceLoader log

- changes/en-us/2.0.0.md
- changes/zh-cn/2.0.0.md
- common/src/main/java/io/seata/common/loader/ExtensionDefinition.java
- common/src/main/java/io/seata/common/util/LowerCaseLinkHashMap.java
> bugfix: fix some tiny bugs

- changes/en-us/2.0.0.md
- changes/zh-cn/2.0.0.md
- integration/grpc/src/main/java/io/seata/integration/grpc/interceptor/GrpcHeaderKey.java
- integration/grpc/src/main/java/io/seata/integration/grpc/interceptor/client/ClientTransactionInterceptor.java
- integration/grpc/src/main/java/io/seata/integration/grpc/interceptor/server/ServerListenerProxy.java
- integration/grpc/src/main/java/io/seata/integration/grpc/interceptor/server/ServerTransactionInterceptor.java
- integration/grpc/src/test/java/io/seata/integration/grpc/interceptor/GrpcTest.java
optimize gRPC Interceptor for TCC mode
> optimize: optimize gRPC Interceptor for TCC mode

- changes/en-us/2.0.0.md
- changes/zh-cn/2.0.0.md
- integration-tx-api/src/main/java/io/seata/integration/tx/api/fence/config/CommonFenceConfig.java
> optimize: add tcc fence log clean task delay check(2.x)

- changes/en-us/2.0.0.md
- changes/zh-cn/2.0.0.md
- integration/brpc/src/main/java/io/seata/integration/brpc/TransactionPropagationClientInterceptor.java
- integration/brpc/src/main/java/io/seata/integration/brpc/TransactionPropagationServerInterceptor.java
- integration/dubbo-alibaba/src/main/java/io/seata/integration/dubbo/alibaba/AlibabaDubboTransactionPropagationFilter.java
- integration/grpc/src/main/java/io/seata/integration/grpc/interceptor/server/ServerListenerProxy.java
- integration/motan/src/main/java/io/seata/integration/motan/MotanTransactionFilter.java
- integration/sofa-rpc/src/main/java/io/seata/integration/sofa/rpc/TransactionContextConsumerFilter.java
- integration/sofa-rpc/src/main/java/io/seata/integration/sofa/rpc/TransactionContextProviderFilter.java
optimize RPC filter for TCC  mode
> optimize: optimize RPC filter for TCC  mode

- changes/en-us/2.0.0.md
- changes/zh-cn/2.0.0.md
- config/seata-config-core/src/main/java/io/seata/config/ConfigurationFactory.java
- discovery/seata-discovery-core/src/main/java/io/seata/discovery/registry/MultiRegistryFactory.java
- discovery/seata-discovery-core/src/main/java/io/seata/discovery/registry/RegistryFactory.java
- server/src/main/java/io/seata/server/coordinator/DefaultCoordinator.java
- server/src/main/java/io/seata/server/lock/LockerManagerFactory.java
- server/src/main/java/io/seata/server/session/SessionHolder.java
> optimize: add config type,registry type,store mode log 

- rm-datasource/src/test/java/io/seata/rm/datasource/exec/MultiExecutorTest.java
> test: fix UpdateExecutorTest failed

- changes/en-us/2.0.0.md
- changes/zh-cn/2.0.0.md
- core/src/main/java/io/seata/core/exception/TransactionExceptionCode.java
- core/src/main/java/io/seata/core/model/GlobalStatus.java
- integration-tx-api/src/main/java/io/seata/integration/tx/api/interceptor/handler/GlobalTransactionalInterceptorHandler.java
- tm/src/main/java/io/seata/tm/api/DefaultFailureHandlerImpl.java
- tm/src/main/java/io/seata/tm/api/FailureHandler.java
- tm/src/main/java/io/seata/tm/api/TransactionalExecutor.java
- tm/src/main/java/io/seata/tm/api/TransactionalTemplate.java
optimize transaction fail handler
fix #5362
> optimize: optimize transaction fail handler

- .github/workflows/test.yml
- build/pom.xml
- core/src/main/java/io/seata/core/protocol/Version.java
- dependencies/pom.xml
> release 1.7.0-native-rc2

- changes/en-us/2.0.0.md
- changes/zh-cn/2.0.0.md
- dependencies/pom.xml
fix multi spring version test failed
fix #5381
> test: fix multi spring version test failed

- changes/en-us/2.0.0.md
- changes/zh-cn/2.0.0.md
- config/seata-config-core/src/test/java/io/seata/config/ConfigFutureTest.java
- config/seata-config-core/src/test/java/io/seata/config/ConfigTypeTest.java
- config/seata-config-core/src/test/java/io/seata/config/ConfigurationCacheTests.java
- config/seata-config-core/src/test/java/io/seata/config/ConfigurationChangeEventTest.java
- config/seata-config-core/src/test/java/io/seata/config/file/SimpleFileConfigTest.java
- config/seata-config-core/src/test/java/io/seata/config/file/YamlFileConfigTest.java
- config/seata-config-core/src/test/java/io/seata/config/processor/ConfigDataTypeTest.java
- config/seata-config-core/src/test/java/io/seata/config/processor/ConfigProcessorTest.java
- config/seata-config-core/src/test/java/io/seata/config/processor/ProcessorPropertiesTest.java
> test: add unit test for config module

- changes/en-us/develop.md
- changes/zh-cn/develop.md
- tm/src/main/java/io/seata/tm/api/TransactionalTemplate.java
…ailureHandler
fix transaction timeout on client side not execute hook and failureHandler
fix #5373  #5374
> bugfix: fix transaction timeout on client side not execute hook and failureHandler

- README.md
> optimize: optimize contact information

- changes/en-us/develop.md
- changes/zh-cn/develop.md
- rm-datasource/src/main/java/io/seata/rm/datasource/util/SeataXAResource.java
- rm-datasource/src/main/java/io/seata/rm/datasource/xa/ConnectionProxyXA.java
> bugfix: oracle xa mode cannnot be used By same database

- console/src/main/resources/static/console-fe/README.md
> doc: update console-fe readme

- .github/workflows/license-checker.yaml
- .licenserc.yaml
- changes/en-us/2.0.0.md
- changes/zh-cn/2.0.0.md
exclude some incompatible license
> optimize: exclude some incompatible license

- changes/en-us/develop.md
- changes/zh-cn/develop.md
- integration-tx-api/src/main/java/io/seata/integration/tx/api/interceptor/handler/GlobalTransactionalInterceptorHandler.java
…everHappenException will be thrown
fix #5460 
#5459
> bugfix: fix using @GlobalTransactional in provider ShouldNeverHappenException  thrown

- .github/ISSUE_TEMPLATE/BUG_REPORT.md
- .github/ISSUE_TEMPLATE/FEATURE_REQUEST.md
- README.md
- SECURITY.md
> docs: add security docs

- .github/ISSUE_TEMPLATE/BUG_REPORT.md
- .github/ISSUE_TEMPLATE/FEATURE_REQUEST.md
- changes/en-us/2.0.0.md
- changes/zh-cn/2.0.0.md
- integration-tx-api/src/main/java/io/seata/integration/tx/api/fence/store/CommonFenceStore.java
- integration-tx-api/src/main/java/io/seata/integration/tx/api/fence/store/db/CommonFenceStoreDataBaseDAO.java
- integration-tx-api/src/main/java/io/seata/integration/tx/api/fence/store/db/sql/CommonFenceStoreSqls.java
- spring/src/main/java/io/seata/rm/fence/SpringFenceHandler.java
optimize FenceHandler for oracle
> optimize: optimize FenceHandler for oracle

- changes/en-us/2.0.0.md
- changes/zh-cn/2.0.0.md
- server/src/main/java/io/seata/server/coordinator/DefaultCoordinator.java
- server/src/main/java/io/seata/server/session/GlobalSession.java
- server/src/main/java/io/seata/server/session/SessionHelper.java
fix GlobalStatus=9 can't be cleared in DB storage mode
fix #5418
> bugfix: fix GlobalStatus=9 can't be cleared in DB storage mode

- changes/en-us/2.0.0.md
- changes/zh-cn/2.0.0.md
- dependencies/pom.xml
- distribution/bin/seata-server.bat
- distribution/bin/seata-server.sh
- server/pom.xml
- server/src/main/resources/logback-spring.xml
> bugfix: the log file path was loaded incorrectly

- changes/en-us/develop.md
- changes/zh-cn/develop.md
- dependencies/pom.xml
- distribution/bin/seata-server.bat
- distribution/bin/seata-server.sh
- server/pom.xml
- server/src/main/resources/logback-spring.xml
> bugfix: fix log file path was loaded incorrectly

- changes/en-us/develop.md
- changes/zh-cn/develop.md
- rm-datasource/src/main/java/io/seata/rm/datasource/DataSourceManager.java
- rm/src/main/java/io/seata/rm/AbstractResourceManager.java
- test/src/test/java/io/seata/saga/engine/mock/MockGlobalTransaction.java
- tm/src/main/java/io/seata/tm/api/DefaultGlobalTransaction.java
- tm/src/main/java/io/seata/tm/api/GlobalTransaction.java
- tm/src/main/java/io/seata/tm/api/TransactionalTemplate.java
optimize transaction log on client side
fix ##5471
> optimize: optimize transaction log on client side

- changes/en-us/develop.md
- changes/zh-cn/develop.md
- core/src/main/java/io/seata/core/exception/TransactionExceptionCode.java
- core/src/main/java/io/seata/core/model/GlobalStatus.java
- server/src/main/java/io/seata/server/session/GlobalSession.java
- tm/src/main/java/io/seata/tm/api/TransactionalTemplate.java
fix finished transaction swallows exception when committing 
fix #5478
> bugfix: fix finished transaction swallows exception when committing 

- .github/workflows/publish-docker.yml
- .github/workflows/publish-ossrh.yml
- build/pom.xml
- changes/en-us/develop.md
- changes/zh-cn/develop.md
update expire gpg key and publish workflow
> optimize: update expire gpg key and publish workflow

- changes/en-us/2.0.0.md
- changes/zh-cn/2.0.0.md
- script/client/at/db/oracle.sql
- script/client/at/db/postgresql.sql
fix oracle insert undolog failed
fixes #5498  #5555
> bugfix: fix oracle insert undolog failed

- changes/en-us/2.0.0.md
- changes/zh-cn/2.0.0.md
- rm-datasource/src/main/java/io/seata/rm/datasource/undo/AbstractUndoExecutor.java
- rm-datasource/src/main/java/io/seata/rm/datasource/undo/AbstractUndoLogManager.java
- rm-datasource/src/test/java/io/seata/rm/datasource/undo/BaseH2Test.java
- rm-datasource/src/test/java/io/seata/rm/datasource/undo/UndoExecutorTest.java
> bugfix: fix mariadb rollback failed

- changes/en-us/2.0.0.md
- changes/zh-cn/2.0.0.md
- metrics/seata-metrics-core/src/test/java/io/seata/metrics/exporter/ExporterTypeTest.java
- metrics/seata-metrics-core/src/test/java/io/seata/metrics/registry/RegistryTypeTest.java
Add unit test case for ExporterType/RegistryType
> test: add unit test case for ExporterType/RegistryType

- changes/en-us/develop.md
- changes/zh-cn/develop.md
- tm/src/main/java/io/seata/tm/api/DefaultGlobalTransaction.java
- tm/src/main/java/io/seata/tm/api/TransactionalTemplate.java
同步修复 https://github.com/seata/seata/pull/5594 2.0已修复的问题
fixes https://github.com/seata/seata/issues/5567
> bugfix: fix log in participant transaction role

- changes/en-us/2.0.0.md
- changes/zh-cn/2.0.0.md
- core/src/test/java/io/seata/core/message/RegisterTMResponseTest.java
- core/src/test/java/io/seata/core/protocol/BatchResultMessageTest.java
- core/src/test/java/io/seata/core/protocol/HeartbeatMessageTest.java
- core/src/test/java/io/seata/core/protocol/MergeResultMessageTest.java
- core/src/test/java/io/seata/core/protocol/MergedWarpMessageTest.java
- core/src/test/java/io/seata/core/protocol/RegisterRMResponseTest.java
- core/src/test/java/io/seata/core/protocol/ResultCodeTest.java
- core/src/test/java/io/seata/core/protocol/VersionTest.java
Add unit test case for request/response messages
> test: add unit test for transaction messages

- changes/en-us/2.0.0.md
- changes/zh-cn/2.0.0.md
- discovery/seata-discovery-core/src/main/java/io/seata/discovery/registry/MultiRegistryFactory.java
- server/src/main/java/io/seata/server/ServerRunner.java
- server/src/main/resources/logback-spring.xml
> optimize: optimize server logs print

- changes/en-us/develop.md
- changes/zh-cn/develop.md
- config/seata-config-core/src/main/java/io/seata/config/exception/ConfigNotFoundException.java
- core/src/main/java/io/seata/core/rpc/netty/NettyClientChannelManager.java
- discovery/seata-discovery-consul/src/main/java/io/seata/discovery/registry/consul/ConsulRegistryServiceImpl.java
- discovery/seata-discovery-core/src/main/java/io/seata/discovery/registry/FileRegistryServiceImpl.java
- discovery/seata-discovery-etcd3/src/main/java/io/seata/discovery/registry/etcd3/EtcdRegistryServiceImpl.java
- discovery/seata-discovery-eureka/src/main/java/io/seata/discovery/registry/eureka/EurekaRegistryServiceImpl.java
- discovery/seata-discovery-nacos/src/main/java/io/seata/discovery/registry/nacos/NacosRegistryServiceImpl.java
- discovery/seata-discovery-redis/src/main/java/io/seata/discovery/registry/redis/RedisRegistryServiceImpl.java
- discovery/seata-discovery-sofa/src/main/java/io/seata/discovery/registry/sofa/SofaRegistryServiceImpl.java
- discovery/seata-discovery-zk/src/main/java/io/seata/discovery/registry/zk/ZookeeperRegisterServiceImpl.java
- discovery/seata-discovery-zk/src/test/java/io/seata/discovery/registry/zk/ZookeeperRegisterServiceImplTest.java
- seata-spring-autoconfigure/seata-spring-autoconfigure-core/src/main/java/io/seata/spring/boot/autoconfigure/provider/SpringBootConfigurationProvider.java
fix compatibility between xxx.grouplist and grouplist.xxx
fix #5649
> bugfix: fix compatibility between xxx.grouplist and grouplist.xxx

- changes/en-us/develop.md
- changes/zh-cn/develop.md
- saga/seata-saga-engine/src/main/java/io/seata/saga/engine/impl/ProcessCtrlStateMachineEngine.java
FIX [5672](https://github.com/seata/seata/issues/5672)
>  bugfix: fix saga mode replay context lost start

- .github/workflows/build.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/license-checker.yaml
- .github/workflows/publish-docker.yml
- .github/workflows/test.yml
- changes/en-us/develop.md
- changes/zh-cn/develop.md
optimize github actions for CodeQL, skywalking-eyes
fix https://github.blog/changelog/2023-01-18-code-scanning-codeql-action-v1-is-now-deprecated/
> optimize: optimize github actions for CodeQL, skywalking-eyes

- changes/en-us/develop.md
- changes/zh-cn/develop.md
- console/src/main/resources/static/index.html
- server/src/main/resources/application.yml
fix console jwt error
fix #5689 
cherry-pick #5347
> bugfix: fix console jwt error

- README.md
- build/pom.xml
- changes/en-us/1.7.0.md
- changes/en-us/develop.md
- changes/zh-cn/1.7.0.md
- changes/zh-cn/develop.md
change version to 1.7.1-SNAPSHOT
> version: change version to 1.7.1-SNAPSHOT

- changes/en-us/2.0.0.md
- changes/zh-cn/2.0.0.md
- distribution/Dockerfile
- server/pom.xml
optimize docker timezone
fix #5722
> optimize: optimize docker timezone

- changes/en-us/2.0.0.md
- changes/zh-cn/2.0.0.md
- common/src/main/java/io/seata/common/ConfigurationKeys.java
- config/seata-config-core/src/main/java/io/seata/config/ConfigurationFactory.java
- config/seata-config-core/src/main/java/io/seata/config/FileConfiguration.java
- config/seata-config-core/src/main/java/io/seata/config/file/FileConfig.java
- config/seata-config-core/src/main/java/io/seata/config/file/SimpleFileConfig.java
- config/seata-config-core/src/main/java/io/seata/config/file/YamlFileConfig.java
- seata-spring-autoconfigure/seata-spring-autoconfigure-core/src/test/java/io/seata/spring/boot/autoconfigure/properties/config/test/ConfigPropertiesTest.java
- seata-spring-autoconfigure/seata-spring-autoconfigure-core/src/test/resources/application-test.properties
- server/src/main/java/io/seata/server/spring/listener/SeataPropertiesLoader.java
- server/src/main/java/io/seata/server/spring/listener/ServerApplicationListener.java
- server/src/main/resources/META-INF/spring.factories
- server/src/main/resources/application.yml
- server/src/test/java/io/seata/server/LoaderConfTest.java
- server/src/test/resources/file.conf
- server/src/test/resources/registry.conf
https://github.com/seata/seata/pull/5668
> feature: compatible with file.conf and registry.conf configurations

- all/pom.xml
- dependencies/pom.xml
fix some dependencies vulnerability
> security: fix some dependencies vulnerability

- changes/en-us/develop.md
- changes/zh-cn/develop.md
- common/src/main/java/io/seata/common/Constants.java
- core/src/main/java/io/seata/core/context/RootContext.java
- integration/sofa-rpc/src/main/java/io/seata/integration/sofa/rpc/TransactionContextConsumerFilter.java
- integration/sofa-rpc/src/main/java/io/seata/integration/sofa/rpc/TransactionContextProviderFilter.java
- integration/sofa-rpc/src/test/java/io/seata/integration/sofa/rpc/TransactionContextFilterTest.java
> bugfix: fix the key parameter problem of sofa-rpc setAttachment method(develop)

- all/pom.xml
- changes/en-us/2.0.0.md
- changes/zh-cn/2.0.0.md
- dependencies/pom.xml
security: fix some dependencies vulnerability 
cherry-pick #5728
> security: fix some dependencies vulnerability 

- changes/en-us/2.0.0.md
- changes/zh-cn/2.0.0.md
- server/src/main/java/io/seata/server/store/DbcpDataSourceProvider.java
- server/src/main/java/io/seata/server/store/DruidDataSourceProvider.java
- server/src/main/java/io/seata/server/store/HikariDataSourceProvider.java
optimize: set server's transaction level to READ_COMMITTED
cherry-pick #5638
> optimize: set server's transaction level to READ_COMMITTED

- .travis.yml
- changes/en-us/develop.md
- changes/zh-cn/develop.md
- distribution/bin/seata-setup.sh
- server/pom.xml
- server/src/main/resources/docker/seata-server-entrypoint.sh
docker image supports JVM parameter injection
cherry pick  #5529
> feature: docker image supports JVM parameter injection

- distribution/bin/seata-server.sh
optimize: support for more operational commands in seata-server.sh
cherry-pick #5524
> optimize: support for more operational commands in seata-server.sh

- changes/en-us/develop.md
- changes/zh-cn/develop.md
- core/src/main/java/io/seata/core/constants/DBType.java
- rm-datasource/src/main/java/io/seata/rm/datasource/util/JdbcUtils.java
- rm-datasource/src/main/java/io/seata/rm/datasource/xa/ConnectionProxyXA.java
- sqlparser/seata-sqlparser-core/src/main/java/io/seata/sqlparser/util/JdbcConstants.java
…d by druid dependency conflict
1. 使用Seata的`JdbcUtils`和`JdbcConstants`分别获取dbType，判断dbType是否是特定的类型，避免druid依赖冲突导致的异常
2. 补充数据库的类型
fixes #5775
> bugfix: fix XA transaction start exception and rollback failure

- changes/en-us/develop.md
- changes/zh-cn/develop.md
- discovery/seata-discovery-nacos/src/main/java/io/seata/discovery/registry/nacos/NacosRegistryServiceImpl.java
- script/client/spring/application.properties
- script/client/spring/application.yml
- seata-spring-autoconfigure/seata-spring-autoconfigure-core/src/main/java/io/seata/spring/boot/autoconfigure/properties/registry/RegistryNacosProperties.java
optimize: support the nacos application name property
cherry-pick #5783
> optimize: support the nacos application name property

- changes/en-us/2.0.0.md
- changes/zh-cn/2.0.0.md
- rm-datasource/src/main/java/io/seata/rm/datasource/exec/BaseTransactionalExecutor.java
- rm-datasource/src/main/java/io/seata/rm/datasource/exec/MultiUpdateExecutor.java
- rm-datasource/src/main/java/io/seata/rm/datasource/exec/UpdateExecutor.java
- rm-datasource/src/main/java/io/seata/rm/datasource/exec/mysql/MySQLUpdateJoinExecutor.java
- rm-datasource/src/main/java/io/seata/rm/datasource/exec/sqlserver/SqlServerUpdateExecutor.java
> bugfix: insert executor keywords unescape

- .github/workflows/build.yml
- .github/workflows/publish-docker.yml
- .github/workflows/publish-ossrh.yml
- .github/workflows/test.yml
- changes/en-us/develop.md
- changes/zh-cn/develop.md
upgrade some deprecated github actions
fix #5767
> optimize: upgrade some deprecated github actions

- build/pom.xml
- changes/en-us/1.7.1.md
- changes/en-us/develop.md
- changes/zh-cn/1.7.1.md
- changes/zh-cn/develop.md
change version to 1.8.0-SNAPSHOT
> version: change version to 1.8.0-SNAPSHOT

- changes/en-us/2.0.0.md
- changes/zh-cn/2.0.0.md
- server/src/main/java/io/seata/server/session/BranchSession.java
fix delete branch table unlock failed
> bugfix:fix delete branch table unlock failed

- dependencies/pom.xml
remove dependency without license 
cherry-pick #5889
> optimize: remove dependency without license 

- changes/en-us/develop.md
- changes/zh-cn/develop.md
- dependencies/pom.xml
- discovery/seata-discovery-etcd3/pom.xml
upgrade native-lib-loader version
> optimize: upgrade native-lib-loader version

- changes/en-us/2.0.0.md
- changes/zh-cn/2.0.0.md
- distribution/bin/seata-server.bat
- distribution/bin/seata-setup.sh
fixes #5269
1. `export JMX_ENABLE=true`
2.  run in local machine, check the opts
> optimize: support jmx port in seata

- changes/en-us/2.0.0.md
- changes/zh-cn/2.0.0.md
- console/src/main/resources/static/console-fe/package-lock.json
- console/src/main/resources/static/console-fe/package.json
- saga/seata-saga-statemachine-designer/package-lock.json
- saga/seata-saga-statemachine-designer/package.json
> security: upgrade dependencies version

- build/pom.xml
- changes/en-us/2.0.0.md
- changes/zh-cn/2.0.0.md
> optimize: remove unsupport config in jdk17

- server/src/main/java/io/seata/server/cluster/raft/sync/msg/dto/BranchTransactionDTO.java
- server/src/main/java/io/seata/server/cluster/raft/sync/msg/dto/GlobalTransactionDTO.java
- server/src/main/java/io/seata/server/storage/SessionConverter.java
> optimize: modify code style and remove unused import

- changes/en-us/develop.md
- changes/zh-cn/develop.md
- dependencies/pom.xml
try fix zookeeper UT failed
fixes #5923
fixes #5952
> test: fix zookeeper UT failed

- changes/en-us/develop.md
- changes/zh-cn/develop.md
- seata-spring-autoconfigure/seata-spring-autoconfigure-core/src/main/resources/META-INF/additional-spring-configuration-metadata.json
> bugfix: fix some configurations that are not deprecated show "Deprecated"

- README.md
- build/pom.xml
- changes/en-us/1.7.1.md
- changes/en-us/1.8.0.md
- changes/en-us/develop.md
- changes/zh-cn/1.7.1.md
- changes/zh-cn/1.8.0.md
- changes/zh-cn/develop.md
- distribution/bin/seata-server.bat
- distribution/bin/seata-setup.sh
vote for release 1.8.0 (https://github.com/seata/seata/milestone/30)
result:
+4 binding
- @funky-eyes 
- @leizhiyuan 
- @xingfudeshi 
- @slievrly 
vote result:
> release: release for 1.8.0

- changes/zh-cn/1.8.0.md
> optimize: fix 1.8.0 release notes
