core/src/main/java/com/alibaba/fescar/core/exception/AbstractExceptionHandler.java
rm-datasource/src/main/java/com/alibaba/fescar/rm/AbstractRMHandlerAT.java
server/src/main/java/com/alibaba/fescar/server/AbstractTCInboundHandler.java

This PR renames `AbstractExceptionHander` to `AbstractExceptionHandler` which I believe was a typo.

Rename AbstractExceptionHander to AbstractExceptionHandler

---

core/src/main/java/com/alibaba/fescar/core/rpc/netty/AbstractRpcRemotingServer.java

#79, Expection fired when using server = "NATIVE" on Linux

#79, Expection fired when using server = "NATIVE" on Linux

---

config/pom.xml
pom.xml

of netty-transport-native-epoll and netty-transport-native-kqueue. (#97 )

#97, remove the redundant dependencies

---

core/src/main/java/com/alibaba/fescar/core/rpc/netty/AbstractRpcRemotingClient.java

add cause to FrameworkException to expose the actual exception

---

server/src/main/java/com/alibaba/fescar/server/store/FileTransactionStoreManager.java

FileTransactionStoreManager#closeFile() method remove redundant fileChannel.close() invoke
fix #127

fix #127 remove redundant fileChannel.close() invoke

---

core/src/main/java/com/alibaba/fescar/core/rpc/netty/AbstractRpcRemotingServer.java
server/src/main/java/com/alibaba/fescar/server/store/FileTransactionStoreManager.java

Netty `SO_KEEPALIVE` option not works on `ServerBootstrap#option()`, should replace with `ServerBootstrap#childOption()`
fix #150

fix #150 use ServerBootstrap#childOption() to set SO_KEEPALIVE

---

core/src/main/java/com/alibaba/fescar/core/rpc/netty/AbstractRpcRemoting.java

ths isSending flag should be set as volatile type for multi-thread read and write without synchronized

ths isSending flag should be set as volatile type for multi-thread read and write without synchronized

---

rm-datasource/src/main/java/com/alibaba/fescar/rm/datasource/exec/AbstractDMLBaseExecutor.java

com.alibaba.fescar.rm.datasource.exec.AbstractDMLBaseExecutor#executeAutoCommitTrue
rollback physical connection before retrying to get global lock again
https://github.com/alibaba/fescar/issues/324

fix #324 rollback physical connection before retrying to get global lock again

---

server/src/main/java/com/alibaba/fescar/server/Server.java

FIX https://github.com/alibaba/fescar/issues/342 , user can modify ip by manual

Add IpAddress by args

---

core/pom.xml

Signed-off-by: zhengyangyong <yangyong.zheng@qq.com>
delete useless fescar-common in fescar-core because fescar-config had imported it
run fescar demo passed

delete useless fescar-common in fescar-core because fescar-config had imported it

---

server/src/main/java/com/alibaba/fescar/server/UUIDGenerator.java
server/src/test/java/com/alibaba/fescar/server/UUIDGeneratorOverflowTest.java

Fixed UUIDGenerator Algorithm bug: when the nodeId is greater than 1, it will not work as expected.
fixes #387
unit test also included
run the unit test UUIDGeneratorOverflowTest

Fixed issue #387: UUIDGenerator Algorithm bug

---

core/src/main/java/com/alibaba/fescar/core/rpc/netty/NettyClientConfig.java
core/src/main/java/com/alibaba/fescar/core/rpc/netty/RmRpcClient.java
core/src/main/java/com/alibaba/fescar/core/rpc/netty/TmRpcClient.java
core/src/test/java/com/alibaba/fescar/core/rpc/netty/TmRpcClientTest.java

Rename the member variable DEFAULT_POOL_FIFO in the NettyClientConfig class, Because the config object is actually assigned to a LIFO rather than a FIFO
Because it already exists

NettyClientConfig Class member variable named incorrectly

---

common/src/main/java/com/alibaba/fescar/common/thread/RejectedPolicys.java
common/src/test/java/com/alibaba/fescar/common/thread/RejectedPolicysTest.java
core/src/main/java/com/alibaba/fescar/core/rpc/netty/TmRpcClient.java

add run oldest task reject policy when task queue is full
fix #466 
add RejectedPolicysTest verify the policy
when add new task; the oldest task in queue run first

fix #466 add run oldest task reject policy

---

common/src/test/java/com/alibaba/fescar/common/StringUtilsTest.java
common/src/test/java/com/alibaba/fescar/common/XIDTest.java
common/src/test/java/com/alibaba/fescar/common/exception/FrameworkExceptionTest.java
common/src/test/java/com/alibaba/fescar/common/exception/Message.java

add test for FrameworkException
fix #195 
already add
run ut first

[Test-1] add test for FrameworkException

---

server/src/main/java/com/alibaba/fescar/server/session/SessionHolder.java
server/src/test/java/com/alibaba/fescar/server/session/SessionHolderTest.java

Uses hardcoded file separator will cause cross-platform file path problems,so we must use some way platform independent to avoid it.Uses File.separator is one of the best way.
fixes #522.Use File.separator instead of Hardcoded file separator.
fixes #522
i have added a unit test
I have searched all code block,ensure that only this code has this problem so far.

fixes #522.Use File.separator instead of Hardcoded file separator.

---

discovery/src/main/java/com/alibaba/fescar/discovery/registry/EurekaRegistryServiceImpl.java

if user / to splicing instanceId,the renew request will to ***/name/ip:port, but should to ***/(name/ip:port) ,change the instanceId to name:ip:port
add unified the key uppercase,from eureka cluster name is uppercase
fixes #569

fix up ,eureka client renew request is error#569

---

rm-datasource/src/main/java/com/alibaba/fescar/rm/datasource/undo/UndoLogManager.java

Fix #489 
fixes #489 
A, B two processes, perform the following steps:
1. A initiates a global transaction
2. B registration branch transaction succeeded
3. B service processing time is greater than the RPC timeout period.
4. A receives the RPC timeout and initiates a global transaction rollback.
5. After the global transaction is rolled back, the business of B is processed.

fix #489 when GlobalRollback but not receive report

---

README.md

add Mailing list and subscribe method in the README.md
yes

add Mailing list and subscribe method

---

spring/src/main/java/com/alibaba/fescar/spring/annotation/GlobalTransactionalInterceptor.java

Fix #576
fixes #576
test on fescar-samples
1. enable `<aop:aspectj-autoproxy />`
2. create Aspect
```java
@Aspect
public class MyAspect {
@Before("execution(* com.alibaba.fescar.samples.dubbo.service.impl.BusinessServiceImpl.purchase(..))")
public void before(){
}
}
```
GlobalTransactionScanner can correctly detect @GlobalTransactional

fix #576 when target is jdk-proxy, GlobalTransactional not function

---

rm-datasource/src/main/java/com/alibaba/fescar/rm/datasource/exec/InsertExecutor.java
rm-datasource/src/test/java/com/alibaba/fescar/rm/datasource/exec/InsertExecutorTest.java

when pk auto generated and  value is null, fescar can not get the pk value .
fix #357

fix #357 pk auto generated but value is null

---

core/src/main/java/com/alibaba/fescar/core/rpc/netty/AbstractRpcRemotingServer.java
core/src/main/java/com/alibaba/fescar/core/rpc/netty/NettyServerConfig.java
discovery/src/main/java/com/alibaba/fescar/discovery/registry/RedisRegistryServiceImpl.java

1. modify the FileConfiguration in the RedisRegistry.Let it use registry.conf
2. fix uese redis registry, if restart or close the redis coudn't unregister the server.But still can't prevent kill -9.
the second commit ：
Add shutdownHook, For graceful shutdown.
this can replace the shutdownHook in the RedisRegistry.Another benefit is that the shutdown code is unified

fix: RedisRegistry's problems

---

spring/src/main/java/com/alibaba/fescar/spring/util/SpringProxyUtils.java

In the process of integrating spring-cloud-alibaba-stream-rocketmq with fescar, I throw a null pointer exception in the fescar-spring module's com.alibaba.fescar.spring.annotation.GlobalTransactionScanner. I found that com.alibaba was called. The .fescar.spring.util.SpringProxyUtils#findTargetClass method will recursively call target.getClass() when it gets the target object of the proxy class to generate a null pointer. The jdkProxy object generated by @EnableBinding has no target object, and there may be similar in the future. The scene, such as the proxy object generated by interface + annotation in Feign, also has no target object.
So I am modifying the com.alibaba.fescar.spring.util.SpringProxyUtils#findTargetClass part of the code:
`public static Class<?> findTargetClass(Object …

fix: throw NPE when jdk-proxy has no target

---

discovery/src/main/java/com/alibaba/fescar/discovery/registry/NacosRegistryServiceImpl.java

when use Nacos as our discovery service,
we should always use IP address instead of Hostname to register or unregister to Nacos.otherwise,you will get the following exceptions:
`01 2019-03-29 09:42:21.164 ERROR [main :c.a.n.c.naming] [] [] [CALL-SERVER] failed to req API:http://localhost:8848/nacos/v1/ns/instance. code:400 msg: instance format invalid:CHINA-20181022Z:8091:unknown:default_1.0_true_false_default
01 2019-03-29 09:42:21.166 ERROR [main :c.a.n.c.naming] [] [] [NA] req api:/nacos/v1/ns/instance failed, server(localhost
com.alibaba.nacos.api.exception.NacosException: null
at com.alibaba.nacos.client.naming.net.NamingProxy.callServer(NamingProxy.java:333)
at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:358)
at …

fix #647 uses IP address to register or unregister to Nacos

---

server/src/main/java/com/alibaba/fescar/server/session/BranchSession.java
server/src/main/java/com/alibaba/fescar/server/session/GlobalSession.java
server/src/main/java/com/alibaba/fescar/server/store/FileTransactionStoreManager.java

In the code, there are many bytebuffers created but not reused. To reduce the number of YGC, ByteBuffer is reused.
I first read netty's recycle and implemented it. But this is a big change and will make the byte[] that was previously returned by SessionStorable into one of our custom objects, so I dropped it.
Then I looked at other store's system, such as RocketMq, which use ThreadLocal for caching,.it is simple and has very little momentum.
I ran the write part of WriteStoreTest, the VM parameter was -Xmx10m, the YGC was 3,400 times before the modification, and the YGC was 900 times after the modification.
I also changed the HeapByteBuffer used by Filechannel to DirectHeapByteBuffer.
run write part of WriteStoreTest, VM parameter -Xmx10m
wathching jstat -gc pid 1000

add: recycle buffer

---

core/src/main/java/com/alibaba/fescar/core/rpc/netty/AbstractRpcRemotingClient.java

https://github.com/seata/seata/issues/724.
1.In the MergedSendRunnable class, the connect method can throw a FrameworkException that causes the run method to permanently close.
2.MessageFuture will wait until the timeout, which I've optimized.

bugfix:MergedSendRunnable can be closed by accident

---

core/src/main/java/com/alibaba/fescar/core/rpc/netty/RpcServer.java

https://github.com/seata/seata/issues/722.
In the onTrxMessage method, each message is added to the queue. But the runnable, which does not start the consumption queue, results in OOM.

bugfix:the defaultServerMessageListener not init issue

---

core/src/main/java/com/alibaba/fescar/core/rpc/netty/AbstractRpcRemoting.java
discovery/src/main/java/com/alibaba/fescar/discovery/registry/ZookeeperRegisterServiceImpl.java

this can replace the shutdownHook in the RedisRegistry.Another benefit is that the shutdown code is unified
1.fix ZK USES persistent nodes and does not support disconnected reconnections
2.A Chinese document has been modified

FIX:fix ZK Register bugs

---

config/src/main/java/com/alibaba/fescar/config/ZookeeperConfiguration.java
discovery/src/main/java/com/alibaba/fescar/discovery/registry/EurekaRegistryServiceImpl.java

1.Remove redundant static keywords
2.initial size of map.
3.lazy load of some object.
#753 

bugfix:code optimization of EurekaRegistryServiceImpl

---

config/src/main/java/com/alibaba/fescar/config/FileConfiguration.java

when listeners change, add or remove the config correspond to the config id, as the config change, it mean current config different from the config in listenconfigmap, the listener match that config should be called

bugfix:fix FileConfiguration config listener logic 

---

server/src/main/java/com/alibaba/fescar/server/coordinator/DefaultCore.java
server/src/main/java/com/alibaba/fescar/server/session/SessionHelper.java

replace magic judge of timeout status with status enum, Timeout is confused here.
It does not need a test case, we can ensure by the code 
review

replace magic judgement of timeout status with status enum

---

core/src/main/java/io/seata/core/protocol/RegisterRMRequest.java

fix bug for decode regist rm request

---

rm-datasource/src/main/java/io/seata/rm/datasource/exec/ExecuteTemplate.java
rm-datasource/src/main/java/io/seata/rm/datasource/exec/SelectForUpdateExecutor.java

Signed-off-by: hongwei yi <hongweiyi@hotmail.com>
support Statement#execute for SELECT_FOR_UPDATE
fixes #870 
I've tested this in seata-examples. BTW, Seata need more test cases in the project.
Connection conn = dataSourceProxy.getConnection();
Statement stmt = conn.createStatement();
stmt.execute("select * from table where id=? for update");

bugfix:support Statement#execute for SELECT_FOR_UPDATE

---

core/src/main/java/io/seata/core/rpc/netty/NettyBaseConfig.java

init default value for import config
fix #873

fix #873 init default value for import config

---

discovery/seata-discovery-zk/pom.xml
discovery/seata-discovery-zk/src/main/java/io/seata/discovery/registry/zk/ZookeeperRegisterServiceImpl.java
discovery/seata-discovery-zk/src/test/java/io/seata/discovery/registry/zk/ZookeeperRegisterServiceImplTest.java
discovery/seata-discovery-zk/src/test/java/io/seata/discovery/registry/zk/ZookeeperRegistryProviderTest.java

- fixes #900 
- add test case.
Fixes #900

Fix ZkNoNodeException when zookeeper server is empty.

---

core/src/main/java/io/seata/core/rpc/netty/RmRpcClient.java
core/src/main/java/io/seata/core/rpc/netty/TmRpcClient.java

The return type of `ctx.channel().remoteAddress()`  isn't  `String`.I changed it.

change the key type to `String`

---

server/src/main/java/io/seata/server/Server.java

Reuse the same coordinator instance
fixes #924 
did not change logic
CI passed
null

Reuse the same coordinator instance. resolve #924

---

server/src/main/java/io/seata/server/session/GlobalSession.java

fix restTime bug

---

server/src/main/java/io/seata/server/store/FileTransactionStoreManager.java
server/src/main/java/io/seata/server/store/TransactionStoreManager.java

when occurs exceptions, if will can not read data any more, because we flip twice.
```
@Test
public void test(){
ByteBuffer byteBuffer = ByteBuffer.allocateDirect(1024);
byteBuffer.putInt(123);
byteBuffer.flip();
byteBuffer.flip();
while (byteBuffer.hasRemaining()) {
//
System.out.println(byteBuffer.get());
}
}
```
this test case will print nothing, only if you fix this bug

fix bug of flip multi times

---

core/src/main/java/io/seata/core/exception/AbstractExceptionHandler.java
rm/src/main/java/io/seata/rm/AbstractRMHandler.java
server/src/main/java/io/seata/server/AbstractTCInboundHandler.java
server/src/main/java/io/seata/server/session/AbstractSessionManager.java
server/src/main/java/io/seata/server/session/SessionHolder.java
server/src/main/java/io/seata/server/session/SessionManager.java
server/src/test/java/WriteStoreMultithreadTest.java
server/src/test/java/WriteStoreTest.java

fix global status is null
fixes https://github.com/seata/seata/issues/922
notice！ here, when occurs exception, what the correct global status should we return? please review it. I can change it later.

refactor: exceptionHandleTemplate

---

all/pom.xml
bom/pom.xml
integration/sofa-rpc/pom.xml
integration/sofa-rpc/src/main/java/io/seata/integration/sofa/rpc/TransactionContextConsumerFilter.java
integration/sofa-rpc/src/main/java/io/seata/integration/sofa/rpc/TransactionContextProviderFilter.java
integration/sofa-rpc/src/main/resources/META-INF/services/com.alipay.sofa.rpc.filter.Filter
integration/sofa-rpc/src/test/java/io/seata/integration/sofa/rpc/HelloService.java
integration/sofa-rpc/src/test/java/io/seata/integration/sofa/rpc/HelloServiceImpl.java
integration/sofa-rpc/src/test/java/io/seata/integration/sofa/rpc/HelloServiceProxy.java
integration/sofa-rpc/src/test/java/io/seata/integration/sofa/rpc/TransactionContextFilterTest.java
pom.xml

- Add integration/sofa-rpc module.
- Add auto active filter for sofa-rpc.
- Add the test case for this.
Fix #1042

Add sofa-rpc integration for context propagation.

---

server/pom.xml

bugfix:seata-server can's start in IDE.

---

common/src/main/java/io/seata/common/util/CollectionUtils.java
common/src/main/java/io/seata/common/util/StringUtils.java
common/src/test/java/io/seata/common/util/CollectionUtilsTest.java
common/src/test/java/io/seata/common/util/StringUtilsTest.java
rm-datasource/src/main/java/io/seata/rm/datasource/DataCompareUtils.java
rm-datasource/src/main/java/io/seata/rm/datasource/undo/AbstractUndoExecutor.java
rm-datasource/src/test/java/io/seata/rm/datasource/DataCompareUtilsTest.java

- Add DataCompareUtils
- Add some test case.
- Do not execute `undo` if the before data snapshot is equivalent to the after data snapshot.
Part of #1049

Break undo if data snapshot is not changed.

---

rm-datasource/src/main/java/io/seata/rm/datasource/AsyncWorker.java
rm-datasource/src/main/java/io/seata/rm/datasource/undo/UndoLogManager.java
rm-datasource/src/test/java/io/seata/rm/datasource/undo/UndoLogManagerTest.java

size wrong between xid and branchId which will delete fail
fix #1061

fix #1061 size wrong between xid and branchId

---

server/src/main/java/io/seata/server/Server.java
server/src/main/java/io/seata/server/coordinator/DefaultCoordinator.java
server/src/main/java/io/seata/server/lock/DefaultLockManagerImpl.java
server/src/main/java/io/seata/server/session/BranchSession.java
server/src/main/java/io/seata/server/store/FileTransactionStoreManager.java

This PR fix some typos and replace anonymous inner types with lambdas
no
did not change logics, just polishing
CI pass
no

Polish code: fix typos and replace AIT's with lambdas

---

config/seata-config-core/src/main/java/io/seata/config/ConfigurationFactory.java
discovery/seata-discovery-core/src/test/java/io/seata/config/ConfigurationFactoryTest.java

- Cache singleton configuration instance.
Fix #1077

Cache configuration instance.

---

common/src/main/java/io/seata/common/Constants.java
common/src/main/java/io/seata/common/loader/EnhancedServiceLoader.java
common/src/main/java/io/seata/common/util/BlobUtils.java
common/src/main/java/io/seata/common/util/StringUtils.java
common/src/test/java/io/seata/common/util/BlobUtilsTest.java
common/src/test/java/io/seata/common/util/StringUtilsTest.java
core/src/main/java/io/seata/core/protocol/AbstractMessage.java
rm-datasource/src/main/java/io/seata/rm/datasource/undo/UndoLogManager.java

- All use default `UTF-8` charset
- Remove `BlobUtils#inputStream2String()` which duplicate with StringUtils
- Delete `StringUtils#string2blob()` which duplicate with BlobUtils
- Add `BlobUtils#blob2Bytes()` and `BlobUtils#bytes2Blob()`
- Add more test case.

Refactor Charset using and blob utils.

---

.gitignore
all/pom.xml
server/src/main/resources/file.conf

Change points:
- Undo the pr #1033 
Set the createDependencyReducedPom to true.
The code of seata-* has all be packed into the seata-all.jar, and should not be inclueded in the seata-all.pom.
- Modify the all.xml
Change  the  configs of maven-javadoc-plugin in seata-all.xml

Undo pr 1033 and adjust the maven plugin of seata-all.xml

---

config/seata-config-core/src/main/resources/file.conf
core/src/main/java/io/seata/core/constants/ConfigurationKeys.java
rm-datasource/src/main/java/io/seata/rm/datasource/undo/AbstractUndoExecutor.java
rm-datasource/src/main/java/io/seata/rm/datasource/undo/UndoLogParserFactory.java
rm-datasource/src/main/resources/META-INF/services/io.seata.rm.datasource.undo.UndoLogParser
rm-datasource/src/test/java/io/seata/rm/datasource/undo/UndoLogParserFactoryTest.java
rm-datasource/src/test/java/io/seata/rm/datasource/undo/UndoLogParserProviderTest.java
server/src/main/resources/file.conf
server/src/main/resources/nacos-config.txt
test/src/test/resources/file.conf

- `UndoLogParser` change to SPI mode and make `fastjson` as default implement.
- Add config `transaction.undo.log.serialization`
- Fix one typo.
- Add test cases.
Fix #1010

UndoLogParser change to SPI.

---

core/src/main/java/io/seata/core/rpc/netty/MessageCodecHandler.java

Remove unnecessary copy of bytes.
resolve #1085

Remove unnecessary copy of bytes. resolve #1085

---

all/pom.xml
bom/pom.xml

Fix Maven configuration problems encountered when publishing the seata 0.6.0,
Change point:
- Add javadoc plugin for seata-all
- Add javadoc plugin for seata-bom
- Add url, licenses, developers, organization, issueManagement,scm for seata-bom

Fix maven configuration problems 

---

rm-datasource/src/main/java/io/seata/rm/datasource/DataCompareUtils.java

fix field type is datetime equals fail

---

rm-datasource/src/main/java/io/seata/rm/datasource/sql/struct/TableRecords.java
rm-datasource/src/main/java/io/seata/rm/datasource/undo/JSONBasedUndoLogParser.java
rm-datasource/src/main/java/io/seata/rm/datasource/undo/UndoLogManager.java
rm-datasource/src/test/java/io/seata/rm/datasource/undo/AbstractUndoExecutorTest.java
rm-datasource/src/test/java/io/seata/rm/datasource/undo/BaseExecutorTest.java
rm-datasource/src/test/java/io/seata/rm/datasource/undo/BaseH2Test.java
rm-datasource/src/test/java/io/seata/rm/datasource/undo/BaseUndoLogParserTest.java
rm-datasource/src/test/java/io/seata/rm/datasource/undo/BranchUndoLogTest.java
rm-datasource/src/test/java/io/seata/rm/datasource/undo/JSONBasedUndoLogParserTest.java

- change the method definition of UndoLogParser.
- String encode(BranchUndoLog branchUndoLog) -> byte[] encode(BranchUndoLog branchUndoLog)
- BranchUndoLog decode(String data) -> BranchUndoLog decode(byte[] bytes)
- Use `transient` instead of `@JSONField(serialize = false)` for ignore serialization of field `tableMeta`
- Refactor test case for more abstract.
Fix #1088

Change the method definition of UndoLogParser for better extensibility.

---

server/src/main/java/io/seata/server/coordinator/DefaultCoordinator.java
server/src/main/java/io/seata/server/coordinator/DefaultCore.java

fix #1118 
Use the xid wrong when do branch commit and rollback.

bugfix : use xid wrong when do branch commit and rollback

---

all/pom.xml
bom/pom.xml
integration/motan/pom.xml
integration/motan/src/main/java/io/seata/integration/motan/MotanTransactionFilter.java
integration/motan/src/main/resources/META-INF/services/com.weibo.api.motan.filter.Filter
integration/motan/src/test/java/io/seata/integration/motan/MotanTransactionFilterTest.java
integration/motan/src/test/java/io/seata/integration/motan/XIDService.java
integration/motan/src/test/java/io/seata/integration/motan/XIDServiceImpl.java
pom.xml

support weibo/motan

---

server/pom.xml

when the server is running in windows, the classpath is too long to failure start.
fix #1136

bugfix: seata-server.bat classpath too long

---

rm-datasource/src/main/java/io/seata/rm/datasource/DataSourceProxy.java

fix the data too long for column 'row_key' problem
fixes #1158

bugfix: AT mode resourceId(row_key) too long

---

core/src/main/java/io/seata/core/protocol/MergedWarpMessage.java

Due to the `java.nio.ByteBuffer` can not grow dynamically, its size is hardcoded now, this patch replaces `java.nio.ByteBuffer` with `io.netty.buffer.ByteBuf`, which can grow on demand.
fixes issue #976 
There is already tests upon this method.
CI passes
null

bugfix:the buffer may cause overflows when sql statement is long

---

core/src/main/java/io/seata/core/rpc/netty/RmRpcClient.java
core/src/main/java/io/seata/core/rpc/netty/TmRpcClient.java

reset initialized flag & instance when destroy RpcClient.
fix #983
unit test is included in another PR, for splitting #1105 into 2 PRs.

Reset initialized flag & instance while destroy(). split PR #1105

---

rm-datasource/src/main/java/io/seata/rm/datasource/undo/UndoLogManager.java

only add a missing placeholder in INSERT_UNDO_LOG_SQL
fixes https://github.com/seata/seata/issues/1164

add a missing placeholder in INSERT_UNDO_LOG_SQL

---

server/src/main/java/io/seata/server/session/GlobalSession.java

This patch replaces `ArrayList` with `HaseSet` to avoid duplicated listeners as described in #1126 , and also fix some typos
fixes #1126 
Already have
CI passes
null

bugfix: use Set to avoid duplicate listeners. fixes #1126

---

server/src/test/java/io/seata/server/coordinator/DefaultCoreTest.java
spring/src/main/java/io/seata/spring/tcc/TccActionInterceptor.java

Clear the transaction context in TCC prepare methed

---

pom.xml

check the third-party dependencies license
fix #1197

check the third-party dependencies license

---

rm-datasource/src/main/java/io/seata/rm/datasource/DataSourceManager.java

output branchRollback failed log

---

rm-datasource/src/main/java/io/seata/rm/datasource/ConnectionContext.java
spring/src/main/java/io/seata/spring/annotation/GlobalTransactionalInterceptor.java
spring/src/main/java/io/seata/spring/tcc/TccActionInterceptor.java
spring/src/main/java/io/seata/spring/util/SpringProxyUtils.java

setting default values using trinomial operators

---

core/src/main/java/io/seata/core/store/db/LockStoreDataBaseDAO.java

In LockStoreDataBaseDAO::doAcquireLock, The internal property ResultSet and related code are not necessary.

remove useless code

---

server/src/main/java/io/seata/server/session/SessionHolder.java

remove unused semicolons
fixes #540

remove unused semicolons

---

all/pom.xml
bom/pom.xml
config/seata-config-core/src/main/resources/file.conf
core/src/main/java/io/seata/core/protocol/Version.java
core/src/main/java/io/seata/core/rpc/netty/NettyServerConfig.java
pom.xml
server/src/main/java/io/seata/server/coordinator/DefaultCore.java
server/src/main/resources/file.conf
server/src/main/resources/nacos-config.txt
test/src/test/resources/file.conf

add config `shutdown.wait` and update version to 0.7.1-SNAPSHOT
fix #1212

add config `shutdown.wait` and update version to 0.7.0-SNAPSHOT

---

discovery/seata-discovery-eureka/src/main/java/io/seata/discovery/registry/eureka/EurekaRegistryServiceImpl.java

fixes https://github.com/seata/seata/issues/1160

fix bug of refresh cluster

---

rm-datasource/src/main/java/io/seata/rm/datasource/sql/struct/TableRecords.java

Fix Rm cannot find primary key when primary key is Uppercase in sql ,using MySQL.
fixes #1217

bugfix: fix in which SQL and database field names are inconsistent#1217

---

common/src/main/java/io/seata/common/util/CollectionUtils.java
common/src/test/java/io/seata/common/util/CollectionUtilsTest.java
rm-datasource/src/main/java/io/seata/rm/datasource/sql/struct/TableMeta.java

bugfix:containsPK ignoreCase
fix #1217 #1176

bugfix:containsPK ignoreCase

---

config/seata-config-core/src/main/java/io/seata/config/ConfigurationFactory.java

Currently "env" is used as the parameter name of environment isolation, but it is too general and may conflict with the parameter name of other components.
So,i modify the env to seataConfigEnv,so it will be like:
`-DseataConfigEnv=test`
fixes #1209
i have done the integration testing.
after this PR merged,i will update the wiki page.

optimize the name of seata config environment.

---

config/seata-config-core/src/main/java/io/seata/config/ConfigurationFactory.java
core/src/main/java/io/seata/core/rpc/netty/NettyClientChannelManager.java

fix a typo

---

common/src/test/java/io/seata/common/util/CompressUtilTest.java
common/src/test/java/io/seata/common/util/DurationUtilTest.java
common/src/test/java/io/seata/common/util/ReflectionUtilTest.java

I've analysed your codebase and noticed that `io.seata.common.util CompressUtil, DurationUtil, ReflectionUtil` is not fully tested.
I've written some tests for the methods in this class with the help of [Diffblue Cover](https://www.diffblue.com/opensource).
Hopefully, these tests will help you detect any regressions caused by future code changes. If you would find it useful to have additional tests written for this repository, I would be more than happy to look at other classes that you consider important.

Add unit tests for io.seata.common.util CompressUtil, DurationUtil, ReflectionUtil

---

config/seata-config-core/src/main/java/io/seata/config/ConfigurationFactory.java
spring/src/main/java/io/seata/spring/annotation/GlobalTransactionScanner.java

prioritize global transaction scanner
fix #1227
ensure order of bean initialization by BeanFactoryPostProcessor & PriorityOrdered is already verified.
Bean annotated with TwoPhaseBusinessAction is a part of a TCC transaction.

prioritize global transaction scanner #1227

---

discovery/seata-discovery-zk/src/main/java/io/seata/discovery/registry/zk/ZookeeperRegisterServiceImpl.java

fix ConcurrentModificationException in Zookeeper discovery implementation.
Here, while traversing iZkChildListeners, new listener may be added, so CopyOnWriteArraylist must be used here to avoid CME.
fixex #1234

bugfix:fix CME in ZK discovery implementation.

---

codecov.yml

fix codecov for protobuf

---

core/src/main/java/io/seata/core/constants/ConfigurationKeys.java
server/src/main/java/io/seata/server/metrics/MetricsManager.java
server/src/main/resources/file.conf
server/src/test/resources/file.conf

Signed-off-by: zhengyangyong <yangyong.zheng@qq.com>
add a new configuration `enabled` for metrics:
```
metrics {
enabled = true                                          <-------- new
registry-type = "compact"
exporter-list = "prometheus"
exporter-prometheus-port = 9898
}
```

add enabled configuration for metrics

---

.gitignore
codecov.yml

configuration:update ignore and coverage

configuration:update ignore and coverage

---

rm-datasource/src/main/java/io/seata/rm/datasource/ConnectionContext.java

bugfix: @GlobalLock get error with Response

---

rm-datasource/src/main/java/io/seata/rm/datasource/exec/BaseTransactionalExecutor.java
rm-datasource/src/main/java/io/seata/rm/datasource/exec/DeleteExecutor.java
rm-datasource/src/main/java/io/seata/rm/datasource/exec/InsertExecutor.java
rm-datasource/src/main/java/io/seata/rm/datasource/exec/UpdateExecutor.java

1. optimization SQL join

---

rm-datasource/src/main/java/io/seata/rm/datasource/exec/InsertExecutor.java
rm-datasource/src/test/java/io/seata/rm/datasource/exec/InsertExecutorTest.java

修复issue 1259，在插入数据时，如果未显式指定PreparedStatement返回自动生成的key 使用Select last_insert_id()代替时，打印warn日志，提醒用户Statement状态可能被污染的风险。
fixes #1259
有测试用例，是InsertExecutorTest#testGetPkValuesByAuto_SQLException_WarnLog
通过测试用例验证，或者 issue 1259 中的复现case验证

add warn log when fail to get auto-generated keys. (#1259)

---

server/src/main/java/io/seata/server/coordinator/DefaultCore.java

bugfix: DefaultFailureHandler check status NPE, cause trx finished
fix #1312

bugfix: DefaultFailureHandler check status NPE, cause trx finished

---

core/src/main/java/io/seata/core/constants/ConfigurationKeys.java
core/src/main/java/io/seata/core/store/db/AbstractDataSourceGenerator.java
server/src/main/java/io/seata/server/store/db/DbcpDataSourceGenerator.java
server/src/main/java/io/seata/server/store/db/DruidDataSourceGenerator.java
server/src/main/resources/db_undo_log.sql
server/src/main/resources/file.conf

add a sql file when the first time  to use seata . it is init to sql database  and add database driver class name  of config

add undo_log.sql   and add database driver class config

---

codec/seata-codec-protobuf/src/main/java/io/seata/codec/protobuf/convertor/BranchRegisterRequestConvertor.java
codec/seata-codec-protobuf/src/main/java/io/seata/codec/protobuf/convertor/GlobalLockQueryRequestConvertor.java

tcc will not set lock key, when users use protobuf as serialize type, the setLockKey will fail.

bugfix: fix lock key npe bug, when tcc use protobuf

---

core/src/main/java/io/seata/core/store/db/LockStoreDataBaseDAO.java

bugfix: Lock is not acquired when multiple branches have cross locks#1247

---

bom/pom.xml
core/src/main/java/io/seata/core/rpc/netty/v1/ProtocolV1Decoder.java

bugfix: netty memory leak

---

config/seata-config-consul/src/main/java/io/seata/config/consul/ConsulConfiguration.java
config/seata-config-etcd3/src/main/java/io/seata/config/etcd3/EtcdConfiguration.java
discovery/seata-discovery-consul/src/main/java/io/seata/discovery/registry/consul/ConsulRegistryServiceImpl.java
discovery/seata-discovery-etcd3/src/main/java/io/seata/discovery/registry/etcd3/EtcdRegistryServiceImpl.java

Code Cleaning of Consul&Etcd implementations.
Nil.

Code Cleaning of Consul&Etcd implementations.

---

discovery/seata-discovery-eureka/src/main/java/io/seata/discovery/registry/eureka/EurekaRegistryServiceImpl.java

1. Fixed issue where clusterAddressMap did not remove this instance after the instance was offline.
2. remove EurekaRegistryException, because EurekaRegistryException is RuntimeException.
3. add log.

Fixed issue where clusterAddressMap did not remove this instance after the instance was offline

---

server/src/main/java/io/seata/server/coordinator/DefaultCoordinator.java

bugfix: get SessionManager error when rollback retry timeout

---

rm-datasource/src/main/java/io/seata/rm/datasource/sql/SQLVisitorFactory.java

add Oracle prompt code to the else code block

---

rm-datasource/src/main/java/io/seata/rm/datasource/AbstractConnectionProxy.java

support preparedStatement  batch self-increment(need jdbc2+)

---

server/src/main/resources/registry.conf
test/src/test/resources/registry.conf

modify eureka registry serviceUrl with default port
eureka default port is 8761.

modify eureka registry serviceUrl with default port

---

core/src/main/java/io/seata/core/rpc/netty/NettyClientChannelManager.java

`                if (null == rmChannel || rmChannel.isActive()) {
return rmChannel;
}`
Our goal is to get a active rmChannel,So when null == rmChannel ,we can not return,Otherwise it will be called in a loop.
I dont know.
review maybe

bugfix: check null channel

---

core/src/main/java/io/seata/core/exception/TransactionExceptionCode.java
core/src/main/java/io/seata/core/rpc/netty/AbstractRpcRemotingClient.java
tm/src/main/java/io/seata/tm/DefaultTransactionManager.java

bugfix: begin failed not release channel and throw exception
fix #1349

bugfix: begin failed not release channel and throw exception

---

config/seata-config-apollo/src/main/java/io/seata/config/apollo/ApolloConfiguration.java
config/seata-config-consul/src/main/java/io/seata/config/consul/ConsulConfiguration.java
config/seata-config-core/src/main/java/io/seata/config/Configuration.java
config/seata-config-core/src/main/java/io/seata/config/FileConfiguration.java
config/seata-config-etcd3/src/main/java/io/seata/config/etcd3/EtcdConfiguration.java
config/seata-config-nacos/src/main/java/io/seata/config/nacos/NacosConfiguration.java
config/seata-config-zk/src/main/java/io/seata/config/zk/ZookeeperConfiguration.java

support -Dkey=value parameter
startup parameter > -D parameter > configCenter parameter > default value
fix #1377

support -Dkey=value SysConfig

---

server/src/test/java/io/seata/server/coordinator/DefaultCoordinatorMetricsTest.java

disable unstable unit tests

---

core/src/main/java/io/seata/core/model/BranchStatus.java
server/src/main/java/io/seata/server/coordinator/DefaultCore.java

Optimize BranchStatus.java annotation,the annotation is very messy.

Optimize:optimize BranchStatus annotation

---

rm-datasource/src/main/java/io/seata/rm/RMHandlerAT.java

bugfix: if the connection is autocommit=false will cause fail to delete
fix #1420

bugfix: if the connection is autocommit=false will cause fail to delete

---

common/src/main/java/io/seata/common/util/StringUtils.java

StringUtils.toString() method output error when instance of map

bugfix:map.toString error

---

core/src/main/java/io/seata/core/codec/Codec.java
core/src/main/java/io/seata/core/codec/CodecFactory.java
core/src/main/java/io/seata/core/constants/DBType.java
core/src/main/java/io/seata/core/lock/AbstractLocker.java
core/src/main/java/io/seata/core/lock/LocalDBLocker.java
core/src/main/java/io/seata/core/lock/LockMode.java
core/src/main/java/io/seata/core/lock/Locker.java
core/src/main/java/io/seata/core/lock/RowLock.java
core/src/main/java/io/seata/core/protocol/MessageType.java
core/src/main/java/io/seata/core/store/BranchTransactionDO.java
core/src/main/java/io/seata/core/store/GlobalTransactionDO.java
core/src/main/java/io/seata/core/store/LockDO.java
core/src/main/java/io/seata/core/store/LogStore.java
core/src/main/java/io/seata/core/store/StoreMode.java
core/src/main/java/io/seata/core/store/db/AbstractDataSourceGenerator.java
core/src/main/java/io/seata/core/store/db/DataSourceGenerator.java
core/src/main/java/io/seata/core/store/db/LockStoreDataBaseDAO.java
core/src/main/java/io/seata/core/store/db/LockStoreSqls.java
core/src/main/java/io/seata/core/store/db/LogStoreDataBaseDAO.java
core/src/main/java/io/seata/core/store/db/LogStoreSqls.java
core/src/test/java/io/seata/core/store/db/DataBaseLockStoreDAOTest.java
core/src/test/java/io/seata/core/store/db/LogStoreDataBaseDAOTest.java

Some adjustments on the comments.
No.
That is not necessary.
em.....
Nothing.

fix some javadoc comments

---

rm-datasource/src/main/java/io/seata/rm/datasource/exec/BaseTransactionalExecutor.java
rm-datasource/src/main/java/io/seata/rm/datasource/exec/DeleteExecutor.java
rm-datasource/src/main/java/io/seata/rm/datasource/exec/InsertExecutor.java
rm-datasource/src/main/java/io/seata/rm/datasource/exec/SelectForUpdateExecutor.java
rm-datasource/src/main/java/io/seata/rm/datasource/exec/UpdateExecutor.java
rm-datasource/src/main/java/io/seata/rm/datasource/sql/WhereRecognizer.java
rm-datasource/src/main/java/io/seata/rm/datasource/sql/druid/BaseRecognizer.java
rm-datasource/src/main/java/io/seata/rm/datasource/sql/druid/MySQLDeleteRecognizer.java
rm-datasource/src/main/java/io/seata/rm/datasource/sql/druid/MySQLSelectForUpdateRecognizer.java
rm-datasource/src/main/java/io/seata/rm/datasource/sql/druid/MySQLUpdateRecognizer.java
rm-datasource/src/main/java/io/seata/rm/datasource/sql/druid/oracle/OracleDeleteRecognizer.java
rm-datasource/src/main/java/io/seata/rm/datasource/sql/druid/oracle/OracleSelectForUpdateRecognizer.java
rm-datasource/src/main/java/io/seata/rm/datasource/sql/druid/oracle/OracleUpdateRecognizer.java
rm-datasource/src/test/java/io/seata/rm/datasource/exec/InsertExecutorTest.java
rm-datasource/src/test/java/io/seata/rm/datasource/sql/druid/MySQLDeleteRecognizerTest.java
rm-datasource/src/test/java/io/seata/rm/datasource/sql/druid/MySQLSelectForUpdateRecognizerTest.java
rm-datasource/src/test/java/io/seata/rm/datasource/sql/druid/MySQLUpdateRecognizerTest.java

refactor: executor class duplicate code

---

core/src/main/java/io/seata/core/model/Result.java
rm-datasource/src/main/java/io/seata/rm/datasource/DataCompareUtils.java
rm-datasource/src/main/java/io/seata/rm/datasource/undo/AbstractUndoExecutor.java
rm-datasource/src/test/java/io/seata/rm/datasource/DataCompareUtilsTest.java
rm-datasource/src/test/java/io/seata/rm/datasource/undo/BaseUndoLogParserTest.java
rm-datasource/src/test/java/io/seata/rm/datasource/undo/parser/JacksonUndoLogParserTest.java

optimize: data image compare log

---

config/seata-config-consul/src/main/java/io/seata/config/consul/ConsulConfiguration.java
config/seata-config-core/src/main/java/io/seata/config/AbstractConfiguration.java
config/seata-config-core/src/main/java/io/seata/config/ConfigFuture.java
config/seata-config-nacos/src/main/java/io/seata/config/nacos/NacosConfiguration.java
config/seata-config-zk/src/main/java/io/seata/config/zk/ZookeeperConfiguration.java

refactor: remove unnecessary code

refactor: remove unnecessary code

---

common/src/main/java/io/seata/common/loader/EnhancedServiceLoader.java

bugfix: EnhancedServiceLoader may be appears load class error

---

test/src/test/java/io/seata/core/rpc/netty/v1/ProtocolV1CodecTest.java

bugfix: ProtocolV1CodecTest testAll may be appears test not pass

---

rm-datasource/src/main/java/io/seata/rm/datasource/sql/struct/TableMetaCache.java
rm-datasource/src/main/java/io/seata/rm/datasource/sql/struct/TableMetaCacheOracle.java
rm-datasource/src/test/java/io/seata/rm/datasource/sql/struct/TableMetaTest.java

git some tips when no index in the table cause NPE in TableMetaCache.java.
#1529

optimize: throw Exception when no index in the table

---

server/src/main/resources/nacos-config.txt

bugfix: nacos-config.txt miss store.db.driver-class-name property

---

config/seata-config-nacos/src/main/java/io/seata/config/nacos/NacosConfiguration.java

bugfix: nacos namespace setting does not take effect 
fix #1536

bugfix: nacos namespace setting does not take effect

---

config/seata-config-core/src/main/java/io/seata/config/ConfigurationFactory.java

For the current logics of loading different configuration,it's a bit complicated to understand.So,i'm gonna improve it,and make it clearly.So,the new logics will be like:
At first,will try to read the name from JVM parameters(when use -Dxxx=xx),if reads nothing,will try to read the name from system environment,if reads nothing again,then will ues default configuration:file.conf,registry.conf.
For example,if we have a testing environment called "test",then these conf files should be in the following format:
`
file-test.conf
registry-test.conf
`
fixes #1532

Refactor of the logics of Multi-configuration Isolation

---

config/seata-config-zk/src/main/java/io/seata/config/zk/ZookeeperConfiguration.java

code cleanup 

---

core/src/main/java/io/seata/core/rpc/netty/AbstractRpcRemotingServer.java
server/src/main/java/io/seata/server/ParameterParser.java
server/src/main/java/io/seata/server/Server.java

bugfix:binding public network address listen failed.
sh seata-server.sh -h $PUBLIC_ADDRESS_IP  -p 8091 -m file
fix #1504

bugfix: binding public network address listen failed

---

rm-datasource/src/main/java/io/seata/rm/datasource/sql/struct/TableRecords.java
rm-datasource/src/main/java/io/seata/rm/datasource/undo/parser/JacksonUndoLogParser.java

optimize TableRecords delete jackson annotation

optimize: TableRecords delete jackson annotation

---

core/src/main/java/io/seata/core/rpc/netty/RpcServer.java

bugfix: throw NPE when the rpcMessage's body is null (#1556)

---

server/src/main/java/io/seata/server/coordinator/DefaultCoordinator.java

optimize delay to delete the expired undo log
fixes #1464

optimize: delay to delete the expired undo log

---

server/src/main/java/io/seata/server/session/BranchSession.java

fix BranchSession.calBranchSessionSize return missing xidBytes.length.
fixes 1549
https://github.com/seata/seata/issues/1549#issue-486287065

bugfix: calculate BranchSession size missing xidBytes.length

---

codec/seata-codec-seata/src/test/resources/registry.conf
config/seata-config-core/src/main/resources/registry.conf
config/seata-config-nacos/src/main/java/io/seata/config/nacos/NacosConfiguration.java
discovery/seata-discovery-nacos/src/main/java/io/seata/discovery/registry/nacos/NacosRegistryServiceImpl.java
rm-datasource/src/main/java/io/seata/rm/datasource/sql/struct/TableMetaCacheOracle.java
server/src/main/resources/registry.conf
test/src/test/resources/registry.conf

bugfix: modify default namespace
fix #1592

bugfix: modify default namespace

---

core/src/test/java/io/seata/core/message/RegisterTMRequestTest.java
core/src/test/java/io/seata/core/message/RegisterTMResponseTest.java

add testcase for RegisterTMReques
no
add a unit test case
The type Register tm request test. test tostring

Test: add UT for RegisterTMRequest

---

server/src/main/java/io/seata/server/session/GlobalSession.java
server/src/main/java/io/seata/server/store/db/DatabaseTransactionStoreManager.java
server/src/main/java/io/seata/server/store/file/FileTransactionStoreManager.java

fix missing length in GlobalSession and FileTransactionStoreManager
No.
No need.
By logical
BUG

bugfix: missing some length in GlobalSession and FileTransactionStoreManager

---

rm-datasource/src/main/java/io/seata/rm/datasource/sql/struct/TableMetaCacheOracle.java

optimize oracle index:
1. "PRIMARY" is used for mysql primary indexName but not for oracle
2. get primary index should always used the columnName，avoid to different oracle version index  offset changed

optimize: get oracle primary index

---

rm-datasource/src/main/java/io/seata/rm/datasource/sql/struct/TableMetaCache.java
rm-datasource/src/main/java/io/seata/rm/datasource/sql/struct/TableMetaCacheOracle.java

Use seata's StringUtils, instead of druid's.
fix #1606

bugfix: solve NoSuchMethodError when the version of druid used < 1.1.3

---

rm-datasource/src/main/java/io/seata/rm/datasource/undo/mysql/keyword/MySQLKeywordChecker.java

> Performing additional initialization on an object after assignment to a shared variable guarded by double-checked locking is not thread-safe, and could result in unexpected behavior.
Potential race condition: this instance of `keywordChecker` is available to other threads before `keywordSet` are assign, which may causes NPE if other threads call '#check' method.
Below is code segment (the code comment is added by me):
```java
private static volatile KeywordChecker keywordChecker = null;
private static volatile Set<String> keywordSet = null;
public static KeywordChecker getInstance() {
if (keywordChecker == null) {
synchronized (MySQLKeywordChecker.class) {
if (keywordChecker == null) {
keywordChecker = new MySQLKeywordChecker();
// additional initialization inside double-checked locking …
```

bugfix: thread unsafe issue of MySQLKeywordChecker initialization

---

rm-datasource/src/main/java/io/seata/rm/datasource/undo/oracle/keyword/OracleKeywordChecker.java

Thanks @chenxi-null push a pr to fix #1599 , and I found same problem in oracle keyword checker. so, I fix it base on you solution.

bugfix: thread unsafe of oracle keyword checker

---

server/src/main/java/io/seata/server/store/file/FileTransactionStoreManager.java

fix BufferOverflowException when FileTransactionStoreManager write a big BranchSession(size > 16KB).
fixes #1551
https://github.com/seata/seata/issues/1551#issue-486308391
```
public class FileTransactionStoreManagerTest {
FileTransactionStoreManager fileTransactionStoreManager;
@BeforeEach
public void beforeAll() throws IOException {
fileTransactionStoreManager = new FileTransactionStoreManager("~/my/tmp/test/seata", null);
}
@Test
public void writeBigBytes() {
BranchSession branchSession = new BranchSession();
branchSession.setApplicationData(createBigStr(1024 * 16 - 36));
fileTransactionStoreManager.writeSession(TransactionStoreManager.LogOperation.BRANCH_ADD, branchSession);
}
public String createBigStr(int size){
byte[] bytes = new byte[size];
for (int i = 0; i < size; i++) { …
```

bugfix: BufferOverflow when BranchSession size too large

---

core/src/main/java/io/seata/core/constants/ConfigurationKeys.java
rm-datasource/src/main/java/io/seata/rm/datasource/ConnectionProxy.java
rm-datasource/src/main/java/io/seata/rm/datasource/exec/AbstractDMLBaseExecutor.java
rm-datasource/src/test/java/io/seata/rm/datasource/ConnectionProxyTest.java
rm-datasource/src/test/java/io/seata/rm/datasource/exec/AbstractDMLBaseExecutorTest.java
server/src/main/resources/nacos-config.txt

Move lock retry loop into ConnectionProxy.commit, that the number of LockKeyConflict can be significantly reduced whether auto-commit is true or false. Related issue #1438.

optimize: reduce the number of lock conflict exception

---

rm-datasource/src/main/java/io/seata/rm/RMHandlerAT.java
rm-datasource/src/main/java/io/seata/rm/datasource/AsyncWorker.java
rm-datasource/src/main/java/io/seata/rm/datasource/ConnectionProxy.java
rm-datasource/src/main/java/io/seata/rm/datasource/DataCompareUtils.java
rm-datasource/src/main/java/io/seata/rm/datasource/DataSourceManager.java
rm-datasource/src/main/java/io/seata/rm/datasource/undo/AbstractUndoLogManager.java
rm-datasource/src/main/java/io/seata/rm/datasource/undo/UndoLogManager.java
rm-datasource/src/main/java/io/seata/rm/datasource/undo/UndoLogManagerFactory.java
rm-datasource/src/main/java/io/seata/rm/datasource/undo/mysql/MySQLUndoLogManager.java
rm-datasource/src/main/java/io/seata/rm/datasource/undo/oracle/OracleUndoLogManager.java
rm-datasource/src/test/java/io/seata/rm/datasource/undo/UndoLogManagerTest.java

optimize undo log manager and fix delete undolog support oracle
fixes #1596

optimize undolog manager and fix delete undolog support oracle

---

core/src/main/java/io/seata/core/rpc/DefaultServerMessageListenerImpl.java
core/src/main/java/io/seata/core/rpc/netty/AbstractRpcRemoting.java
core/src/main/java/io/seata/core/rpc/netty/AbstractRpcRemotingClient.java
core/src/main/java/io/seata/core/rpc/netty/RmMessageListener.java
core/src/main/java/io/seata/core/rpc/netty/RmRpcClient.java

There are several places that are not correct for the use of Slf4j.
They log error log like this:
```
LOGGER.error("", "send response error", throwable);
```
It will print log like below, missing the log message:
```
[main] ERROR TmpTest -
java.lang.RuntimeException: xx
at TmpTest.<init>(TmpTest.java:28)
...... ignore exception stack ......
```
I correct it like this:
```
LOGGER.error("send response error", throwable);
```
So, it will print the expected log content:
```
[main] ERROR TmpTest - send response error
java.lang.RuntimeException: xx
at TmpTest.<init>(TmpTest.java:28)
...... ignore exception stack ......
```

optimize: fix wrong usage of Slf4j

---

core/src/main/java/io/seata/core/store/db/LockStoreDataBaseDAO.java
rm-datasource/src/main/java/io/seata/rm/datasource/undo/mysql/MySQLUndoLogManager.java
rm-datasource/src/main/java/io/seata/rm/datasource/undo/oracle/OracleUndoLogManager.java

https://github.com/seata/seata-samples/issues/226
After the connection is used, restore the commit status of the initial connection.

bugfix: restore autocommit

---

rm-datasource/src/main/java/io/seata/rm/datasource/sql/struct/TableMetaCache.java

Fix get table meta fail when table name was keyword
#1662

bugfix: get table meta fail when table name was keyword

---

server/src/main/java/io/seata/server/lock/DefaultLockManager.java
server/src/main/java/io/seata/server/lock/LockerFactory.java

file mode rm selectForUpdate lockQuery exception
fixes #1586

bugfix: selectForUpdate lockQuery exception in file mode

---

discovery/seata-discovery-etcd3/src/main/java/io/seata/discovery/registry/etcd3/EtcdRegistryServiceImpl.java

Fix etcd registry service's server address list change events leak.
#1623 
No new api.
1. get newest server address list then start debug break point
2. change server address list
3. cancel break point, then add change listener
4. receive change event，refresh address list

bugfix: address list change events leak

---

codec/seata-codec-kryo/pom.xml
codec/seata-codec-protobuf/pom.xml

bugfix: revision -> project version
cause the variable name to not be replaced in pom.xml when released.

bugfix: revision -> project version

---

all/pom.xml
config/pom.xml
config/seata-config-core/src/main/java/io/seata/config/ConfigType.java
config/seata-config-custom/pom.xml
config/seata-config-custom/src/main/java/io/seata/config/custom/CustomConfigurationProvider.java
config/seata-config-custom/src/main/resources/META-INF/services/io.seata.config.ConfigurationProvider
config/seata-config-custom/src/test/java/io/seata/config/CustomConfigurationForTest.java
config/seata-config-custom/src/test/java/io/seata/config/CustomConfigurationProviderForTest.java
config/seata-config-custom/src/test/java/io/seata/config/CustomConfigurationTest.java
config/seata-config-custom/src/test/resources/META-INF/services/io.seata.config.ConfigurationProvider
config/seata-config-custom/src/test/resources/custom_for_test.properties
config/seata-config-custom/src/test/resources/registry.conf
discovery/seata-discovery-all/pom.xml
discovery/seata-discovery-core/src/main/java/io/seata/discovery/registry/RegistryFactory.java
discovery/seata-discovery-core/src/main/java/io/seata/discovery/registry/RegistryType.java
discovery/seata-discovery-custom/pom.xml
discovery/seata-discovery-custom/src/main/java/io/seata/discovery/registry/custom/CustomRegistryProvider.java
discovery/seata-discovery-custom/src/main/resources/META-INF/services/io.seata.discovery.registry.RegistryProvider
discovery/seata-discovery-custom/src/test/java/io/seata/discovery/registry/custom/CustomRegistryProviderForTest.java
discovery/seata-discovery-custom/src/test/java/io/seata/discovery/registry/custom/CustomRegistryServiceForTest.java
discovery/seata-discovery-custom/src/test/java/io/seata/discovery/registry/custom/CustomRegistryTest.java
discovery/seata-discovery-custom/src/test/resources/META-INF/services/io.seata.discovery.registry.RegistryProvider
discovery/seata-discovery-custom/src/test/resources/registry.conf

Add custom config and registry type, which can be used to help users create their own configuration loading mechanism. Mainly used in client side.

feature: support custom config and registry type

---

discovery/seata-discovery-core/src/main/java/io/seata/discovery/registry/RegistryFactory.java
rm-datasource/src/main/java/io/seata/rm/datasource/AbstractPreparedStatementProxy.java
rm-datasource/src/main/java/io/seata/rm/datasource/AbstractStatementProxy.java
rm-datasource/src/main/java/io/seata/rm/datasource/AsyncWorker.java
rm-datasource/src/main/java/io/seata/rm/datasource/ConnectionProxy.java
rm-datasource/src/main/java/io/seata/rm/datasource/sql/druid/MySQLDeleteRecognizer.java
rm-datasource/src/main/java/io/seata/rm/datasource/sql/druid/MySQLSelectForUpdateRecognizer.java
rm-datasource/src/test/java/io/seata/rm/datasource/mock/MockExecuteHandlerImpl.java
rm-datasource/src/test/java/io/seata/rm/datasource/mock/MockResultSet.java
server/src/test/java/io/seata/server/coordinator/DefaultCoordinatorMetricsTest.java

optimize: remove unused imports

---

common/src/main/java/io/seata/common/exception/DataAccessException.java
core/src/main/java/io/seata/core/exception/TransactionExceptionCode.java
core/src/main/java/io/seata/core/store/db/LockStoreDataBaseDAO.java
core/src/main/java/io/seata/core/store/db/LogStoreDataBaseDAO.java
server/src/main/java/io/seata/server/AbstractTCInboundHandler.java
server/src/main/java/io/seata/server/lock/db/DataBaseLocker.java
server/src/main/resources/db_store.sql

pk too long in lock table on db mode and optimize error log.
fixes #1679

bugfix:pk too long in lock table on db mode and optimize error log.

---

config/seata-config-core/src/main/java/io/seata/config/ConfigurationFactory.java
core/src/main/java/io/seata/core/rpc/netty/AbstractRpcRemotingServer.java
server/src/main/java/io/seata/server/ParameterParser.java
server/src/main/java/io/seata/server/Server.java
server/src/test/java/io/seata/server/ParameterParserTest.java

As described in issue #1683,So i added a new parameter option "-e" to fix it.
And this is only available on the server side,for the client side,you can still use JVM parameter to set
the name of multi-configuration isolation directly.
```
Usage: sh seata-server.sh(for linux and mac) or cmd seata-server.bat(for 
windows) [options]
Options:
--host, -h
The ip to register to registry center.
--port, -p
The port to listen.
Default: 8091
--storeMode, -m
log store mode : file、db
--serverNode, -n
server node id, such as 1, 2, 3. default is 1
Default: 1
--seataEnv, -e
The name used for multi-configuration isolation.
--help
```
fixes #1683 
UT provided,i've tested it.
After this PR merged,i will update wiki as well.

feature:support new parameter option "-e" used for setting name of configuration.

---

server/src/test/java/io/seata/server/lock/LockManagerTest.java

bugfix: correct LockManagerTest.concurrentUseAbilityTest assertion condition

---

core/src/main/java/io/seata/core/rpc/ChannelManager.java
core/src/main/java/io/seata/core/rpc/DefaultServerMessageListenerImpl.java
core/src/main/java/io/seata/core/rpc/netty/NettyClientChannelManager.java
core/src/main/java/io/seata/core/rpc/netty/RpcClientHandler.java

This PR is just replace the parameters from string concatenation to message formatting
LOGGER.error("rpcContext is null,channel:" + channel + ",active:" + channel.isActive());
change to:
LOGGER.error("rpcContext is null,channel:{},active:{}", channel, channel.isActive());
no
It could be verified by code review
code review and the actual logs

optimize:formating log messages

---

codec/seata-codec-kryo/src/main/java/io/seata/codec/kryo/KryoCodec.java
rm-datasource/src/main/java/io/seata/rm/datasource/DataSourceProxy.java

Simplify to make codes more readable.
Ⅱ. Does this pull request fix one issue?
No.
Ⅲ. Why don't you add test cases (unit test/integration test)?
Ⅳ. Describe how to verify it
Ⅴ. Special notes for reviews

optimize: simplify to make codes more readable

---

rm-datasource/src/main/java/io/seata/rm/datasource/AbstractConnectionProxy.java
rm-datasource/src/main/java/io/seata/rm/datasource/exec/BaseTransactionalExecutor.java
rm-datasource/src/main/java/io/seata/rm/datasource/exec/InsertExecutor.java
rm-datasource/src/test/java/io/seata/rm/datasource/exec/InsertExecutorTest.java
rm-datasource/src/test/java/io/seata/rm/datasource/exec/OracleInsertExecutorTest.java

oracle batch insert error
fixes #1709

bugfix: oracle batch insert error

---

server/src/main/java/io/seata/server/store/file/FileTransactionStoreManager.java
server/src/test/java/io/seata/server/store/file/FileTransactionStoreManagerTest.java

In FileTransactionStoreManager, sometimes, data buffer size was not under control. For example when data size to write was bigger than writerBuffer:
```
...
ByteBuffer byteBuffer = null;
if (bs.length + 4 > MAX_WRITE_BUFFER_SIZE) {
//allocateNew
byteBuffer = ByteBuffer.allocateDirect(bs.length + 4);
} else {
...
```
Or in function findTimeoutAndSave:
```
...
ByteBuffer byteBuffer = ByteBuffer.allocateDirect(totalSize);
for (byte[] bytes : listBytes) {
byteBuffer.putInt(bytes.length);
byteBuffer.put(bytes);
}
...
```
Those buffers' size was out of control, unlimited, that may be a hidden danger. 
This PR makes fully use of the writerBuffer, eliminate the possibility of allocating too much memory.
Did.

optimize: eliminate the possibility of allocating too much direct memory

---

server/src/main/java/io/seata/server/lock/memory/MemoryLocker.java
server/src/main/java/io/seata/server/session/BranchSession.java
server/src/test/java/io/seata/server/lock/LockManagerTest.java

fix memory lock is not released
#1744
UT in LockManagerTest.java
Run UT in LockManagerTest.java

bugfix:fix memory lock is not released due to hash conflict

---

bom/pom.xml

This PR upgraded jackson version to 2.9.9 to avoid [CVE-2019-12086]( https://nvd.nist.gov/vuln/detail/CVE-2019-12086).
Jackson ReleaseNote: [https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.9.9](https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.9.9#databind).
Jackson Patch: databind/issue/2326.
Do we need to upgrade to latest version?

security: upgrade jackson to avoid security vulnerabilities

---

rm-datasource/src/main/java/io/seata/rm/datasource/undo/AbstractUndoExecutor.java

fix oracle rollback failed when the table that include null value in the Clob and Blob column
#1762

bugfix: oracle rollback failed when the table has null Blob Clob value

---

rm-datasource/src/main/java/io/seata/rm/datasource/exec/DeleteExecutor.java

keyword checker not distinguish db type
fixes #1754

bugfix: DeleteExecutor. buildBeforeImageSQL keyword checker by db type

---

metrics/seata-metrics-core/src/main/java/io/seata/metrics/exporter/ExporterFactory.java
saga/seata-saga-engine-store/src/main/java/io/seata/saga/engine/config/DbStateMachineConfig.java
saga/seata-saga-engine-store/src/main/java/io/seata/saga/engine/serializer/impl/ExceptionSerializer.java
saga/seata-saga-engine-store/src/main/java/io/seata/saga/engine/store/db/DbAndReportTcStateLogStore.java
saga/seata-saga-engine/src/main/java/io/seata/saga/engine/pcext/handlers/SubStateMachineHandler.java
saga/seata-saga-engine/src/main/java/io/seata/saga/engine/pcext/interceptors/ServiceTaskHandlerInterceptor.java
saga/seata-saga-processctrl/src/main/java/io/seata/saga/proctrl/handler/DefaultRouterHandler.java
saga/seata-saga-processctrl/src/main/java/io/seata/saga/proctrl/impl/ProcessControllerImpl.java
saga/seata-saga-processctrl/src/main/java/io/seata/saga/proctrl/process/impl/CustomizeBusinessProcessor.java
saga/seata-saga-tm/src/main/java/io/seata/saga/tm/DefaultSagaTransactionalTemplate.java
server/src/main/java/io/seata/server/coordinator/DefaultCore.java
server/src/main/java/io/seata/server/lock/DefaultLockManager.java
server/src/main/java/io/seata/server/lock/db/DataBaseLocker.java
server/src/main/java/io/seata/server/store/file/FileTransactionStoreManager.java
tm/src/main/java/io/seata/tm/api/TransactionalTemplate.java

optimize:LOGGER.error()，Use placeholders to avoid string concatenation

optimize: format error log

---

.gitignore
server/pom.xml

Remove deprecated JVM arguments in Java 11
#1819 
There is no test for server script
1. Change JRE to 8, startup server in Mac/Linux/Win
2. Change JRE to 11, startup server in Mac/Linux/Win
All environment should be startup normally.
Need to make sure removed argument is not affect performance of server

Remove deprecated JVM arguments in Java 11

---

codec/seata-codec-protobuf/src/main/resources/protobuf/io/seata/protocol/transcation/transactionExceptionCode.proto
common/src/main/java/io/seata/common/util/LambdaUtils.java
core/src/main/java/io/seata/core/store/db/LockStoreDataBaseDAO.java
server/src/main/resources/file.conf

fixes #1833 
1.use @Transcation
2.batch write such as insert id (123),(124),(125)
3.update 123

bugfix: filter repeated lock

---

discovery/seata-discovery-nacos/src/main/java/io/seata/discovery/registry/nacos/NacosRegistryServiceImpl.java

bugfix: multi-thread concurrent add listener problem
fix #1830

bugfix: multi-thread concurrent add listener problem

---

spring/src/main/java/io/seata/spring/annotation/GlobalTransactionScanner.java

bugfix:fix Global transaction does not work

---

common/src/main/java/io/seata/common/util/LambdaUtils.java
rm-datasource/src/main/java/io/seata/rm/datasource/sql/struct/TableMeta.java
rm-datasource/src/test/java/io/seata/rm/datasource/sql/struct/TableMetaTest.java

optimize: optimize no primary key output log
fix #1860 #1854

optimize: optimize no primary key output log

---

core/src/main/java/io/seata/core/store/db/LockStoreDataBaseDAO.java
core/src/main/java/io/seata/core/store/db/LogStoreDataBaseDAO.java
server/src/main/java/io/seata/server/coordinator/DefaultCoordinator.java
server/src/main/java/io/seata/server/coordinator/DefaultCore.java

bugfix: when branchCommit failed,it will trigger retry of multi-tc and throw npe
fix #1841

bugfix: when branchCommit failed,it will trigger retry of multi-tc and throw npe

---

seata-spring-boot-starter/src/main/java/io/seata/spring/boot/autoconfigure/SeataAutoConfiguration.java

1.remove @ConditionalOnClass(DataSourceProxy.class) 
2.add attribute havingValue = "true" in @ConditionalOnProperty

optimize:optimization of seata-spring-boot-starter

---

server/src/main/java/io/seata/server/store/FlushDiskMode.java
server/src/main/java/io/seata/server/store/file/FileTransactionStoreManager.java

bugfix: when write the new file throw ClosedChannelException
fix #1875

bugfix: when write the new file throw ClosedChannelException

---

.gitignore
rm-datasource/src/main/java/io/seata/rm/datasource/sql/druid/BaseMySQLRecognizer.java
rm-datasource/src/main/java/io/seata/rm/datasource/sql/druid/oracle/BaseOracleRecognizer.java

jdbc parameter set null, cause error.
fixes #1852

bugfix: jdbc parameter set null

---

core/src/main/java/io/seata/core/model/ResourceManager.java
core/src/main/java/io/seata/core/rpc/netty/RmRpcClient.java
rm-datasource/src/main/java/io/seata/rm/datasource/DataSourceManager.java
saga/seata-saga-rm/src/main/java/io/seata/saga/rm/SagaResourceManager.java
tcc/src/main/java/io/seata/rm/tcc/TCCResourceManager.java

bugfix: fix register branch thread hang on tcc mode
fix #1888 #1862 
#1401

bugfix: fix register branch thread hang on tcc mode

---

test/src/test/resources/basic-test-context.xml

delete not use bean
it is not be defined

clean: remove clientTest  it's not use

---

server/src/main/java/io/seata/server/Server.java

…cServer init exception.
We need to tell the system something about code(eg:-1) when tc server abnormal exit system

bugfix: add exception system exit code  when rpcServer init.

---

core/src/main/java/io/seata/core/context/RootContext.java

bugfix: fix xidInterceptorType is null

---

core/src/main/java/io/seata/core/rpc/netty/v1/ProtocolV1Decoder.java
saga/seata-saga-statelang/src/main/java/io/seata/saga/statelang/domain/impl/AbstractTaskState.java
saga/seata-saga-statelang/src/main/java/io/seata/saga/statelang/domain/impl/StateMachineImpl.java
saga/seata-saga-tm/src/main/java/io/seata/saga/tm/DefaultSagaTransactionalTemplate.java

optimize : all override methods must be annotated with @override

---

rm-datasource/src/main/java/io/seata/rm/datasource/ConnectionContext.java
saga/seata-saga-engine/src/main/java/io/seata/saga/engine/evaluation/expression/ExpressionEvaluator.java
server/src/main/java/io/seata/server/store/StoreConfig.java

optimize : javadoc should be used for classes, class variables and methods.

---

common/src/test/java/io/seata/common/exception/FrameworkExceptionTest.java
common/src/test/java/io/seata/common/exception/StoreExceptionTest.java

optimize: optimize assert throw exception

optimize: optimize assert throw exception

---

core/src/main/java/io/seata/core/store/db/AbstractDataSourceGenerator.java

bugfix : fix string.format() method formatting error

---

tcc/src/main/java/io/seata/rm/tcc/interceptor/ActionInterceptorHandler.java
test/src/test/resources/basic-test-context.xml

reduce HashMap initial size,It doesn't need size of 16.

optimize: reduce HashMap initial size

---

server/src/main/resources/nacos-config.py

feature: nacos-config.py support  namespace

---

rm-datasource/src/main/java/io/seata/rm/datasource/exec/BaseTransactionalExecutor.java

…image data and don't call pkRows in loop)
optimize the speed when batch insert or batch update
fixes #1933 
compare the speed before merge and after merge when effect rows more than 10000

optimize:optimize the speed when batch insert or batch update

---

saga/seata-saga-engine-store/src/main/java/io/seata/saga/engine/store/db/DbAndReportTcStateLogStore.java
server/src/main/java/io/seata/server/coordinator/DefaultCore.java
test/src/test/java/io/seata/saga/engine/mock/MockSagaTransactionTemplate.java

Fix saga dose not delete branches when transaction ended. 
Optimize: RetryState and CompensateState dose not registry branch to Server now, only the original state instance is registered on the server, and its status should be reported. 
#1887

bugifx: fix saga dose not delete branches when transaction ended

---

server/src/main/java/io/seata/server/coordinator/DefaultCoordinator.java

leak of error trace while handleAsyncCommitting. It is difficult to find the error.
#1949

optimize: leak of error trace while handleAsyncCommitting

---

.travis.yml

bugfix: travis-ci exceeded the maximum log length
fix #1962 
ref https://www.jianshu.com/p/3025c3814961

bugfix: travis-ci exceeded the maximum log length

---

server/src/main/java/io/seata/server/ParameterParser.java

bugfix: fixed error of get server port in container

---

rm-datasource/src/main/java/io/seata/rm/datasource/sql/SQLVisitorFactory.java
rm-datasource/src/main/java/io/seata/rm/datasource/sql/druid/MySqlOperateRecognizerHolder.java
rm-datasource/src/main/java/io/seata/rm/datasource/sql/druid/oracle/OracleOperateRecognizerHolder.java

When I use PG Sql in the feature branch, I found could not use one way to determine the SQL is for update or not. So, we have to use different way for different database.

optimize: optimize get select for update recognizer

---

server/src/test/java/io/seata/server/store/file/FileTransactionStoreManagerTest.java

fix FileTransactionStoreManagerTest failed on wins OS
fixes #1937

bugfix: FileTransactionStoreManagerTest failed on wins OS

---

.travis.yml
server/pom.xml
server/src/main/java/io/seata/server/ParameterParser.java

1. Removed presuppose environment variable
2. Replace base image of JDK8
3. Add JVM args for  respect CPU and RAM limits

bugfxi: fixed issue of presuppose environment variable and replace base image for tool

---

core/src/main/java/io/seata/core/constants/ConfigurationKeys.java
core/src/main/java/io/seata/core/rpc/netty/NettyBaseConfig.java
core/src/main/java/io/seata/core/rpc/netty/NettyClientConfig.java
core/src/main/java/io/seata/core/rpc/netty/NettyServerConfig.java

add netty config constant keys.

optimize: add netty config constant keys.

---

server/pom.xml

1. replace deprecated jvm args

bugfix: replace deprecated jvm args

---

config/seata-config-core/src/main/java/io/seata/config/ConfigurationKeys.java
config/seata-config-zk/src/main/java/io/seata/config/zk/ZookeeperConfiguration.java
server/src/test/java/io/seata/server/store/file/FileTransactionStoreManagerTest.java

There are many projects for 'config' node in zk, such as kafka.

optimize: rename zk configuration root path.

---

spring/src/main/java/io/seata/spring/annotation/GlobalTransactionScanner.java

When enable auto proxying of datasouce which has final modifier,it will cause a Exception means the class can't be proxied by using cglib.This PR will use JDK proxy instead of cglib to avoid this problem.
fixes #1995 
I've done integration testing with following scenes:
1.Specific init-method for a datasource bean defination.
2.A datasource class that with final modifier.
3.A datasource that extends AbstractRoutingDataSource.

bugfix:fix auto proxying of datasource which has final modifier

---

core/src/main/java/io/seata/core/rpc/DefaultServerMessageListenerImpl.java

optimize:show the applicationId when register TM
when register TM,we do not know which application register,we just know the ip and port like this:
`io.seata.core.rpc.DefaultServerMessageListenerImpl.onRegTmMessage:133 -checkAuth for client:192.168.xx.xx:10984 vgroup:fsp_tx_group ok
`
When we monitor the server log，it is very unfriendly,we want to know which application had regiested,or remove，like this:
`io.seata.core.rpc.DefaultServerMessageListenerImpl.onRegTmMessage:133 -checkAuth for client:192.168.xx.xx:10984 vgroup:fsp_tx_group  applicationId:user-server ok`

optimize:show the applicationId when register TM

---

saga/seata-saga-engine-store/src/main/java/io/seata/saga/engine/store/db/DbAndReportTcStateLogStore.java
saga/seata-saga-engine-store/src/main/resources/sql/db2_init.sql
saga/seata-saga-engine-store/src/main/resources/sql/h2_init.sql
saga/seata-saga-engine-store/src/main/resources/sql/mysql_init.sql
saga/seata-saga-engine-store/src/main/resources/sql/oracle_init.sql
saga/seata-saga-engine/src/main/java/io/seata/saga/engine/pcext/utils/EngineUtils.java
saga/seata-saga-engine/src/main/java/io/seata/saga/engine/repo/impl/StateMachineRepositoryImpl.java
saga/seata-saga-statelang/src/main/java/io/seata/saga/statelang/domain/DomainConstants.java
saga/seata-saga-statelang/src/main/java/io/seata/saga/statelang/parser/impl/StateMachineParserImpl.java
test/src/test/resources/saga/sql/db2_init.sql
test/src/test/resources/saga/sql/h2_init.sql
test/src/test/resources/saga/sql/mysql_init.sql
test/src/test/resources/saga/sql/oracle_init.sql

Saga nested transaction(SubState Machine)will create a new Global transaction, it is not necessary, We need make it Flatten.
#1974
run unit test at seata/test/src/test/java/io/seata/saga

optimize: Flatten Saga nested transactions

---

saga/seata-saga-engine/src/main/java/io/seata/saga/engine/pcext/handlers/ServiceTaskStateHandler.java
saga/seata-saga-engine/src/main/java/io/seata/saga/engine/pcext/handlers/SubStateMachineHandler.java
saga/seata-saga-processctrl/src/main/java/io/seata/saga/proctrl/handler/DefaultRouterHandler.java

Too much log output in Saga mode, we need to change log level to debug.
#2019

optimize: optimize saga log output

---

config/seata-config-etcd3/src/main/java/io/seata/config/etcd3/EtcdConfiguration.java

bugfix: fix Etcd3Configuration FILE_CONFIG reference incorrect.

---

rm-datasource/src/main/java/io/seata/rm/datasource/sql/struct/cache/MysqlTableMetaCache.java

fix mysql connect unable to release bug
fixes [#2034](https://github.com/seata/seata/issues/2034)
fixes [#2035](https://github.com/seata/seata/issues/2035)

bugfix: fix mysql connection unable to release

---

config/seata-config-core/src/main/java/io/seata/config/FileConfiguration.java

fix seata-spring-boot-starter does not work.
fixes #2027

bugfix:fix seata-spring-boot-starter does not work

---

spring/src/main/java/io/seata/spring/annotation/GlobalTransactionScanner.java
spring/src/main/java/io/seata/spring/util/SpringProxyUtils.java

…druid-spring-boot-starter dependency is used
Fix startup failure issue caused when dynamic proxy is turned on and druid-spring-boot-starter dependency is used
fixes #2045

bugfix: startup failure when dynamic proxy is turned on and use druid-spring-boot-starter

---

server/src/main/java/io/seata/server/session/db/DataBaseSessionManager.java

bugfix: RetryRollbackingSessionManager lost Rollbacking

---

tm/src/main/java/io/seata/tm/TransactionManagerHolder.java
tm/src/main/java/io/seata/tm/api/DefaultFailureHandlerImpl.java
tm/src/main/java/io/seata/tm/api/DefaultGlobalTransaction.java
tm/src/main/java/io/seata/tm/api/GlobalTransactionContext.java
tm/src/main/java/io/seata/tm/api/transaction/TransactionHookManager.java
tm/src/main/java/io/seata/tm/api/transaction/TransactionInfo.java
tm/src/test/java/io/seata/tm/api/DefaultFailureHandlerImplTest.java
tm/src/test/java/io/seata/tm/api/DefaultGlobalTransactionTest.java
tm/src/test/java/io/seata/tm/api/GlobalTransactionContextTest.java
tm/src/test/java/io/seata/tm/api/transaction/RollbackRuleTest.java

optimize: tm module code style

---

rm-datasource/src/test/java/io/seata/rm/datasource/mock/MockDatabaseMetaData.java
rm-datasource/src/test/java/io/seata/rm/datasource/mock/MockDriver.java
rm-datasource/src/test/java/io/seata/rm/datasource/sql/struct/cache/MysqlTableMetaCacheTest.java
rm-datasource/src/test/java/io/seata/rm/datasource/sql/struct/cache/OracleTableMetaCacheTest.java

1.change the name of TableMetaCacheTest to MysqlTableMetaCacheTest
2.increate the oracle table meta cache code coverage
3.support mock primary key meta.

optimize: increase the oracle table meta cache code coverage

---

metrics/seata-metrics-core/src/main/java/io/seata/metrics/exporter/ExporterType.java
metrics/seata-metrics-core/src/main/java/io/seata/metrics/registry/RegistryType.java
metrics/seata-metrics-exporter-prometheus/src/main/java/io/seata/metrics/exporter/prometheus/PrometheusExporter.java

optimize: some typos

---

core/src/main/java/io/seata/core/context/FastThreadLocalContextCore.java
core/src/main/resources/META-INF/services/io.seata.core.context.ContextCore

feature: support FastThreadLocalContextCore

---

common/src/main/java/io/seata/common/executor/Callback.java
common/src/main/java/io/seata/common/executor/Initialize.java
common/src/main/java/io/seata/common/loader/EnhancedServiceLoader.java
common/src/main/java/io/seata/common/thread/RejectedPolicies.java
common/src/main/java/io/seata/common/util/CollectionUtils.java
common/src/main/java/io/seata/common/util/NetUtil.java
common/src/main/java/io/seata/common/util/ReflectionUtil.java
common/src/main/java/io/seata/common/util/StringUtils.java
common/src/test/java/io/seata/common/thread/RejectedPoliciesTest.java
common/src/test/java/io/seata/common/util/NetUtilTest.java
common/src/test/java/io/seata/common/util/ReflectionUtilTest.java

I studied and read the seata source code in the seta-common module and found some optimization points.

refactor: simplify to make seata-common more readable

---

config/seata-config-core/src/main/java/io/seata/config/ConfigFuture.java

optimize:optimize log specifications

---

common/src/test/java/io/seata/common/util/IOUtilTest.java
common/src/test/java/io/seata/common/util/NumberUtilsTest.java

Enhance the test coverage of `seata-common` module.
It's a partial fix of #187 .
It adds tests... again... \o/
Run tests and coverage of `seata-common` module.
Should I update the Copyright 1999-2019 to 2020?

test: enhance test coverage of seata common

---

saga/seata-saga-statemachine-designer/src/Flow/WorkSpace.js

Optimize: saga statemachine designer add default properties for 'catch' node.
Many user feedback added the catch node, but did not catch the exception, 
the reason is because they don't configure the type of exception to catch. So the designer fills in "java.lang.Throwable" by default

optimize: saga statemachine designer add default properties for 'catch' node

---

config/seata-config-apollo/src/main/java/io/seata/config/apollo/ApolloConfiguration.java
config/seata-config-consul/src/main/java/io/seata/config/consul/ConsulConfiguration.java
config/seata-config-core/src/main/java/io/seata/config/ConfigurationFactory.java
config/seata-config-core/src/main/java/io/seata/config/FileConfiguration.java
config/seata-config-core/src/test/java/io.seata.config/FileConfigurationTest.java
config/seata-config-etcd3/src/main/java/io/seata/config/etcd3/EtcdConfiguration.java
config/seata-config-nacos/src/main/java/io/seata/config/nacos/NacosConfiguration.java
config/seata-config-zk/src/main/java/io/seata/config/zk/ZookeeperConfiguration.java

I found some optimization points when i was reading source code in seata-config module.

refactor: make seata-config more readable

---

server/src/main/java/io/seata/server/ParameterParser.java

1. Fixed issue of judgement container error in older version kubernetes

bugfix: fixed issue of judgement container in kubernetes

---

common/src/main/java/io/seata/common/util/ReflectionUtil.java
common/src/test/java/io/seata/common/util/ReflectionUtilTest.java
core/src/main/java/io/seata/core/constants/ConfigurationKeys.java
script/config-center/config.txt
server/src/main/java/io/seata/server/coordinator/DefaultCoordinator.java
server/src/main/resources/file.conf.example
server/src/test/java/io/seata/server/coordinator/DefaultCoordinatorTest.java

fixes #2166 
DefaultCoordinatorTest.test_handleRetryRollbackingTimeOut
DefaultCoordinatorTest.test_handleRetryRollbackingTimeOut_unlock

bugfix: fix global lock not released when rollback retry timeout

---

discovery/seata-discovery-consul/src/main/java/io/seata/discovery/registry/consul/ConsulRegistryServiceImpl.java
discovery/seata-discovery-core/src/main/java/io/seata/discovery/loadbalance/LoadBalanceFactory.java
discovery/seata-discovery-core/src/main/java/io/seata/discovery/registry/RegistryFactory.java
discovery/seata-discovery-etcd3/src/main/java/io/seata/discovery/registry/etcd3/EtcdRegistryServiceImpl.java
discovery/seata-discovery-eureka/src/main/java/io/seata/discovery/registry/eureka/EurekaRegistryServiceImpl.java
discovery/seata-discovery-nacos/src/main/java/io/seata/discovery/registry/nacos/NacosRegistryServiceImpl.java
discovery/seata-discovery-redis/src/main/java/io/seata/discovery/registry/redis/RedisRegistryServiceImpl.java
discovery/seata-discovery-sofa/src/main/java/io/seata/discovery/registry/sofa/SofaRegistryServiceImpl.java
discovery/seata-discovery-zk/src/main/java/io/seata/discovery/registry/zk/ZookeeperRegisterServiceImpl.java
discovery/seata-discovery-zk/src/test/java/io/seata/discovery/registry/zk/ZookeeperRegisterServiceImplTest.java

I found some optimization points when i was reading source code in seata-discovery module.

refactor: make seata-discovery more readable

---

core/src/main/java/io/seata/core/context/RootContext.java

optimize: RootContext.java code style

---

discovery/seata-discovery-eureka/src/main/java/io/seata/discovery/registry/eureka/CustomEurekaInstanceConfig.java

在 通过eureka作为注册中心过程中发现注册到 eureka 中，健康检查和状态等地址中获取的均为服务器的hostname而非对应ip。通过 CustomEurekaInstanceConfig 中重写getHostName()方法修改为获取ip来解决该问题。

optimize: override eureka getHostName() return ipAddress

---

rm-datasource/src/main/java/io/seata/rm/datasource/sql/struct/TableMetaCache.java
rm-datasource/src/main/java/io/seata/rm/datasource/sql/struct/TableMetaCacheFactory.java
rm-datasource/src/main/java/io/seata/rm/datasource/sql/struct/cache/MysqlTableMetaCache.java
rm-datasource/src/main/java/io/seata/rm/datasource/sql/struct/cache/OracleTableMetaCache.java
rm-datasource/src/main/java/io/seata/rm/datasource/undo/AbstractUndoLogManager.java
rm-datasource/src/main/java/io/seata/rm/datasource/undo/KeywordChecker.java
rm-datasource/src/main/java/io/seata/rm/datasource/undo/KeywordCheckerFactory.java
rm-datasource/src/main/java/io/seata/rm/datasource/undo/UndoExecutorHolder.java
rm-datasource/src/main/java/io/seata/rm/datasource/undo/UndoExecutorHolderFactory.java
rm-datasource/src/main/java/io/seata/rm/datasource/undo/UndoLogManager.java
rm-datasource/src/main/java/io/seata/rm/datasource/undo/UndoLogManagerFactory.java
rm-datasource/src/main/java/io/seata/rm/datasource/undo/mysql/MySQLUndoExecutorHolder.java
rm-datasource/src/main/java/io/seata/rm/datasource/undo/mysql/MySQLUndoLogManager.java
rm-datasource/src/main/java/io/seata/rm/datasource/undo/mysql/keyword/MySQLKeywordChecker.java
rm-datasource/src/main/java/io/seata/rm/datasource/undo/oracle/OracleUndoExecutorHolder.java
rm-datasource/src/main/java/io/seata/rm/datasource/undo/oracle/OracleUndoLogManager.java
rm-datasource/src/main/java/io/seata/rm/datasource/undo/oracle/keyword/OracleKeywordChecker.java
rm-datasource/src/main/java/io/seata/rm/datasource/util/JdbcUtils.java
rm-datasource/src/test/java/io/seata/rm/datasource/sql/SQLVisitorFactoryTest.java
rm-datasource/src/test/java/io/seata/rm/datasource/sql/struct/TableMetaCacheFactoryTest.java
rm-datasource/src/test/java/io/seata/rm/datasource/undo/KeywordCheckerFactoryTest.java
rm-datasource/src/test/java/io/seata/rm/datasource/undo/mysql/MySQLUndoLogManagerTest.java
sqlparser/seata-sqlparser-druid/src/main/java/io/seata/sqlparser/druid/SQLOperateRecognizerHolder.java
sqlparser/seata-sqlparser-druid/src/main/java/io/seata/sqlparser/druid/SQLOperateRecognizerHolderFactory.java
sqlparser/seata-sqlparser-druid/src/main/java/io/seata/sqlparser/druid/mysql/MySQLOperateRecognizerHolder.java
sqlparser/seata-sqlparser-druid/src/main/java/io/seata/sqlparser/druid/oracle/OracleOperateRecognizerHolder.java

refactor: Replace TableMetaCache and UndoLogManager and UndoExecutorHolder and KeywordChecker and SQLOperateRecognizerHolder with LoadLevel

refactor: Replace getDbType with LoadLevel name

---

config/seata-config-core/src/main/java/io/seata/config/FileConfiguration.java
seata-spring-boot-starter/src/main/java/io/seata/spring/boot/autoconfigure/provider/SpringBootConfigurationProvider.java

fix the value of disableGlobalTransaction not being read correctly.
fixes #2114 

bugfix:fix the value of disableGlobalTransaction not being read correctly

---

core/src/main/java/io/seata/core/context/ContextCoreLoader.java

optimize: ContextCoreLoader.java code style

---

common/pom.xml
core/pom.xml
integration/http/pom.xml
integration/http/src/main/java/io/seata/integration/http/AbstractHttpExecutor.java
integration/http/src/test/java/io/seata/integration/http/HttpTest.java
rm-datasource/pom.xml
rm/pom.xml
saga/pom.xml
serializer/seata-serializer-protobuf/pom.xml
server/pom.xml
tcc/pom.xml
tm/pom.xml

There are some unnecessary transitive dependencies of client side artifacts, e.g. rm-datasource, that may lead to dependent artifact conflict in user's environment. 
```
...
<dependency>
<groupId>com.esotericsoftware</groupId>
<artifactId>kryo</artifactId>
</dependency>
<dependency>
<groupId>de.javakaffee</groupId>
<artifactId>kryo-serializers</artifactId>
</dependency>
...
```
This PR tried to remove unnecessary transitive dependencies of client side artifacts from pom.xml as much as possible.
Please have a review to check whether these changes are appropriate.

optimize: reduce unnecessary dependences in client side

---

server/src/main/java/io/seata/server/coordinator/Core.java
server/src/main/java/io/seata/server/coordinator/TransactionCoordinatorInbound.java
server/src/main/java/io/seata/server/coordinator/TransactionCoordinatorOutbound.java

optimize: separate tc In/Outbound interface.

---

rm-datasource/src/main/java/io/seata/rm/datasource/undo/parser/FastjsonUndoLogParser.java

bugfix: fix fastjson undo filter tableMeta

---

rm-datasource/src/main/java/io/seata/rm/datasource/DataCompareUtils.java

bugfix: fix type error when fastjson deserialize long type

---

common/src/main/java/io/seata/common/loader/EnhancedServiceLoader.java
rm-datasource/src/test/java/io/seata/rm/datasource/sql/SQLVisitorFactoryTest.java
rm-datasource/src/test/java/io/seata/rm/datasource/sql/druid/postgresql/PostgresqlDeleteRecognizerTest.java
rm-datasource/src/test/java/io/seata/rm/datasource/sql/druid/postgresql/PostgresqlInsertRecognizerTest.java
rm-datasource/src/test/java/io/seata/rm/datasource/sql/druid/postgresql/PostgresqlSelectForUpdateRecognizerTest.java
rm-datasource/src/test/java/io/seata/rm/datasource/sql/druid/postgresql/PostgresqlUpdateRecognizerTest.java
sqlparser/seata-sqlparser-druid/pom.xml
sqlparser/seata-sqlparser-druid/src/main/java/io/seata/sqlparser/druid/DefaultDruidLoader.java
sqlparser/seata-sqlparser-druid/src/main/java/io/seata/sqlparser/druid/DruidDbTypeParserImpl.java
sqlparser/seata-sqlparser-druid/src/main/java/io/seata/sqlparser/druid/DruidDelegatingDbTypeParser.java
sqlparser/seata-sqlparser-druid/src/main/java/io/seata/sqlparser/druid/DruidDelegatingSQLRecognizerFactory.java
sqlparser/seata-sqlparser-druid/src/main/java/io/seata/sqlparser/druid/DruidIsolationClassLoader.java
sqlparser/seata-sqlparser-druid/src/main/java/io/seata/sqlparser/druid/DruidLoader.java
sqlparser/seata-sqlparser-druid/src/main/java/io/seata/sqlparser/druid/DruidSQLRecognizerFactoryImpl.java
sqlparser/seata-sqlparser-druid/src/main/java/io/seata/sqlparser/druid/SQLOperateRecognizerHolderFactory.java
sqlparser/seata-sqlparser-druid/src/main/resources/META-INF/services/io.seata.sqlparser.SQLRecognizerFactory
sqlparser/seata-sqlparser-druid/src/main/resources/META-INF/services/io.seata.sqlparser.util.DbTypeParser
sqlparser/seata-sqlparser-druid/src/test/java/io/seata/sqlparser/druid/DruidDbTypeParserTest.java
sqlparser/seata-sqlparser-druid/src/test/java/io/seata/sqlparser/druid/DruidIsolationTest.java
sqlparser/seata-sqlparser-druid/src/test/java/io/seata/sqlparser/druid/DruidLoaderForTest.java

This PR was created to to solve druid compatibility issue, because druid was only used to do sql parser,  so all druid related code were isolated from users' druid by a separate class loader. All imports from druid in rm-datasource were removed except unit test code. In addition, sql parser part was extracted to several new projects as SPI, e.g., seata-sqlparser-core and seata-sqlparser-druid.

feature: isolate druid used in rm-datasource to solve druid compatibility issue

---

all/pom.xml
bom/pom.xml
core/src/main/java/io/seata/core/protocol/Version.java
pom.xml

version: change version to 1.2.0-SNAPSHOT

version: change version to 1.2.0-SNAPSHOT

---

.travis.yml
codecov.yml

Codecov ignore mock
ci success

codecov: codecov ignore mock

---

test/pom.xml

spring-jdbc was duplicated in seate-test module.
#2296

optimize: remove duplicated dependency in seate-test module

---

seata-spring-boot-starter/src/main/java/io/seata/spring/boot/autoconfigure/SeataAutoConfiguration.java

fix seataAutoConfig enableAutoDataSourceProxy issue

bugfix:fix the judgement of configuration condition

---

rm-datasource/src/main/java/io/seata/rm/datasource/undo/parser/FastjsonUndoLogParser.java
rm-datasource/src/main/java/io/seata/rm/datasource/undo/parser/KryoSerializerFactory.java
rm-datasource/src/main/java/io/seata/rm/datasource/undo/parser/ProtostuffUndoLogParser.java
rm-datasource/src/test/java/io/seata/rm/datasource/undo/BaseUndoLogParserTest.java
rm-datasource/src/test/java/io/seata/rm/datasource/undo/parser/FastjsonUndoLogParserTest.java
rm-datasource/src/test/java/io/seata/rm/datasource/undo/parser/KryoUndoLogParserTest.java
rm-datasource/src/test/java/io/seata/rm/datasource/undo/parser/ProtostuffUndoLogParserTest.java

bugfix: Timestamp deserialize lost nano
fix use kyro and protostuff deserialize lost nano
add UT for timestamp
fix #2303

bugfix: Timestamp deserialize lost nano

---

config/seata-config-apollo/src/main/java/io/seata/config/apollo/ApolloConfiguration.java
config/seata-config-core/src/main/resources/registry.conf
config/seata-config-core/src/test/resources/registry.conf
config/seata-config-zk/src/main/java/io/seata/config/zk/ZookeeperConfiguration.java
discovery/seata-discovery-zk/src/main/java/io/seata/discovery/registry/zk/ZookeeperRegisterServiceImpl.java
script/client/conf/registry.conf
serializer/seata-serializer-seata/src/test/resources/registry.conf
server/src/main/resources/registry.conf
test/src/test/resources/registry.conf

This is a small fix for seata1.1.0 since there are some config items need to be corrected.
fixes #2291

bugfix:fix some configuration not converted to camel style

---

all/pom.xml
bom/pom.xml
pom.xml

The descriptor of prerequisites in maven 3 was deprecated.
And please check out of here https://maven.apache.org/ref/3.6.3/maven-model/maven.html#class_prerequisites
#2305

optimize: fix deprecated prerequisites

---

rm-datasource/src/main/java/io/seata/rm/datasource/ConnectionContext.java
rm-datasource/src/main/java/io/seata/rm/datasource/exec/AbstractDMLBaseExecutor.java

bugfix: fix connection context can't be remove when global lock conflict
fix #2286

bugfix: fix connection context can't be remove when global lock retry

---

script/client/conf/registry.conf
script/client/spring/application.properties
script/client/spring/application.yml

remove redundant configuration

optimize:remove redundant configuration

---

bom/pom.xml
core/pom.xml
core/src/main/java/io/seata/core/store/db/AbstractDataSourceGenerator.java
core/src/test/java/io/seata/core/store/db/DataBaseLockStoreDAOTest.java
core/src/test/java/io/seata/core/store/db/LogStoreDataBaseDAOTest.java
distribution/pom.xml
distribution/release-seata.xml
rm-datasource/pom.xml
rm-datasource/src/test/java/io/seata/rm/datasource/undo/BaseH2Test.java
server/pom.xml
server/src/main/java/io/seata/server/store/db/DbcpDataSourceGenerator.java
server/src/main/java/io/seata/server/store/db/DruidDataSourceGenerator.java
server/src/test/java/io/seata/server/lock/db/DataBaseLockManagerImplTest.java
server/src/test/java/io/seata/server/session/db/DataBaseSessionManagerTest.java
server/src/test/java/io/seata/server/store/db/DataSourceGeneratorTest.java

This PR provided a feature that mysql 5.x and 8.x jdbc drivers coexist in the server to fix issues like #2116.
1) Made use of DriverClassLoader to load mysql 5.x and 8.x driver separately.
2) Moved mysql driver jar from classpath to special location that the mysql drivers can coexist.
3) Upgraded dbcp to avoid loading error ([https://issues.apache.org/jira/browse/DBCP-333](https://issues.apache.org/jira/browse/DBCP-333)).
4) Determined different drivers according to driverClassName:
```
store.db.driverClassName=com.mysql.jdbc.Driver -> mysql 5.x
store.db.driverClassName=com.mysql.cj.jdbc.Driver -> mysql 8.x
``` 
5) Tested following combinations:
```
dbcp + mysql-connector-java-5.1.30
dbcp + mysql-connector-java-8.0.19
druid + mysql-connector-java-5.1.30
druid + mysql-connector-java-8.0.19 …
```

feature: mysql 5.x and 8.x jdbc drivers coexist in the server

---

test/src/test/java/io/seata/saga/engine/mock/MockGlobalTransaction.java
tm/src/main/java/io/seata/tm/api/DefaultGlobalTransaction.java
tm/src/main/java/io/seata/tm/api/GlobalTransaction.java
tm/src/main/java/io/seata/tm/api/TransactionalTemplate.java

add get local global status
#2325

optimize: add get local global status

---

rm-datasource/src/main/java/io/seata/rm/datasource/undo/parser/KryoSerializerFactory.java
rm-datasource/src/main/java/io/seata/rm/datasource/undo/parser/ProtostuffUndoLogParser.java
rm-datasource/src/test/java/io/seata/rm/datasource/undo/BaseUndoLogParserTest.java

optimize protostuff and kryo serialize timestamp.

optimize: protostuff and kryo serialize timestamp 

---

core/src/main/java/io/seata/core/context/RootContext.java
integration/dubbo-alibaba/src/main/java/io/seata/integration/dubbo/alibaba/AlibabaDubboTransactionPropagationFilter.java
integration/dubbo/src/main/java/io/seata/integration/dubbo/ApacheDubboTransactionPropagationFilter.java
rm-datasource/src/main/java/io/seata/rm/datasource/exec/ExecuteTemplate.java
saga/seata-saga-engine-store/src/main/java/io/seata/saga/engine/store/db/DbAndReportTcStateLogStore.java
saga/seata-saga-tm/src/main/java/io/seata/saga/tm/DefaultSagaTransactionalTemplate.java
spring/src/main/java/io/seata/spring/annotation/GlobalTransactional.java
spring/src/main/java/io/seata/spring/annotation/GlobalTransactionalInterceptor.java
spring/src/main/java/io/seata/spring/tcc/TccActionInterceptor.java
test/src/test/java/io/seata/saga/engine/mock/MockGlobalTransaction.java
tm/src/main/java/io/seata/tm/api/DefaultGlobalTransaction.java
tm/src/main/java/io/seata/tm/api/GlobalTransaction.java
tm/src/main/java/io/seata/tm/api/GlobalTransactionContext.java
tm/src/main/java/io/seata/tm/api/TransactionalTemplate.java
tm/src/main/java/io/seata/tm/api/transaction/TransactionInfo.java
tm/src/test/java/io/seata/tm/api/APITest.java
tm/src/test/java/io/seata/tm/api/TransactionTemplateTest.java

Optimize transaction context behavior when transaction mode is switched:
1.remove interceptorType context variable.
2.add  branchType context variable and use it to distinguish different branch transaction modes.(distinguish TCC Mode and AT Mode)

optimize: optimize transaction context switch logic when transaction mode switching

---

discovery/seata-discovery-core/src/main/java/io/seata/discovery/registry/RegistryFactory.java
discovery/seata-discovery-core/src/main/java/io/seata/discovery/registry/RegistryType.java

… judge mode
optimize RegistryFactory singleton pattern and RegistryType judge mode

optimize: optimize RegistryFactory singleton pattern and RegistryType judge mode

---

server/src/main/java/io/seata/server/UUIDGenerator.java

optimize:optimize the magic num of date at UUIDGenerator

optimize:optimize the magic num of date at UUIDGenerator

---

server/src/main/resources/registry.conf

server zookeeper digest support

optimize:add zk missing configuration

---

README.md

README.md has a a misspelled word-"videa"
fixed a misspelled word in README.md "videa"->"video"
No

optimize: fix typo

---

integration/http/src/main/java/io/seata/integration/http/XidResource.java

Inaccurate judgment will lead to NullPointerException. After the global web exception is caught, the successful return result will be misjudged as a failure.

optimize: Inaccurate judgment will lead to NPE.

---

script/client/at/db/postgresql.sql

bugfix: fix missing sequence in undo_log table
fix #2289

bugfix: fix missing sequence in undo_log table

---

config/seata-config-core/src/main/java/io/seata/config/FileConfiguration.java

optimize file configuration reading
#2387

bugfix: configuration exceptions lead to increased CPU usage

---

server/src/main/resources/README-zh.md
server/src/main/resources/README.md

optimize: add link of script in document

---

bom/pom.xml
config/seata-config-nacos/src/main/java/io/seata/config/nacos/NacosConfiguration.java
discovery/seata-discovery-nacos/src/main/java/io/seata/discovery/registry/nacos/NacosRegistryServiceImpl.java
script/client/conf/registry.conf
script/client/spring/application.properties
script/client/spring/application.yml
seata-spring-boot-starter/src/main/java/io/seata/spring/boot/autoconfigure/properties/registry/ConfigNacosProperties.java
seata-spring-boot-starter/src/main/java/io/seata/spring/boot/autoconfigure/properties/registry/RegistryNacosProperties.java
server/src/main/resources/registry.conf

added permission configuration support for nacos 1.2
#2365

feature:added permission configuration support for nacos 1.2

---

README.md
script/client/conf/registry.conf
script/client/spring/application.properties
script/client/spring/application.yml
server/src/main/java/io/seata/server/UUIDGenerator.java
tm/src/main/java/io/seata/tm/api/DefaultGlobalTransaction.java
tm/src/main/java/io/seata/tm/api/TransactionalTemplate.java
tm/src/main/java/io/seata/tm/api/transaction/Propagation.java
tm/src/test/java/io/seata/tm/api/TransactionTemplateTest.java

1.add propagation about:never,mandatory；
2.optimize the transationTemplate code；

feature: support propagation.never, propagation.mandatory, transaction suspend and resume api

---

README.md
config/seata-config-core/src/main/java/io/seata/config/ConfigurationFactory.java
server/src/main/java/io/seata/server/coordinator/DefaultCoordinator.java

optimize: optimize contact us and startup log
1. The QR code of dingTalk into group is invalid
2. WeChat group cannot be actively entered into the group and replaced with WeChat official account
3. Optimize the problem that the output log is null at startup
4. change the log level when startup delete undolog.

optimize: optimize contact us and startup log

---

core/src/main/java/io/seata/core/constants/ConfigurationKeys.java
core/src/main/java/io/seata/core/store/db/AbstractDataSourceGenerator.java
script/config-center/config.txt
server/src/main/java/io/seata/server/store/DbcpDataSourceGenerator.java
server/src/main/java/io/seata/server/store/DruidDataSourceGenerator.java
server/src/main/resources/file.conf

increase max wait parameter configuration
#2482

support: add the max wait configuration for db

---

server/src/main/java/io/seata/server/session/GlobalSession.java

bugfix: memory visibility of active attribute in file mode
close the session, then no more branch can be registered.

bugfix: memory visibility of active attribute in file mode

---

server/src/main/java/io/seata/server/session/SessionHolder.java

fix bug of session store path value judgment

bugfix: fix bug of session store path value judgment

---

rm-datasource/src/main/java/io/seata/rm/datasource/ConnectionProxy.java
server/src/main/java/io/seata/server/lock/AbstractLockManager.java
server/src/main/java/io/seata/server/storage/db/lock/DataBaseLocker.java

1.fix: Fix the NPE when lockkey is null;
2.optimize:  Reduce once db request when lockkey is null;
yes.
[issue](https://github.com/seata/seata/issues/2496)

bugfix:  fix the NPE and reduce the request when lockkey is null

---

config/seata-config-core/src/main/java/io/seata/config/ConfigurationFactory.java
config/seata-config-core/src/main/java/io/seata/config/FileConfiguration.java
config/seata-config-zk/src/main/java/io/seata/config/zk/ZookeeperConfiguration.java
server/src/main/java/io/seata/server/coordinator/AbstractCore.java
server/src/main/java/io/seata/server/coordinator/DefaultCoordinator.java
server/src/main/java/io/seata/server/coordinator/DefaultCore.java

optimize: optimize config and server module log

optimize: optimize config and server module log

---

tcc/src/main/java/io/seata/rm/tcc/remoting/parser/HSFRemotingParser.java
tcc/src/main/resources/META-INF/services/io.seata.rm.tcc.remoting.RemotingParser

Support for HSF protocol by adding Seata HSFParser.
I made the following changes
- Modify the ‘GlobalTrans actionScanner’ to support HSF tag creation of HSF proxy bean
- Support for non SpringProxy beans with new parsing methods of  ‘SpringProxyUtils’ 
fixes #2248 #2228
I have used 'edas-demo' to verify the modification.

feature: support hsf on TCC transaction mode

---

rm-datasource/src/main/java/io/seata/rm/datasource/AbstractStatementProxy.java
rm-datasource/src/main/java/io/seata/rm/datasource/StatementProxy.java
rm-datasource/src/test/java/io/seata/rm/datasource/StatementProxyTest.java

fix bug #2537 
in seata 1.1.0 addBatch could invoke only once。
if use jdbcTemplate.batchUpdate(String...sql), Only supports one SQL

bugfix: fix executeBatch can not get targetSql in Statement mode

---

discovery/seata-discovery-core/src/main/java/io/seata/discovery/loadbalance/RandomLoadBalance.java

ThreadLocalRandom will achieve less contention.
Replace Random by ThreadLocalRandom in RandomLoadBalance，refer to the implement of RandomLoadBalance in dubbo.
test case LoadBalanceTest already exist.
test case LoadBalanceTest already exist.

optimize: replace Random by ThreadLocalRandom in RandomLoadBalance

---

discovery/seata-discovery-zk/src/main/java/io/seata/discovery/registry/zk/ZookeeperRegisterServiceImpl.java

increases the default timeout for zookeeper register
fix #2590

optimize: support the default timeout for zookeeper register

---

core/src/main/java/io/seata/core/rpc/netty/RpcServerBootstrap.java
core/src/main/java/io/seata/core/store/BranchTransactionDO.java
core/src/main/java/io/seata/core/store/GlobalTransactionDO.java
core/src/main/java/io/seata/core/store/db/sql/log/AbstractLogStoreSqls.java
rm-datasource/src/main/java/io/seata/rm/datasource/xa/XABranchXid.java
tcc/src/main/java/io/seata/rm/tcc/interceptor/ActionInterceptorHandler.java

…r#proceed
fix typo for io.seata.rm.tcc.interceptor.ActionInterceptorHandler#proceed
fix some coding guidelines analyze
fix io.seata.core.rpc.netty.RpcServerBootstrap#start  A static field should be directly referred by its class name instead of its corresponding object name.
fix io.seata.core.store.db.sql.log.AbstractLogStoreSqls#getQueryGlobalMax,io.seata.core.store.db.sql.log.AbstractLogStoreSqls#getQueryBranchMax.An overridden method from an interface or abstract class must be marked with @Override annotation.
fix io.seata.core.store.GlobalTransactionDO. Members of a POJO class must be wrapper classes. 
Not
No validation required
No validation required
Not

docs: fix typo and some coding guidelines

---

script/config-center/README.md
script/config-center/nacos/nacos-config.sh

Adapt to nacos 1.2 on permission control.
fixes #2612

bugfix: nacos-script adapt to nacos 1.2 on permission control.

---

discovery/seata-discovery-zk/src/main/java/io/seata/discovery/registry/zk/ZookeeperRegisterServiceImpl.java

seata-server使用zookeeper作为注册中心时，zookeeper要求设置密码才可以建立目录和写数据。
原有实现是先建目录，再设置密码进行写数据；但是当zookeeper根目录都要求有密码访问时，原实现会出错。需要改为先设置密码，再创建目录和写数据。

bugfix: fix could not create folder in zookeeper

---

sqlparser/seata-sqlparser-druid/src/main/java/io/seata/sqlparser/druid/mysql/MySQLDeleteRecognizer.java

fix mysql delete with alias error.
fixes: #2626

bugfix: fix get tablename and alias error in mysql delete 

---

rm-datasource/src/main/java/io/seata/rm/datasource/sql/struct/cache/AbstractTableMetaCache.java

optimize: optimize get table meta

---

config/seata-config-apollo/src/main/java/io/seata/config/apollo/ApolloConfiguration.java

修复因驼峰命名法导致配置apollo无法加载的bug
fixes #2627

bugfix:fix Apollo configuration load fail due to camel style

---

config/seata-config-consul/src/main/java/io/seata/config/consul/ConsulConfiguration.java
discovery/seata-discovery-consul/src/main/java/io/seata/discovery/registry/consul/ConsulRegistryServiceImpl.java

Fixed issue #2599 which can't get correct consul config center address

optimize: consul supports custom port

---

core/src/main/java/io/seata/core/constants/ClientTableColumnsName.java
rm-datasource/src/main/java/io/seata/rm/datasource/undo/mysql/MySQLUndoLogManager.java
script/client/at/db/mysql.sql

mysql business insert use select last insert id is undo_log id's value.
fixes: #2655

bugfix: fix mysql insert use select last insert id is undo_log id value

---

README.md

supplement using organization logs

doc: supplement using organization logos

---

spring/src/main/java/io/seata/spring/annotation/GlobalTransactionScanner.java

optimize : Change GlobalTransactionalInterceptor to singleton

---

spring/src/main/java/io/seata/spring/tcc/TccActionInterceptor.java

优化 TccActionInterceptor 的日志打印。防止调用Tcc接口的toString方法时，打印出NoSuchMethodException异常的WARN日志。

optimize: optimize TccActionInterceptor log print

---

config/seata-config-core/src/main/java/io/seata/config/ConfigType.java
config/seata-config-core/src/main/java/io/seata/config/ConfigurationFactory.java
discovery/seata-discovery-core/src/main/java/io/seata/discovery/registry/RegistryType.java
metrics/seata-metrics-core/src/main/java/io/seata/metrics/exporter/ExporterType.java
metrics/seata-metrics-core/src/main/java/io/seata/metrics/registry/RegistryType.java

fix: get configTypeName exception
fixes #2724

optimize: optimize get config type from configuration

---

config/seata-config-nacos/src/main/java/io/seata/config/nacos/NacosConfiguration.java
rm-datasource/src/main/java/io/seata/rm/datasource/sql/struct/cache/PostgresqlTableMetaCache.java

optimize get table meta in postgre sql

optimize: optimize get table meta in postgre sql

---

saga/seata-saga-processctrl/src/main/java/io/seata/saga/proctrl/process/impl/CustomizeBusinessProcessor.java

optimize: logger class miswrite

---

distribution/pom.xml
pom.xml
server/pom.xml

1. Copy jdbc driver to image
1. Build an image 
2. Run container by this image 
3. Found jdbc directory under `/seata-server/libs/jdbc`

optimize: copy jdbc driver to image

---

common/src/main/java/io/seata/common/thread/NamedThreadFactory.java
common/src/test/java/io/seata/common/thread/NamedThreadFactoryTest.java

optimized the generation rules of thread name factory
fixes #2741
has already add `NamedThreadFactoryTest#testThreadNameHasCounterWithPrefixCounter`
test cases pass
can view the thread name using jstack or jconsole

optimize: optimized the generation rules of thread name factory

---

rm-datasource/src/main/java/io/seata/rm/datasource/xa/ResourceManagerXA.java

optimize: Optimize the processing logic of XA's RM for unsupported transaction resources.

optimize: Optimize the processing logic of XA's RM for unsupported transaction resources.

---

test/src/test/java/io/seata/saga/engine/db/StateMachineDBTests.java

fix https://github.com/seata/seata/issues/2414#issuecomment-639546811

optimize: disable unstable unit tests

---

common/src/main/java/io/seata/common/util/CollectionUtils.java

CollectionUtils.decodeMap 方法内部变量不存在线程安全问题，改成HashMap；
方法内部变量不存在线程安全问题，改成HashMap；
no
no
run CollectionUtilsTest

optimize: CollectionUtils.decodeMap method variables ConcurrentHashMap refact to HashMap

---

server/src/main/java/io/seata/server/storage/db/store/LogStoreDataBaseDAO.java

paramsPlaceHolder generate by StringUtils.repeat()
1.  paramsPlaceHolder generate by StringUtils.repeat()
2.  make read easy
3. run test LogStoreDataBaseDAOTest

optimize: paramsPlaceHolder generate by StringUtils.repeat()

---

rm-datasource/src/main/java/io/seata/rm/datasource/exec/BaseInsertExecutor.java
spring/src/main/java/io/seata/spring/annotation/GlobalTransactionalInterceptor.java
tm/src/main/java/io/seata/tm/api/DefaultFailureHandlerImpl.java
tm/src/main/java/io/seata/tm/api/FailureHandler.java
tm/src/main/java/io/seata/tm/api/TransactionalTemplate.java

1、TM在往TC发起回滚请求时，如果连接TC超时了，会向外抛出超时异常，但实际上需要往外抛的是业务异常。
2、TM在往TC发起回滚请求时，RM端回滚失败导致全局事务进入RollbackRetrying状态时，触发了空指针异常。

bugfix: TM rollback fail throw the seata exception, rollback retrying throw NPE

---

core/src/main/java/io/seata/core/constants/ConfigurationKeys.java
core/src/main/java/io/seata/core/constants/DefaultValues.java
core/src/main/java/io/seata/core/rpc/netty/AbstractRpcRemotingServer.java
core/src/main/java/io/seata/core/rpc/netty/RpcServer.java
core/src/main/java/io/seata/core/rpc/processor/server/RegRmProcessor.java
core/src/main/java/io/seata/core/rpc/processor/server/RegTmProcessor.java
server/src/main/java/io/seata/server/auth/AbstractCheckAuthHandler.java
server/src/main/java/io/seata/server/auth/DefaultCheckAuthHandler.java
server/src/main/resources/META-INF/services/io.seata.core.rpc.netty.RegisterCheckAuthHandler
server/src/main/resources/file.conf.example

feature: server check auth support SPI

feature: server check auth support SPI

---

core/pom.xml
core/src/main/java/io/seata/core/event/GuavaEventBus.java
spring/src/main/java/io/seata/spring/annotation/GlobalTransactionalInterceptor.java
spring/src/main/java/io/seata/spring/event/DegradeCheckEvent.java

optimize: downgrade check unlock and asynchronous

optimize: downgrade check unlock and asynchronous

---

saga/seata-saga-engine-store/src/main/java/io/seata/saga/engine/store/db/DbAndReportTcStateLogStore.java
saga/seata-saga-engine/src/main/java/io/seata/saga/engine/pcext/handlers/CompensationTriggerStateHandler.java
saga/seata-saga-processctrl/src/main/java/io/seata/saga/proctrl/HierarchicalProcessContext.java
saga/seata-saga-processctrl/src/main/java/io/seata/saga/proctrl/ProcessContext.java
saga/seata-saga-processctrl/src/main/java/io/seata/saga/proctrl/impl/ProcessContextImpl.java

bug修复：在SAGA事务，以同步方式执行时，正向服务出现异常后，可以通过stateMachineInstance.getException()方法获取到该异常。
此PR从 #2551 中拆分出来的。
以同步方式执行SAGA事务，并故意在业务方法中抛出异常，并使冲正补偿执行成功。然后在事务结束后，通过stateMachineInst.getException()，看看是否可以获取到业务方法中抛出的异常信息。

bugfix: fix business exception is lost when compensation succeed in saga mode

---

all/pom.xml

When I install the snapshot version of seata. I found the error of can not find class of 
```
com.google.common.eventbus.AsyncEventBus
```
fix #2869

bugfix: fix can not find com.google.common.eventbus.AsyncEventBus

---

rm-datasource/src/main/java/io/seata/rm/datasource/AbstractConnectionProxy.java

When get table meta, table meta cache already handle the different kind of table name. so we do not need to transfer it.

bugfix: fix get table meta failed when table name like 'schame'.'table'.

---

rm-datasource/src/main/java/io/seata/rm/datasource/ColumnUtils.java
rm-datasource/src/main/java/io/seata/rm/datasource/exec/DeleteExecutor.java
rm-datasource/src/main/java/io/seata/rm/datasource/exec/MultiDeleteExecutor.java
rm-datasource/src/main/java/io/seata/rm/datasource/sql/struct/cache/MysqlTableMetaCache.java
rm-datasource/src/main/java/io/seata/rm/datasource/sql/struct/cache/PostgresqlTableMetaCache.java
rm-datasource/src/main/java/io/seata/rm/datasource/undo/KeywordChecker.java
rm-datasource/src/main/java/io/seata/rm/datasource/undo/mysql/keyword/MySQLKeywordChecker.java
rm-datasource/src/main/java/io/seata/rm/datasource/undo/oracle/keyword/OracleKeywordChecker.java
rm-datasource/src/main/java/io/seata/rm/datasource/undo/postgresql/keyword/PostgresqlKeywordChecker.java
rm-datasource/src/test/java/io/seata/rm/datasource/ColumnUtilsTest.java
rm-datasource/src/test/java/io/seata/rm/datasource/sql/struct/cache/MysqlTableMetaCacheTest.java
rm-datasource/src/test/java/io/seata/rm/datasource/sql/struct/cache/OracleTableMetaCacheTest.java
rm-datasource/src/test/java/io/seata/rm/datasource/sql/struct/cache/PostgresqlTableMetaCacheTest.java
rm-datasource/src/test/java/io/seata/rm/datasource/undo/mysql/keyword/MySQLKeywordCheckerTest.java
rm-datasource/src/test/java/io/seata/rm/datasource/undo/oracle/keyword/OracleKeywordCheckerTest.java
rm-datasource/src/test/java/io/seata/rm/datasource/undo/postgresql/keyword/PostgresqlKeywordCheckerTest.java

fix ColumnUtils#delEscape like \`scheme\`.\`table\` error, optimize KeywordChecker checkAndReplace method.

bugfix: ColumnUtils delEscape with scheme error.

---

rm/src/main/java/io/seata/rm/AbstractRMHandler.java

The previous logic client side did not have onResponse logic. The TransactionMessageHandler interface has an implementation class AbstractRMHandler. The onRequest method is specifically used to handle rm’s commit, rollback, and deleteUndoLog. After putting these logics in the processor, commit, rollback, and deleteUndoLog are all independent. The respective processor, the logic of onResponse is placed in ClientOnResponseProcessor, so the relevant logic of the client response is placed here, unified and centralized processing

bugfix: fix rm client receive response logic.

---

rm-datasource/src/main/java/io/seata/rm/datasource/sql/struct/cache/PostgresqlTableMetaCache.java

fix could not get table meta in pg when table name like schema.table
#2892

bugfix: fix get table meta failed in postgresql.

---

test/src/test/resources/saga/statelang/simple_statelang_with_catches.json
test/src/test/resources/saga/statelang/simple_statelang_with_retry.json
test/src/test/resources/saga/statelang/simple_statelang_with_script.json

Fix spelling issues in saga mode statelang examples. The lowercase 'output' in states will not put any return value into state machine context.
NO
N/A
N/A
N/A

bugfix: fix misspelling in statelang examples

---

config/seata-config-core/src/main/java/io/seata/config/ConfigurationCache.java

bugfix: fix getConfig cache value is 'null'

bugfix: fix getConfig cache value is 'null'

---

core/src/main/java/io/seata/core/constants/DefaultValues.java
core/src/main/java/io/seata/core/store/db/AbstractDataSourceProvider.java
server/src/main/java/io/seata/server/storage/db/lock/DataBaseLockManager.java
server/src/main/java/io/seata/server/storage/db/store/DataBaseTransactionStoreManager.java

Add some default configurations when store.mode is 'db'.
These default configurations are added according to the description in the official document.
fixes #2903

optimize: Added some configuration items to keep consistent with official documents

---

rm-datasource/src/main/java/io/seata/rm/datasource/ColumnUtils.java
rm-datasource/src/main/java/io/seata/rm/datasource/undo/KeywordChecker.java
rm-datasource/src/main/java/io/seata/rm/datasource/undo/postgresql/keyword/PostgresqlKeywordChecker.java
rm-datasource/src/test/java/io/seata/rm/datasource/ColumnUtilsTest.java

pgsql add escape check logic error, ColumnUtils add escape with scheme.

bugfix: ColumnUtils add escape with scheme.

---

discovery/seata-discovery-core/src/main/java/io/seata/discovery/registry/RegistryType.java

bugfix:fix error registry type comment

---

README.md

optimize: optimize some grammatical errors

---

rm-datasource/src/main/java/io/seata/rm/datasource/undo/parser/FastjsonUndoLogParser.java
rm-datasource/src/test/java/io/seata/rm/datasource/undo/parser/FastjsonUndoLogParserTest.java

fastjson write undo log not parser.

bugfix: fastjson write undo log not parser.

---

core/src/main/java/io/seata/core/rpc/TransportProtocolType.java
core/src/main/java/io/seata/core/rpc/TransportServerType.java
core/src/main/java/io/seata/core/rpc/netty/NettyBaseConfig.java
core/src/main/java/io/seata/core/serializer/SerializerType.java
script/client/conf/file.conf
script/client/spring/application.properties
script/client/spring/application.yml
seata-spring-boot-starter/src/main/java/io/seata/spring/boot/autoconfigure/properties/client/RmProperties.java
seata-spring-boot-starter/src/main/java/io/seata/spring/boot/autoconfigure/properties/client/ThreadFactoryProperties.java
seata-spring-boot-starter/src/main/java/io/seata/spring/boot/autoconfigure/properties/client/TransportProperties.java
seata-spring-boot-starter/src/main/resources/META-INF/additional-spring-configuration-metadata.json
server/src/main/resources/file.conf.example

1. 补充additional-spring-configuration-metadata.json，在springboot项目中，部分配置项可以提示可选值及其说明。
2. 顺便优化了`seata.transport.type`和`seata.transport.server`两个配置，使其兼容大小写以及多格式配置.
3. 协议枚举中，删除UDT及相关的所有注释，因为暂时还不支持。

optimize: opt additional-spring-configuration-metadata.json

---

core/src/main/java/io/seata/core/rpc/netty/RmNettyRemotingClient.java

【情况说明】
当资源注册（ResourceManager.registerResource）先于RM初始化（RMClient.init）时会打印错误日志，不过由于RMClient初始化后会有定时连接检测，所以对业务的影响只是在连接检测被触发之前资源不会被注册到TC，连接检测启动延迟目前为1分钟。（AbstractNettyRemotingClient.SCHEDULE_DELAY_MILLS = 60 * 1000L）。
错误日志:
Failed to get available servers: endpoint format should like ip:port
【原因分析】: 
由于资源注册时RM还没有初始化，所以此时transactionServiceGroup为空！
【解决方案】：
RmNettyRemotingClient.registerResource 加上transactionServiceGroup是否为空的检查
延迟注册，注册资源时如果RM尚未初始化则先不连接，待RM初始化时检查有已注册的RM则连接后将资源一并注册到TC
【复现方法】：
1、[样例代码](https://github.com/seata/seata-samples/tree/master/api) 直接将POM中seata版本切换为1.3运行
日志中会找到错误:Failed to get available servers: endpoint format should like ip:port
2、简化代码后发现，只要当资源注册先于RM初始化就会**复现问题**。可以将[样例代码](https://github.com/seata/seata-samples/blob/master/api/src/main/java/io/seata/samples/api/Bussiness.j …

optimize: ensure that the register message is sent after RM client initialization

---

common/src/main/java/io/seata/common/util/IdWorker.java

UUIDGenerator类的generateUUID()方法在高并发情况下，会生成重复的id
高并发压测发现
高并发压测，不会再出现重复的branchid
UUIDGenerator generate duplicated id

Bugfix: UUIDGenerator generates duplicated id

---

script/config-center/nacos/nacos-config.py

将!=改成<= 即可
运行：python nacos-config.py 172.16.xxx.xxx:31263  seata
提示：python nacos-config.py nacosAddr
看逻辑得知，请求的参数数量判断逻辑错误了
源逻辑：
`if len(sys.argv) != 2:
print ('python nacos-config.py nacosAddr')
exit()
`
修改后：
`if len(sys.argv) <= 2:
print ('python nacos-config.py nacosAddr')
exit()
`
可以正确执行，带 namespace 参数的命令
自己发现的
修改后保存：
执行  python nacos-config.py 172.16.xxx.xxx:31263  seata  成功，数据正确写入了nacos
查看命令窗口日志，并查看nacos配置，是否正确写入

bugfix: nacos-config.py script could not run with namespace

---

bom/pom.xml
config/seata-config-apollo/src/main/java/io/seata/config/apollo/ApolloConfiguration.java
script/client/conf/registry.conf
script/client/spring/application.properties
script/client/spring/application.yml
seata-spring-boot-starter/src/main/java/io/seata/spring/boot/autoconfigure/properties/config/ConfigApolloProperties.java
server/src/main/resources/registry.conf

add apollo secret key configuration
fixs #2940

feature: add apollo secret key configuration

---

config/seata-config-apollo/src/main/java/io/seata/config/apollo/ApolloConfiguration.java
core/src/main/java/io/seata/core/rpc/netty/RmNettyRemotingClient.java
core/src/main/java/io/seata/core/rpc/netty/TmNettyRemotingClient.java
pom.xml
style/seata_suppressions.xml

bugfix: fix checkstyle plugin can't exclude single file
fixs #2985 
http://maven.apache.org/plugins/maven-checkstyle-plugin/checkstyle-mojo.html#encoding
https://checkstyle.sourceforge.io/config_filters.html

bugfix: fix checkstyle plugin can't exclude single file

---

rm-datasource/src/main/java/io/seata/rm/datasource/SqlGenerateUtils.java
rm-datasource/src/test/java/io/seata/rm/datasource/SqlGenerateUtilsTest.java
rm-datasource/src/test/java/io/seata/rm/datasource/undo/AbstractUndoExecutorTest.java

bugfix: fix oracle database IN field size over 1000
fix #2951

bugfix: fix oracle database in field size over 1000

---

server/src/main/java/io/seata/server/storage/redis/lock/RedisLocker.java

fix redis locker delete lock incomplete
fixes #3029 
other person is change the same test cases
can delete all the lock key when has more than 3 row change in a branch session

bugfix: redis locker delete lock incomplete

---

core/src/main/java/io/seata/core/rpc/netty/NettyServerBootstrap.java

When server starting, the port will settle twice.

optimize: remove set port repeatedly

---

core/src/test/java/io/seata/core/store/db/sql/lock/LockStoreSqlFactoryTest.java
server/src/test/java/io/seata/server/lock/db/sql/lock/LockStoreSqlFactoryTest.java

bugfix: fix the wrong package path

---

core/src/main/java/io/seata/core/context/ContextCore.java
core/src/main/java/io/seata/core/context/FastThreadLocalContextCore.java
core/src/main/java/io/seata/core/context/RootContext.java
core/src/main/java/io/seata/core/context/ThreadLocalContextCore.java
core/src/test/java/io/seata/core/context/RootContextTest.java
integration/dubbo-alibaba/src/main/java/io/seata/integration/dubbo/alibaba/AlibabaDubboTransactionPropagationFilter.java
integration/dubbo-alibaba/src/test/java/io/seata/integration/dubbo/alibaba/AlibabaDubboTransactionPropagationFilterTest.java
integration/dubbo/src/main/java/io/seata/integration/dubbo/ApacheDubboTransactionPropagationFilter.java
integration/dubbo/src/test/java/io/seata/integration/dubbo/ApacheDubboTransactionPropagationFilterTest.java
rm-datasource/src/main/java/io/seata/rm/datasource/AbstractConnectionProxy.java
rm-datasource/src/main/java/io/seata/rm/datasource/exec/ExecuteTemplate.java
spring/src/main/java/io/seata/spring/tcc/TccActionInterceptor.java

optimize: opt ContextCore, can be set 'Object' value.
优化`ContextCore`，可设置Object值。
`RootContext.getBranchType()`和`RootContext.unbindBranchType()`方法的返回类型由`String`变为`BranchType`，部分判断方法的性能会更高。

optimize: opt ContextCore, can be set 'Object' value

---

server/pom.xml
server/src/main/java/io/seata/server/env/ContainerHelper.java
server/src/main/java/io/seata/server/logging/logback/ColorConverter.java
server/src/main/resources/logback.xml

bugfix: The color characters are messy when running by `seata-server.bat`.
BUG修复：当使用`seata-server.bat`运行时，颜色符号变成乱码的问题修复。
fixes #2954

bugfix: The color characters are messy when running by 'seata-server.bat'

---

common/src/main/java/io/seata/common/Constants.java
common/src/main/java/io/seata/common/DefaultValues.java
config/seata-config-core/src/main/java/io/seata/config/ConfigurationKeys.java
core/src/main/java/io/seata/core/constants/ClientTableColumnsName.java
core/src/main/java/io/seata/core/constants/ConfigurationKeys.java
core/src/main/java/io/seata/core/constants/ServerTableColumnsName.java
core/src/main/java/io/seata/core/protocol/MessageType.java
core/src/main/java/io/seata/core/protocol/ProtocolConstants.java
core/src/main/java/io/seata/core/rpc/netty/NettyBaseConfig.java
core/src/test/java/io/seata/core/rpc/netty/NettyBaseConfigTest.java
integration/grpc/src/main/java/io/seata/integration/grpc/interceptor/GrpcHeaderKey.java
metrics/seata-metrics-api/src/main/java/io/seata/metrics/IdConstants.java
rm-datasource/src/main/java/io/seata/rm/datasource/undo/UndoLogConstants.java
saga/seata-saga-statelang/src/main/java/io/seata/saga/statelang/domain/DomainConstants.java
seata-spring-boot-starter/src/main/java/io/seata/spring/boot/autoconfigure/StarterConstants.java
seata-spring-boot-starter/src/main/resources/META-INF/additional-spring-configuration-metadata.json
server/src/main/java/io/seata/server/metrics/MeterIdConstants.java
sqlparser/seata-sqlparser-core/src/main/java/io/seata/sqlparser/SqlParserType.java
tcc/src/main/java/io/seata/rm/tcc/remoting/Protocols.java

optimize: Add more configuration tips in `additional-spring-configuration-metadata.json`.
优化：添加更多配置提示信息到`additional-spring-configuration-metadata.json`中。
在springboot项目的yaml配置文件里，编写配置时，将会有提示信息，部分配置还有可选值提示。非常方便。
注：此PR是从 #2964 中拆分出来的。
1. 将常量类由类变更为接口，使代码看起来更简单。（无任何常量值或功能变更）
2. 优化`WorkThreadMode.getModeByName(String name)`方法。

optimize: Add more configuration tips in `additional-spring-configuration-metadata.json`

---

bom/pom.xml
server/pom.xml

seata-server需要fastjson做redis的序列化,原先server内的fastjson由nacos-client依赖引入,目前已经被移除,得单独引入
fixes #3138

optimize: Upgrade nacos and FastJSON dependencies

---

server/src/main/java/io/seata/server/storage/redis/store/RedisTransactionStoreManager.java

fix:the redis pipeline

---

server/src/main/java/io/seata/server/storage/redis/store/RedisTransactionStoreManager.java

the lock has this key,it is a name of hash:
`private static final String DEFAULT_REDIS_SEATA_GLOBAL_LOCK_PREFIX = "SEATA_GLOBAL_LOCK";`
the session has this key,it is a name of string:
` private static final String DEFAULT_REDIS_SEATA_GLOBAL_PREFIX = "SEATA_GLOBAL_";`
They have the same prefix :SEATA_GLOBAL_ ，the `RedisTransactionStoreManager# public List<GlobalSession> readSession(GlobalStatus[] statuses)`  ,use the` redis scan` of key SEATA_GLOBAL_* to get(key).
It will cause:
`redis.clients.jedis.exceptions.JedisDataException: WRONGTYPE Operation against a key holding the wrong kind of value
at redis.clients.jedis.Protocol.processError(Protocol.java:132)
at redis.clients.jedis.Protocol.process(Protocol.java:166)
at redis.clients.jedis.Protocol.read(Protocol.java:220)
at …

bugfix: the redis lock key and the session key has conflict

---

core/src/main/java/io/seata/core/context/RootContext.java
core/src/main/java/io/seata/core/model/BranchType.java
core/src/test/java/io/seata/core/model/BranchTypeTest.java
rm-datasource/src/main/java/io/seata/rm/BaseDataSourceResource.java
rm-datasource/src/main/java/io/seata/rm/datasource/AbstractDataSourceProxy.java
rm-datasource/src/main/java/io/seata/rm/datasource/DataSourceProxy.java
rm-datasource/src/main/java/io/seata/rm/datasource/SeataDataSourceProxy.java
rm-datasource/src/main/java/io/seata/rm/datasource/xa/DataSourceProxyXA.java
rm-datasource/src/test/java/io/seata/rm/datasource/DataSourceProxyTest.java
rm-datasource/src/test/java/io/seata/rm/datasource/mock/MockDataSource.java
rm-datasource/src/test/java/io/seata/rm/xa/DataSourceProxyXATest.java
seata-spring-boot-starter/src/main/java/io/seata/spring/boot/autoconfigure/SeataAutoConfiguration.java
spring/src/main/java/io/seata/spring/annotation/datasource/AutoDataSourceProxyRegistrar.java
spring/src/main/java/io/seata/spring/annotation/datasource/DataSourceProxyHolder.java
spring/src/main/java/io/seata/spring/annotation/datasource/SeataAutoDataSourceProxyAdvice.java
spring/src/main/java/io/seata/spring/annotation/datasource/SeataAutoDataSourceProxyCreator.java
spring/src/main/java/io/seata/spring/annotation/datasource/SeataDataSourceBeanPostProcessor.java

bugfix: fixed some problems in the automatic data source proxy.
修复自动数据源代理的一些问题，用户使用体验会更好，与第三方组件的兼容性也会更好。
注：从此PR是从 #2879 中拆分出来的。
1. `AT`/`XA`代理类构造函数中解除代理，避免用户手动创建代理导致双重代理所致的各种未知问题；(借用了大佬 @slievrly 的PR #2921 的代码，主要我这边新增了一个接口`SeataDataSourceProxy`)
2. 在不需要执行`AT`/`XA`代理时，不进入代理类的方法，而是直接执行原来的`DataSource`的功能，避免一些不可预测的问题，增强`seata`与其他第三方组件的兼容性。
3. 将1.1.0版本中所使用的生命周期时创建数据源代理的Bean恢复过来，并进行了改造。原本代理类会直接代替原来的数据源而成为bean，这次仅创建和初始化数据源代理，数据源bean还是原生的，不会改变。这样就不会产生1.1.0时的兼容性问题，同时解决了`AT`/`XA`在项目启动时未注册资源的问题了。
4. 修复了 _非springboot用户_ 使用`@EnableDataSourceProxy`启用XA模式时，`RootContext.DEFAULT_BRANCH_TYPE`的值却为`AT`的BUG。

bugfix: fix some problems in the automatic data source proxy

---

integration/http/src/main/java/io/seata/integration/http/AbstractHttpExecutor.java

1.remove Repeated conditional tests
2.keySet().stream()->map.foreach
fixes #3161

optimize: remove repeated conditional tests (#3161)

---

common/src/main/java/io/seata/common/util/StringUtils.java

optimize: string utils isBlank method.

optimize: remove duplicated in string utils

---

serializer/seata-serializer-seata/src/main/java/io/seata/serializer/seata/protocol/AbstractResultMessageCodec.java

optimize rpc message when message was substring

optimize: optimize rpc message when message was substring

---

script/client/conf/registry.conf
script/client/spring/application.properties
script/client/spring/application.yml
seata-spring-boot-starter/src/main/java/io/seata/spring/boot/autoconfigure/StarterConstants.java
seata-spring-boot-starter/src/main/java/io/seata/spring/boot/autoconfigure/properties/config/ConfigCustomProperties.java
seata-spring-boot-starter/src/main/java/io/seata/spring/boot/autoconfigure/properties/registry/RegistryCustomProperties.java
seata-spring-boot-starter/src/test/java/io/seata/spring/boot/autoconfigure/PropertiesTest.java

Add the Spring Boot support for custom config and registry type
Fixes #3196.

feature: spring boot support for custom config and registry type

---

core/src/main/java/io/seata/core/context/RootContext.java
rm-datasource/src/main/java/io/seata/rm/datasource/DataSourceProxy.java
rm-datasource/src/main/java/io/seata/rm/datasource/xa/DataSourceProxyXA.java
seata-spring-boot-starter/src/main/java/io/seata/spring/boot/autoconfigure/StarterConstants.java
spring/src/main/java/io/seata/spring/annotation/datasource/AutoDataSourceProxyRegistrar.java
spring/src/main/java/io/seata/spring/annotation/datasource/SeataAutoDataSourceProxyAdvice.java

bugfix: fix the `RootContext.DEFAULT_BRANCH_TYPE` is wrong in some cases.
修复BUG：在部分情况下，`RootContext.DEFAULT_BRANCH_TYPE`的值有误。
1. springboot项目中，使用配置启用XA自动代理时，而不是使用`@EnableAutoDataSourceProxy`启用XA自动代理。（这种情况下，XA代理**不生效**）
2. 手动创建XA代理，并禁用自动代理功能时。（这种情况下，XA代理**生效**，但是`RootContext.DEFAULT_BRANCH_TYPE`却是`AT`）

bugfix: fix the 'RootContext.DEFAULT_BRANCH_TYPE' is wrong in some cases

---

spring/src/main/java/io/seata/spring/annotation/datasource/AutoDataSourceProxyRegistrar.java

bugfix: fix use @EnableAutoDataSourceProxy startup failed
fix #3229

bugfix: fix use @EnableAutoDataSourceProxy startup failed

---

pom.xml
rm-datasource/src/test/java/io/seata/rm/datasource/mock/MockResultSet.java
server/src/main/java/io/seata/server/session/SessionHolder.java

bugfix: fix Collections NPE
fix #3234

bugfix: fix Collections NPE

---

rm-datasource/src/main/java/io/seata/rm/datasource/exec/AbstractDMLBaseExecutor.java

bugfix: fix batch sql getTableMeta error
fix #3244

bugfix: fix batch sql getTableMeta error

---

rm-datasource/src/main/java/io/seata/rm/datasource/exec/DeleteExecutor.java
rm-datasource/src/main/java/io/seata/rm/datasource/exec/UpdateExecutor.java
sqlparser/seata-sqlparser-core/src/main/java/io/seata/sqlparser/WhereRecognizer.java
sqlparser/seata-sqlparser-druid/src/main/java/io/seata/sqlparser/druid/mysql/BaseMySQLRecognizer.java
sqlparser/seata-sqlparser-druid/src/main/java/io/seata/sqlparser/druid/mysql/MySQLDeleteRecognizer.java
sqlparser/seata-sqlparser-druid/src/main/java/io/seata/sqlparser/druid/mysql/MySQLUpdateRecognizer.java
sqlparser/seata-sqlparser-druid/src/test/java/io/seata/sqlparser/druid/MySQLDeleteRecognizerTest.java

bugfix: fix the exception when limit condition contains VariantRefExpr
fixes #3251

bugfix: fix the exception when limit condition contains VariantRefExpr

---

compressor/seata-compressor-deflater/pom.xml
compressor/seata-compressor-deflater/src/main/java/io/seata/compressor/deflater/DeflaterCompressor.java
compressor/seata-compressor-deflater/src/main/java/io/seata/compressor/deflater/DeflaterUtil.java
compressor/seata-compressor-deflater/src/main/resources/META-INF/services/io.seata.core.compressor.Compressor
compressor/seata-compressor-deflater/src/test/java/io/seata/compressor/deflater/DeflaterCompressorTest.java
compressor/seata-compressor-deflater/src/test/java/io/seata/compressor/deflater/DeflaterUtilTest.java
core/src/main/java/io/seata/core/compressor/CompressorType.java

feature：add deflater support for seata compressor. 

---

script/client/spring/application.properties
script/client/spring/application.yml
seata-spring-boot-starter/src/main/resources/META-INF/additional-spring-configuration-metadata.json
server/src/main/java/io/seata/server/coordinator/DefaultCore.java

bugfix: when mixed use of AT and TCC, AT branchs is not deleted.
问题修复：AT和TCC混合使用时，AT分支未被及时删除。
顺便添加上一个PR中变更过配置位置的提示，效果如下图：
fixes #3295

bugfix: when mixed use of AT and TCC, AT branchs is not deleted

---

core/src/main/java/io/seata/core/rpc/netty/RmNettyRemotingClient.java
core/src/main/java/io/seata/core/rpc/netty/TmNettyRemotingClient.java

RmNettyRemotingClient/TmNettyRemotingClient do not used in pipeline, so can remove @Sharable

optimize: delete unnecessary @Sharable

---

common/src/main/java/io/seata/common/thread/NamedThreadFactory.java
common/src/test/java/io/seata/common/thread/NamedThreadFactoryTest.java

enable NamedThreadFactory to get ThreadGroup from the SecurityManager or Current thread
Reference JDK's implementation of DefaultThreadFactory
Ⅱ. Does this pull request fix one issue?
Ⅲ. Why don't you add test cases (unit test/integration test)?
Ⅳ. Describe how to verify it
Ⅴ. Special notes for reviews

optimize: enable NamedThreadFactory to get ThreadGroup from the SecurityManager or Current thread

---

rm-datasource/src/test/java/io/seata/rm/GlobalLockTemplateTest.java
rm-datasource/src/test/java/io/seata/rm/datasource/exec/LockRetryControllerTest.java

adjust GlobalLockTemplateTest logic, make it more stable when ci.

optimize: adjust GlobalLockTemplateTest

---

core/src/main/java/io/seata/core/context/RootContext.java

bugfix: fix throw `IllegalArgumentException` when using `hystrix` and `version 2.2.3.RELEASE and below of SCA`.
修复使用`hystrix`和`SCA 2.2.3.RELEASE及以下版本`时抛出`IllegalArgumentException`异常的问题。

bugfix: fix throw IllegalArgumentException when using hystrix and version 2.2.3.RELEASE and below of SCA

---

saga/seata-saga-engine/src/main/java/io/seata/saga/engine/pcext/handlers/SubStateMachineHandler.java

fix: 当子状态机实例创建失败后，修复找不到上一次子状态机实例，导致重试一直失败问题
fixes #3324

bugfix: fix retry commit unsuccess when record subMachineInst failed

---

core/src/test/java/io/seata/core/context/RootContextTest.java

bugfix: temporarily cancels unwanted test case

---

server/src/main/java/io/seata/server/ParameterParser.java
server/src/test/java/io/seata/server/ParameterParserTest.java

optimize: optimize ParameterParserTest test case failed
fix #3364

optimize: optimize ParameterParserTest test case failed

---

.github/workflows/build.yml
rm-datasource/src/test/java/io/seata/rm/datasource/PreparedStatementProxyTest.java
rm-datasource/src/test/java/io/seata/rm/datasource/StatementProxyTest.java
rm-datasource/src/test/java/io/seata/rm/datasource/exec/SelectForUpdateExecutorTest.java
rm-datasource/src/test/java/io/seata/rm/datasource/undo/mysql/MySQLUndoLogManagerTest.java
rm-datasource/src/test/java/io/seata/rm/xa/ConnectionProxyXATest.java
rm-datasource/src/test/java/io/seata/rm/xa/DataSourceProxyXATest.java
rm-datasource/src/test/resources/META-INF/services/io.seata.sqlparser.SQLRecognizerFactory
rm-datasource/src/test/resources/META-INF/services/io.seata.sqlparser.druid.SQLOperateRecognizerHolder
rm-datasource/src/test/resources/META-INF/services/io.seata.sqlparser.util.DbTypeParser

optimize: optimize github action

---

config/seata-config-core/src/main/java/io/seata/config/FileConfiguration.java

指定配置文件路径时，即使没有使用 file: 前缀，依然尝试在文件系统查找并加载
fixes #3344 
在 registry.conf 文件中配置文件路径的时候，不添加 `file:` 前缀。例如：
```
config {
type = "file"
file {
name = "/root/seata-config/file.conf"
}
}
```
期望的结果：配置文件能被加载

optimize: get config from file system even without file: prefix

---

rm-datasource/src/test/java/io/seata/rm/datasource/StatementProxyTest.java

optimize: optimize StatementProxyTest unit test

---

tm/src/test/java/io/seata/tm/TMClientTest.java

test: test case for tmClient
fix #194

test: test case for tmClient

---

CONTRIBUTING.md
changes/1.5.0.md
changes/en-us/1.5.0.md

add a change log file for the merge and author information record of each pr

optimize:  add the change records folder

---

.github/workflows/build.yml
changes/1.5.0.md
changes/en-us/1.5.0.md
rm-datasource/src/main/java/io/seata/rm/datasource/exec/MultiDeleteExecutor.java
rm-datasource/src/main/java/io/seata/rm/datasource/exec/MultiUpdateExecutor.java
rm-datasource/src/test/java/io/seata/rm/datasource/exec/MultiExecutorTest.java
script/server/config/file.conf

if multi sql contains order by or limit, throws NotSupportYetException to notic user

bugfix: forbidden use order by or limit in multi sql

---

README.md
changes/1.5.0.md
changes/en-us/1.5.0.md
server/pom.xml

optimize: optimize maven clean plugin to clear the distribution directory

optimize: optimize maven clean plugin to clear the distribution directory

---

changes/1.5.0.md
changes/en-us/1.5.0.md
rm-datasource/src/main/java/io/seata/rm/datasource/AbstractStatementProxy.java

去掉getGeneratedKeys的时候的缓存，让每次拿到的数据都是正确的主键。
fixes #3417

bugfix: fix getGeneratedKeys may get history pk

---

config/seata-config-core/src/main/java/io/seata/config/FileConfiguration.java

jar运行模式, 当第三方依赖分开打包时, this.getClass().getClassLoader()是null, 会报空指针异常
#3407

bugfix: run with jar file and not package third lib into jar file, this.getClass().getClassLoader() will be null

---

changes/1.5.0.md
changes/en-us/1.5.0.md
script/logstash/config/logstash-kafka.conf
script/logstash/config/logstash-logback.conf
script/logstash/logstash-logback.conf
server/pom.xml
server/src/main/java/io/seata/server/logging/logback/WhitespaceThrowableProxyConverter.java
server/src/main/resources/logback.xml
server/src/main/resources/logback/console-appender.xml
server/src/main/resources/logback/file-appender.xml
server/src/main/resources/logback/kafka-appender.xml
server/src/main/resources/logback/logstash-appender.xml

feature: send the `seata-server` log to `logstash` or `kafka`.
新功能：将`seata-server`的日志推送到`logstash`或`kafka`中，再存入`elasticsearch`中。（默认情况下，该功能处于关闭状态。需要用户自己修改`logback.xml`。）

feature: send the `seata-server` log to `logstash` or `kafka`

---

discovery/seata-discovery-nacos/src/main/java/io/seata/discovery/registry/nacos/NacosRegistryServiceImpl.java

移除`NacosRegistryServiceImpl`类中重复的`validAddress`方法，保持和其他`RegistryService`实现一样，使用`NetUtil.validAddress`方法。

optimize: remove duplicate validAddress code

---

changes/1.5.0.md
changes/en-us/1.5.0.md
rm-datasource/src/main/java/io/seata/rm/datasource/exec/MultiExecutor.java
rm-datasource/src/main/java/io/seata/rm/datasource/xa/ExecuteTemplateXA.java

I optimized some of the code: String comparison uses equalsIgnoreCase()

optimize: String comparison uses equalsIgnoreCase()

---

changes/1.5.0.md
changes/en-us/1.5.0.md
spring/src/main/java/io/seata/spring/annotation/GlobalTransactionScanner.java

optimize: remove useless if judgments.

---

config/seata-config-consul/src/main/java/io/seata/config/consul/ConsulConfiguration.java
discovery/seata-discovery-consul/src/main/java/io/seata/discovery/registry/consul/ConsulRegistryServiceImpl.java
script/client/conf/registry.conf
script/client/spring/application.properties
script/client/spring/application.yml
seata-spring-boot-starter/src/main/java/io/seata/spring/boot/autoconfigure/properties/config/ConfigConsulProperties.java
seata-spring-boot-starter/src/main/java/io/seata/spring/boot/autoconfigure/properties/registry/RegistryConsulProperties.java
server/src/main/resources/registry.conf

feature: add acl-token  for consul

---

changes/1.5.0.md
changes/en-us/1.5.0.md
test/src/test/java/io/seata/saga/engine/mock/MockGlobalTransaction.java
tm/src/main/java/io/seata/tm/api/DefaultGlobalTransaction.java
tm/src/main/java/io/seata/tm/api/GlobalTransaction.java

optimize: added interface to get current transaction role

---

changes/1.5.0.md
changes/en-us/1.5.0.md
rm-datasource/src/main/java/io/seata/rm/datasource/undo/AbstractUndoExecutor.java
rm-datasource/src/main/java/io/seata/rm/datasource/undo/mysql/MySQLUndoLogManager.java
rm-datasource/src/main/java/io/seata/rm/datasource/undo/oracle/OracleUndoLogManager.java

使用setBytes代替setBlob，避免shardingjdbc 转成setObject，再由jdbc驱动调用toString导致插入的数据被修改
fixes #3541

bugfix: do not call setBlob to invalid the jdbc exception

---

changes/1.5.0.md
changes/en-us/1.5.0.md
server/src/main/java/io/seata/server/coordinator/DefaultCoordinator.java
server/src/main/java/io/seata/server/session/GlobalSession.java
server/src/main/java/io/seata/server/storage/db/session/DataBaseSessionManager.java
server/src/main/java/io/seata/server/storage/redis/session/RedisSessionManager.java

当 TC 驱动 RM 提交事务时，如果在 doGlobalCommit  时数据库宕机，异常被捕获，此时会将事务添加到retry 的 sessionMenager 中，等待 retry 定时任务来处理，但是由于数据库宕机，数据库中事务的状态无法被修改，一直保持 Commiting 状态。retry 定时任务将不会处理该状态的事务。
fixes #3558
参考了 `DefaultCoordinator#handleRetryRollbacking` 中的实现。
在`DefaultCoordinator#handleRetryCommitting` 中把 committing 状态的全局事务也查出来，然后判断是否是 isDeadSession 。判断依据是 `(System.currentTimeMillis() - beginTime) > (2 * 6000);`

bugfix: set time threshold for transactions in committing state

---

spring/src/main/java/io/seata/spring/annotation/datasource/DataSourceProxyHolder.java
spring/src/main/java/io/seata/spring/annotation/datasource/SeataAutoDataSourceProxyAdvice.java

#3567 
修复自动数据源代理 因 ConcurrentHashMap.computeIfAbsent 导致的死锁问题

bugfix: DataSourceProxyHolder#putDataSource deadlock

---

changes/1.5.0.md
changes/en-us/1.5.0.md
rm-datasource/src/main/java/io/seata/rm/datasource/exec/mysql/MySQLInsertExecutor.java
rm-datasource/src/test/java/io/seata/rm/datasource/exec/MySQLInsertExecutorTest.java

MySQL插入的时候，如果getGeneratedKeys无法获取到主键，并且是批量插入的时候，原本的逻辑只能回滚第一条插入的数据，参考MySQL的jdbc驱动的StatementImpl的实现，在业务层进行自增长，保证回滚的时候可以回滚全部的数据。

optimize: optimize the get pks by auto when auto generated keys is false

---

changes/1.5.0.md
changes/en-us/1.5.0.md
common/src/test/java/io/seata/common/util/StringUtilsTest.java

**Problem:**
The Exception Handling test smell occurs when the test outcome is manually determined through pass or fail method calls, dependent on the production method throwing an exception, generally inside a try/catch block. This refactoring proposal aims to make the exception catching a responsibility of the test framework, which is already provided by its API. Also, without using try/catch blocks, tests can be more straightforward and possibly more comprehensible and maintainable.
**Solution:**
We propose using JUnit's exception handling to automatically pass/fail the test instead of writing custom exception handling code. In this particular case, we added the possibly throwable object to the test method signature and removed the redundant `fail` method call and message.
**Result:** …

optimize: Changed exception check by JUnit API usage

---

changes/1.5.0.md
changes/en-us/1.5.0.md
saga/seata-saga-engine/src/main/java/io/seata/saga/engine/impl/ProcessCtrlStateMachineEngine.java

根据FindBugs插件提示，找到的可能会导致NPE的BUG。原代码行172行。

bugfix: fix the possible NPE

---

changes/1.5.0.md
changes/en-us/1.5.0.md
server/src/test/java/io/seata/server/event/DefaultCoreForEventBusTest.java

单独测试DefaultCoreForEventBusTest#test时并不会出现,当与coordinator目录下的其它单元测试一并测试时,由于其中也存在需要异步提交的事务单测,导致GlobalTransactionEventSubscriber中的processGlobalTransactionEvent会进入多次相同的事务状态更改通知,导致单测无法通过
目前有2个修复方案:
1.如上面说的sleep,比较粗暴,但是能解决
2.Assertions.assertEquals强行要求了事务状态变更只能1次的通知,我觉得只要不是null就可以接受了
pr中采用方案1
理由:方案一虽然粗暴但是不会改变此单测的目的,而方案二的话就把结果改变了

bugfix: fixed bugs in EventBus unit tests

---

changes/1.5.0.md
changes/en-us/1.5.0.md
seata-spring-boot-starter/src/main/java/io/seata/spring/boot/autoconfigure/StarterConstants.java
seata-spring-boot-starter/src/main/java/io/seata/spring/boot/autoconfigure/properties/registry/LoadBalanceProperties.java
seata-spring-boot-starter/src/main/resources/META-INF/additional-spring-configuration-metadata.json

optimize: make `LoadBalanceProperties` compatible with `spring-boot:2.x` and above.
优化：使`LoadBalanceProperties`与`spring-boot:2.x`及以上版本兼容。
原因：springboot从2.x开始，强制要求`@ConfigurationProperties`的prefix属性必须使用kebab-case格式。不能使用驼峰格式。
错误信息如下：
```
***************************
APPLICATION FAILED TO START
***************************
Description:
Configuration property name 'seata.client.loadBalance' is not valid:
Invalid characters: 'B'
Bean: loadBalanceProperties
Reason: Canonical names should be kebab-case ('-' separated), lowercase alpha-numeric characters and must start with a letter
Action:
Modify 'seata.client.loadBalance' so that it conforms to the canonical names requirements.
```

optimize: make `LoadBalanceProperties` compatible with `spring-boot:2.x` and above

---

changes/1.5.0.md
changes/en-us/1.5.0.md
script/config-center/nacos/nacos-config.py

optimize: optimize nacos-config.py parameter

---

changes/1.5.0.md
changes/en-us/1.5.0.md
sqlparser/seata-sqlparser-druid/src/main/java/io/seata/sqlparser/druid/mysql/MySQLDeleteRecognizer.java
sqlparser/seata-sqlparser-druid/src/main/java/io/seata/sqlparser/druid/mysql/MySQLUpdateRecognizer.java
sqlparser/seata-sqlparser-druid/src/main/java/io/seata/sqlparser/druid/oracle/OracleDeleteRecognizer.java
sqlparser/seata-sqlparser-druid/src/main/java/io/seata/sqlparser/druid/oracle/OracleUpdateRecognizer.java
sqlparser/seata-sqlparser-druid/src/main/java/io/seata/sqlparser/druid/postgresql/PostgresqlDeleteRecognizer.java
sqlparser/seata-sqlparser-druid/src/main/java/io/seata/sqlparser/druid/postgresql/PostgresqlUpdateRecognizer.java

optimize: optimize the error of join table syntax

---

changes/1.5.0.md
changes/en-us/1.5.0.md
rm-datasource/src/main/java/io/seata/rm/datasource/ConnectionProxy.java
rm-datasource/src/main/java/io/seata/rm/datasource/exec/AbstractDMLBaseExecutor.java
rm-datasource/src/test/java/io/seata/rm/datasource/ConnectionProxyTest.java

Reverts seata/seata#3133
temporarily removed and will  be  merged in 1.5.0

revert : fix the case that could not retry acquire global lock

---

all/pom.xml
bom/pom.xml
changes/1.5.0.md
changes/en-us/1.5.0.md
pom.xml

gpg key  out of date,  re-generate

maven: update gpg key

---

changes/1.5.0.md
changes/en-us/1.5.0.md
seata-spring-boot-starter/src/test/java/io/seata/spring/boot/autoconfigure/RedisAutoInjectionTypeConvertTest.java

optimize: fix typo, applicationContex to applicationContext

---

changes/1.5.0.md
changes/en-us/1.5.0.md
core/src/main/java/io/seata/core/rpc/netty/RmNettyRemotingClient.java

bugfix: fix some comments

---

changes/1.5.0.md
changes/en-us/1.5.0.md
config/seata-config-core/src/main/java/io/seata/config/file/YamlFileConfig.java
integration/http/src/main/java/io/seata/integration/http/AbstractHttpExecutor.java
rm-datasource/src/main/java/io/seata/rm/datasource/exec/BaseInsertExecutor.java
rm-datasource/src/main/java/io/seata/rm/datasource/exec/mysql/MySQLInsertOrUpdateExecutor.java
rm-datasource/src/main/java/io/seata/rm/datasource/undo/parser/JacksonUndoLogParser.java
saga/seata-saga-engine/src/main/java/io/seata/saga/engine/repo/impl/StateMachineRepositoryImpl.java
serializer/seata-serializer-seata/src/main/java/io/seata/serializer/seata/protocol/transaction/AbstractBranchEndRequestCodec.java
serializer/seata-serializer-seata/src/main/java/io/seata/serializer/seata/protocol/transaction/BranchRegisterRequestCodec.java
serializer/seata-serializer-seata/src/main/java/io/seata/serializer/seata/protocol/transaction/BranchReportRequestCodec.java
server/src/main/java/io/seata/server/storage/file/store/FileTransactionStoreManager.java

optimize: close the `Closeable` and optimize some code.
优化：关闭一些未关闭的对象。

optimize: close the `Closeable` and optimize some code

---

changes/1.5.0.md
changes/en-us/1.5.0.md
discovery/seata-discovery-consul/src/main/java/io/seata/discovery/registry/consul/ConsulRegistryServiceImpl.java

bugfix: consul not found tc cluster

---

changes/1.5.0.md
changes/en-us/1.5.0.md
discovery/seata-discovery-zk/src/main/java/io/seata/discovery/registry/zk/ZookeeperRegisterServiceImpl.java

optimize: optimize zk registry lookup performance
see detail #3498

optimize: optimize zk registry lookup performance

---

changes/1.5.0.md
changes/en-us/1.5.0.md
common/src/main/java/io/seata/common/util/CollectionUtils.java
common/src/main/java/io/seata/common/util/CycleDependencyHandler.java
common/src/main/java/io/seata/common/util/ReflectionUtil.java
common/src/main/java/io/seata/common/util/StringUtils.java
common/src/test/java/io/seata/common/util/CollectionUtilsTest.java
common/src/test/java/io/seata/common/util/StringUtilsTest.java
tcc/src/main/java/io/seata/rm/tcc/interceptor/ActionContextUtil.java

bugfix: fix StringUtils StackOverflowError.
fixed: #3826

bugfix: fix StringUtils StackOverflowError

---

changes/1.5.0.md
changes/en-us/1.5.0.md
ext/apm-seata-skywalking-plugin/pom.xml
ext/apm-seata-skywalking-plugin/src/main/java/io/seata/apm/skywalking/plugin/DefaultCoreDoGlobalCommitInterceptor.java
ext/apm-seata-skywalking-plugin/src/main/java/io/seata/apm/skywalking/plugin/NettyRemotingClientSendSyncInterceptor.java
ext/apm-seata-skywalking-plugin/src/main/java/io/seata/apm/skywalking/plugin/RemotingProcessorProcessInterceptor.java
ext/apm-seata-skywalking-plugin/src/main/java/io/seata/apm/skywalking/plugin/common/SWSeataConstants.java
ext/apm-seata-skywalking-plugin/src/main/java/io/seata/apm/skywalking/plugin/common/SWSeataUtils.java
ext/apm-seata-skywalking-plugin/src/main/java/io/seata/apm/skywalking/plugin/define/DefaultCoreInstrumentation.java
ext/apm-seata-skywalking-plugin/src/main/java/io/seata/apm/skywalking/plugin/define/RemotingProcessorInstrumentation.java
ext/apm-seata-skywalking-plugin/src/test/java/io/seata/apm/skywalking/plugin/common/SWSeataUtilsTest.java

fixed https://github.com/seata/seata/issues/3839

optimize: optimization `apm-skwalking` operation method to generate rules

---

core/src/main/java/io/seata/core/rpc/netty/AbstractNettyRemotingServer.java

optimize: invalid string concat.

optimize: invalid string concat

---

changes/1.5.0.md
changes/en-us/1.5.0.md
config/seata-config-core/src/main/java/io/seata/config/ConfigurationCache.java
config/seata-config-core/src/test/java/io.seata.config/FileConfigurationTest.java

bugfix: fix getConfig with different value return the first

bugfix: fix getConfig with different default value return the first

---

changes/1.5.0.md
changes/en-us/1.5.0.md
common/src/main/java/io/seata/common/loader/EnhancedServiceLoader.java
common/src/main/java/io/seata/common/loader/ExtensionDefinition.java

feature: support SPI unload

---

changes/1.5.0.md
changes/en-us/1.5.0.md
core/src/main/java/io/seata/core/rpc/netty/AbstractNettyRemoting.java

use System.currentTimeMillis() as id, and jstack dump to current folder.
fixes https://github.com/seata/seata/issues/3922

bugfix: use system time  and current folder to jstack

---

changes/1.5.0.md
changes/en-us/1.5.0.md
discovery/seata-discovery-redis/src/main/java/io/seata/discovery/registry/redis/RedisRegistryServiceImpl.java

Send redis command at one time using pipeline
fixes #3933.

optimize: Send redis command at one time using pipeline

---

changes/1.5.0.md
changes/en-us/1.5.0.md
server/src/main/java/io/seata/server/storage/redis/store/RedisTransactionStoreManager.java

fix the NPE of multi.exec
fixes #3996

bugfix:The NPE of jedis multi.exec

---

changes/1.5.0.md
changes/en-us/1.5.0.md
core/src/main/java/io/seata/core/rpc/netty/NettyClientChannelManager.java
core/src/main/java/io/seata/core/rpc/netty/TmNettyRemotingClient.java
discovery/seata-discovery-core/src/main/java/io/seata/discovery/registry/RegistryService.java
server/src/test/java/io/seata/server/coordinator/DefaultCoordinatorMetricsTest.java

optimize: optimize client channel alive check

---

changes/1.5.0.md
changes/en-us/1.5.0.md
config/seata-config-nacos/src/main/java/io/seata/config/nacos/NacosConfiguration.java
seata-spring-autoconfigure/seata-spring-autoconfigure-core/src/main/java/io/seata/spring/boot/autoconfigure/properties/config/ConfigApolloProperties.java
seata-spring-autoconfigure/seata-spring-autoconfigure-core/src/main/java/io/seata/spring/boot/autoconfigure/properties/config/ConfigConsulProperties.java
seata-spring-autoconfigure/seata-spring-autoconfigure-core/src/main/java/io/seata/spring/boot/autoconfigure/properties/config/ConfigEtcd3Properties.java
seata-spring-autoconfigure/seata-spring-autoconfigure-core/src/main/java/io/seata/spring/boot/autoconfigure/properties/config/ConfigNacosProperties.java
seata-spring-autoconfigure/seata-spring-autoconfigure-core/src/main/java/io/seata/spring/boot/autoconfigure/properties/config/ConfigZooKeeperProperties.java
seata-spring-autoconfigure/seata-spring-autoconfigure-core/src/test/java/io/seata/spring/boot/autoconfigure/BasePropertiesTest.java
seata-spring-autoconfigure/seata-spring-autoconfigure-core/src/test/java/io/seata/spring/boot/autoconfigure/CorePropertiesTest.java
seata-spring-autoconfigure/seata-spring-autoconfigure-core/src/test/java/io/seata/spring/boot/autoconfigure/properties/config/test/ApolloPropertiesTest.java
seata-spring-autoconfigure/seata-spring-autoconfigure-core/src/test/java/io/seata/spring/boot/autoconfigure/properties/config/test/ConfigPropertiesTest.java
seata-spring-autoconfigure/seata-spring-autoconfigure-core/src/test/java/io/seata/spring/boot/autoconfigure/properties/config/test/ConsulPropertiesTest.java
seata-spring-autoconfigure/seata-spring-autoconfigure-core/src/test/java/io/seata/spring/boot/autoconfigure/properties/config/test/CustomPropertiesTest.java
seata-spring-autoconfigure/seata-spring-autoconfigure-core/src/test/java/io/seata/spring/boot/autoconfigure/properties/config/test/Etcd3PropertiesTest.java
seata-spring-autoconfigure/seata-spring-autoconfigure-core/src/test/java/io/seata/spring/boot/autoconfigure/properties/config/test/FilePropertiesTest.java
seata-spring-autoconfigure/seata-spring-autoconfigure-core/src/test/java/io/seata/spring/boot/autoconfigure/properties/config/test/NacosPropertiesTest.java
seata-spring-autoconfigure/seata-spring-autoconfigure-core/src/test/java/io/seata/spring/boot/autoconfigure/properties/config/test/ZooKeeperPropertiesTest.java
server/src/main/java/io/seata/server/storage/redis/store/RedisTransactionStoreManager.java
server/src/main/resources/application.example.yml

optimize configuration  center
fix #4019

optimize: optimize Nacos, Consul, Zookeeper and Etcd3 configuration

---

changes/1.5.0.md
changes/en-us/1.5.0.md
integration/dubbo-alibaba/src/main/java/io/seata/integration/dubbo/alibaba/AlibabaDubboTransactionPropagationFilter.java
integration/dubbo/src/main/java/io/seata/integration/dubbo/ApacheDubboTransactionPropagationFilter.java

bugfix: remove dubbo PRC communication xid transmission.

---

changes/1.5.0.md
changes/en-us/1.5.0.md
integration/http/src/main/java/io/seata/integration/http/TransactionPropagationInterceptor.java
integration/http/src/main/java/io/seata/integration/http/XidResource.java

bugfix:RM fails to clear XID after throwing an exception after executing local transactions, resulting in the thread always binding the XID of the wrong request
fixes #4020.

bugfix: RM did not clear XID after the local transaction threw an exception

---

changes/1.5.0.md
changes/en-us/1.5.0.md
common/src/main/java/io/seata/common/loader/EnhancedServiceNotFoundException.java
config/seata-config-apollo/src/main/java/io/seata/config/apollo/ApolloConfiguration.java
config/seata-config-zk/src/main/java/io/seata/config/zk/ZookeeperConfiguration.java
discovery/seata-discovery-consul/src/main/java/io/seata/discovery/registry/consul/ConsulRegistryServiceImpl.java
discovery/seata-discovery-core/src/main/java/io/seata/discovery/loadbalance/ConsistentHashLoadBalance.java
discovery/seata-discovery-nacos/src/main/java/io/seata/discovery/registry/nacos/NacosRegistryServiceImpl.java
integration/http/src/main/java/io/seata/integration/http/AbstractHttpExecutor.java
rm-datasource/src/main/java/io/seata/rm/datasource/exec/BaseInsertExecutor.java
rm-datasource/src/main/java/io/seata/rm/datasource/exec/mysql/MySQLInsertExecutor.java
rm-datasource/src/main/java/io/seata/rm/datasource/exec/mysql/MySQLInsertOrUpdateExecutor.java
rm-datasource/src/main/java/io/seata/rm/datasource/undo/AbstractUndoExecutor.java
saga/seata-saga-engine/src/main/java/io/seata/saga/engine/impl/DefaultStateMachineConfig.java
saga/seata-saga-statelang/src/main/java/io/seata/saga/statelang/parser/utils/DesignerJsonTransformer.java
tm/src/main/java/io/seata/tm/api/DefaultGlobalTransaction.java

bugfix: fix potential database resource leak
fix #4024

bugfix: fix potential database resource leak

---

changes/1.5.0.md
changes/en-us/1.5.0.md
discovery/seata-discovery-core/src/main/java/io/seata/discovery/registry/RegistryFactory.java

resolve deadlock problems during project construction

bugfix: resolve deadlock problems during project construction

---

changes/1.5.0.md
changes/en-us/1.5.0.md
common/src/main/java/io/seata/common/DefaultValues.java
core/src/main/java/io/seata/core/constants/ConfigurationKeys.java
core/src/main/java/io/seata/core/rpc/RemotingClient.java
core/src/main/java/io/seata/core/rpc/netty/AbstractNettyRemotingClient.java
core/src/main/java/io/seata/core/rpc/netty/NettyClientConfig.java
core/src/main/java/io/seata/core/rpc/netty/RmNettyRemotingClient.java
core/src/main/java/io/seata/core/rpc/netty/TmNettyRemotingClient.java
script/client/conf/file.conf
script/client/spring/application.properties
script/client/spring/application.yml
script/config-center/config.txt
seata-spring-autoconfigure/seata-spring-autoconfigure-core/src/main/java/io/seata/spring/boot/autoconfigure/properties/TransportProperties.java
seata-spring-autoconfigure/seata-spring-autoconfigure-core/src/main/resources/META-INF/additional-spring-configuration-metadata.json

optimize: optimize client batch sending.

---

changes/1.5.0.md
changes/en-us/1.5.0.md
discovery/seata-discovery-core/src/main/java/io/seata/discovery/registry/RegistryHeartBeats.java
discovery/seata-discovery-redis/src/main/java/io/seata/discovery/registry/redis/RedisRegistryServiceImpl.java

correct  built-in properties for redis registry center
for example,
change `seata.registry.redis.test.on.borrow`  to `seata.registry.redis.test-on-borrow`
fixes #3704
I don't know how to do it
I change application.yml in server module , like this
```
seata:
......
registry:
type: redis
redis:
server-addr: localhost:6379
db: 0
password:
cluster: default
timeout: 0
```
then start ServerApplication. It works

bugfix: correct redis registry built-in properties

---

changes/1.5.0.md
changes/en-us/1.5.0.md
common/src/main/java/io/seata/common/util/ArrayUtils.java
common/src/main/java/io/seata/common/util/StringUtils.java
common/src/test/java/io/seata/common/util/StringUtilsTest.java

bugfix: fix `StringUtils.toString(obj)` throw `ClassCastException` when the obj is primitive data array.
BUG修复：修复 `StringUtils.toString(obj)` 当obj是基本数据数组时，抛出`ClassCastException`的问题。

bugfix: fix `StringUtils.toString(obj)` throw `ClassCastException` when the obj is primitive data array

---

changes/1.5.0.md
changes/en-us/1.5.0.md
server/src/main/java/io/seata/server/coordinator/DefaultCore.java

bugfix: the problem of accidentally releasing the global lock

---

core/src/main/java/io/seata/core/rpc/netty/TmNettyRemotingClient.java

bugfix: fix rpc tm request timeout.

---

changes/1.5.0.md
changes/en-us/1.5.0.md
server/src/main/java/io/seata/server/ServerApplicationListener.java

fix some code for "sessionMode" not execute problem.
if I config service-port , 
```
server:
service-port: 8091
```
the following code will not execute
```java
// Load by priority
System.setProperty("sessionMode",
environment.getProperty(SERVER_STORE_SESSION_MODE, environmentPreparedEvent.getEnvironment().getProperty(SERVER_STORE_MODE, "file")));
System.setProperty("lockMode",
environment.getProperty(SERVER_STORE_LOCK_MODE, environmentPreparedEvent.getEnvironment().getProperty(SERVER_STORE_MODE, "file")));
```
no
I don't know how to do it

bugfix: fix code for "sessionMode" not execute problem

---

changes/1.5.0.md
changes/en-us/1.5.0.md
rm-datasource/src/main/java/io/seata/rm/RMHandlerAT.java
rm-datasource/src/main/java/io/seata/rm/datasource/undo/AbstractUndoLogManager.java
rm-datasource/src/main/java/io/seata/rm/datasource/undo/UndoLogManager.java
rm-datasource/src/main/java/io/seata/rm/datasource/undo/oracle/OracleUndoLogManager.java
rm-datasource/src/test/java/io/seata/rm/RMHandlerATTest.java

when RM receive UndoLogDeleteRequest(send by TC), if user does not use AT mode at all(which mean their database does not have undo_log table), exception would occur(such as undo_log table doesn't existed~) and logger will print error info(which scares user~). Here, we check whether undo_log table exist before trying to delete undolog.

optimize: client check whether undolog table exist before cleaning undolog

---

changes/1.5.0.md
changes/en-us/1.5.0.md
seata-spring-autoconfigure/seata-spring-autoconfigure-client/src/main/java/io/seata/spring/boot/autoconfigure/properties/SpringCloudAlibabaConfiguration.java
seata-spring-autoconfigure/seata-spring-autoconfigure-core/src/main/java/io/seata/spring/boot/autoconfigure/provider/SpringBootConfigurationProvider.java
server/src/main/java/io/seata/server/lock/AbstractLockManager.java
server/src/main/java/io/seata/server/session/AbstractSessionManager.java
server/src/main/java/io/seata/server/transaction/at/ATCore.java

improve code quality
fixes #3690 
this is my first pull request，please

optimize: optimize partial code handling

---

changes/1.5.0.md
changes/en-us/1.5.0.md
seata-spring-autoconfigure/seata-spring-autoconfigure-core/src/main/java/io/seata/spring/boot/autoconfigure/provider/SpringBootConfigurationProvider.java
tcc/src/main/java/io/seata/rm/tcc/TCCFenceHandler.java
tcc/src/main/java/io/seata/rm/tcc/TCCResourceManager.java
tcc/src/main/java/io/seata/rm/tcc/constant/TCCFenceConstant.java
tcc/src/main/java/io/seata/rm/tcc/remoting/parser/LocalTCCRemotingParser.java
tcc/src/main/java/io/seata/rm/tcc/store/db/sql/TCCFenceStoreSqls.java
tcc/src/test/java/io/seata/rm/tcc/remoting/parser/LocalTCCRemotingParserTest.java

optimize tcc module code handling
fixes #3690

optimize: optimize tcc module code handling

---

changes/1.5.0.md
changes/en-us/1.5.0.md
common/src/main/java/io/seata/common/Constants.java
core/src/main/java/io/seata/core/lock/LocalDBLocker.java
core/src/main/java/io/seata/core/lock/Locker.java
core/src/main/java/io/seata/core/store/LockStore.java
rm-datasource/src/main/java/io/seata/rm/datasource/ConnectionContext.java
rm-datasource/src/main/java/io/seata/rm/datasource/ConnectionProxy.java
server/src/main/java/io/seata/server/lock/AbstractLockManager.java
server/src/main/java/io/seata/server/lock/LockManager.java
server/src/main/java/io/seata/server/session/BranchSession.java
server/src/main/java/io/seata/server/storage/db/lock/DataBaseDistributedLocker.java
server/src/main/java/io/seata/server/storage/db/lock/DataBaseLocker.java
server/src/main/java/io/seata/server/storage/db/lock/LockStoreDataBaseDAO.java
server/src/main/java/io/seata/server/storage/file/lock/FileLocker.java
server/src/main/java/io/seata/server/storage/redis/lock/RedisLocker.java
server/src/main/java/io/seata/server/transaction/at/ATCore.java

optimize: skip check lock when all the before image is empty

---

changes/1.5.0.md
changes/en-us/1.5.0.md
core/src/main/java/io/seata/core/store/db/sql/lock/AbstractLockStoreSql.java
core/src/main/java/io/seata/core/store/db/sql/lock/LockStoreSql.java
core/src/test/java/io/seata/core/store/db/sql/lock/LockStoreSqlFactoryTest.java
server/src/main/java/io/seata/server/storage/db/lock/LockStoreDataBaseDAO.java

register branch and release lock failed when the size of rows that modified is greater than 1000 in oracle
fixes #3946

bugfix:  row size gt 1000 cause error in oracle

---

changes/1.5.0.md
changes/en-us/1.5.0.md
server/src/main/java/io/seata/server/storage/redis/lock/RedisLocker.java

When the local transaction and the global transaction are enabled, the branch registration fails to acquire the global lock, the lock holder is in the second-stage rollback, and the branch registration fails to be retried quickly, because the retry with the local transaction does not release the database lock , resulting in a two-phase rollback wait. Therefore, if a global lock is found in the Rollbacking state, the fail-fast code is returned directly.
#4267

optimize: acquire lock return fail-fast code in redis-pipeline mode.

---

changes/1.5.0.md
changes/en-us/1.5.0.md
core/src/main/java/io/seata/core/constants/ConfigurationKeys.java
script/config-center/config.txt
seata-spring-autoconfigure/seata-spring-autoconfigure-core/src/main/java/io/seata/spring/boot/autoconfigure/StarterConstants.java
seata-spring-autoconfigure/seata-spring-autoconfigure-server/src/main/java/io/seata/spring/boot/autoconfigure/SeataServerEnvironmentPostProcessor.java
seata-spring-autoconfigure/seata-spring-autoconfigure-server/src/main/java/io/seata/spring/boot/autoconfigure/properties/server/session/SessionProperties.java
server/src/main/java/io/seata/server/coordinator/DefaultCoordinator.java
server/src/main/java/io/seata/server/coordinator/DefaultCore.java
server/src/main/java/io/seata/server/session/SessionHelper.java
server/src/main/java/io/seata/server/transaction/saga/SagaCore.java
server/src/main/resources/application.example.yml

When the global commit or rollback is performed, the branch transaction enters the thread pool for asynchronous deletion after the second-phase delivery is successful.
全局提交或回滚时，分支事务二阶段下发成功后进入线程池中异步删除。
fixes #3750 
先review方案
The transaction is committed and rolled back normally, the TM receives the response before the branch transaction is deleted, and the branch transaction is deleted after the asynchronous thread is executed.
正常提交和回滚事务，TM在分支事务删除前收到响应，异步线程执行后分支事务被删除。

optimize: Improve the performance of global commit and global rollback

---

changes/1.5.0.md
changes/en-us/1.5.0.md
rm-datasource/src/main/java/io/seata/rm/datasource/sql/struct/cache/PostgresqlTableMetaCache.java
rm-datasource/src/test/java/io/seata/rm/datasource/mock/MockConnection.java

如果SQL表名没有写明schema，使用connection获取当前连接的schema，防止不同schema下存在相同表而导致错误识别多主键
If the SQL table name does not specify schema, use connection to obtain the schema of the current connection to prevent the existence of the same table under different schemas and cause misidentification of multiple primary keys
fixes #3098

bugfix:Fix fetch PostgresqlTableMetaCache fail when the same table exists in different schemas

---

changes/1.5.0.md
changes/en-us/1.5.0.md
rm-datasource/src/main/java/io/seata/rm/datasource/DataSourceProxy.java
rm-datasource/src/main/java/io/seata/rm/datasource/exec/ExecuteTemplate.java
rm-datasource/src/test/java/io/seata/rm/datasource/exec/MariadbInsertExecutorTest.java
rm-datasource/src/test/java/io/seata/rm/datasource/exec/MySQLInsertExecutorTest.java
rm-datasource/src/test/java/io/seata/rm/datasource/mock/MockMariadbDataSource.java
server/src/main/java/io/seata/server/coordinator/DefaultCoordinator.java

bugfix: fixed inability to build Executor when using mariadb driver

---

changes/1.5.0.md
changes/en-us/1.5.0.md
common/src/main/java/io/seata/common/exception/DataAccessException.java
common/src/main/java/io/seata/common/exception/EurekaRegistryException.java
common/src/main/java/io/seata/common/exception/NotSupportYetException.java
common/src/main/java/io/seata/common/exception/RedisException.java
common/src/main/java/io/seata/common/exception/ShouldNeverHappenException.java
common/src/main/java/io/seata/common/exception/StoreException.java
common/src/test/java/io/seata/common/exception/DataAccessExceptionTest.java
common/src/test/java/io/seata/common/exception/EurekaRegistryExceptionTest.java
common/src/test/java/io/seata/common/exception/ShouldNeverHappenExceptionTest.java
common/src/test/java/io/seata/common/exception/StoreExceptionTest.java
core/src/main/java/io/seata/core/context/RootContext.java
rm-datasource/src/main/java/io/seata/rm/datasource/ConnectionContext.java
rm-datasource/src/main/java/io/seata/rm/datasource/ConnectionProxy.java
rm-datasource/src/main/java/io/seata/rm/datasource/DataSourceManager.java
rm-datasource/src/main/java/io/seata/rm/datasource/exec/BaseInsertExecutor.java
rm-datasource/src/main/java/io/seata/rm/datasource/exec/LockConflictException.java
rm-datasource/src/main/java/io/seata/rm/datasource/exec/mysql/MySQLInsertExecutor.java
rm-datasource/src/main/java/io/seata/rm/datasource/sql/struct/TableRecords.java
rm-datasource/src/main/java/io/seata/rm/datasource/undo/UndoExecutorFactory.java
rm-datasource/src/test/java/io/seata/rm/datasource/exec/AbstractDMLBaseExecutorTest.java
tcc/src/main/java/io/seata/rm/tcc/exception/TCCFenceException.java

optimize exceptions to make them friendly

optimize: optimize exceptions to make them friendly

---

LICENSE
console/pom.xml
console/src/main/java/io/seata/console/filter/JwtAuthenticationTokenFilter.java
console/src/main/java/io/seata/console/utils/JwtTokenUtils.java
console/src/main/java/io/seata/console/utils/Result.java
core/src/main/java/io/seata/core/rpc/netty/NettyServerBootstrap.java
metrics/seata-metrics-exporter-prometheus/src/main/java/io/seata/metrics/exporter/prometheus/PrometheusExporter.java
metrics/seata-metrics-exporter-prometheus/src/test/java/io/seata/metrics/exporter/prometheus/PrometheusExporterTest.java
server/src/main/java/io/seata/server/storage/file/store/FileTransactionStoreManager.java

optimize: optimize the log of the server and remove lombok
1. 优化Server端的日志
2. 移除 lombok
#4227 PR太大，慢慢拆分出来

optimize: optimize the log of the server and remove lombok

---

all/pom.xml
dependencies/pom.xml
integration/grpc/pom.xml
server/src/test/java/io/seata/server/coordinator/DefaultCoreTest.java
test/src/test/java/io/seata/common/SagaCostPrint.java
test/src/test/java/io/seata/saga/engine/StateMachineAsyncTests.java
test/src/test/java/io/seata/saga/engine/StateMachineTests.java
test/src/test/java/io/seata/saga/engine/db/StateMachineDBTests.java
test/src/test/java/io/seata/saga/engine/db/mockserver/StateMachineAsyncDBMockServerTests.java
test/src/test/java/io/seata/saga/engine/db/mockserver/StateMachineDBMockServerTests.java

1. 优化 `SAGA` 的测试用例，避免失败的测试用例不会记录cost日志。
2. `SAGA` 单测：禁用三个非常耗时的单测、以及两个经常出错的单测，并标记FIXME。
1. 修复 `DefaultCoreTest` 偶发的 `ConcurrentModificationException`
5个单测的代码变更行比较多，但实际上就是包装了一层日志打印，实际的测试代码并没有变更。建议在review界面勾选 `Hide whitespace` 后再开始review

optimize: disable `SAGA` tests

---

changes/1.5.0.md
changes/en-us/1.5.0.md
server/src/main/java/io/seata/server/coordinator/DefaultCoordinator.java

目前的实现中,在同步二阶段时不会进行删除全局事务为了避免db和redis下残留branchsession和lock所以进行了默认2分10秒延迟删除,但是file下globalsession是有锁的,不会出现这种残留情况,也就无需延迟,仅需异步删除即可,file的内存是寸土寸金应尽快删除,所以需要通过storemode判断处理
fixes #4399

optimize: file mode does not require lazy processing of sessions

---

changes/1.5.0.md
changes/en-us/1.5.0.md
server/src/main/java/io/seata/server/ParameterParser.java
server/src/main/java/io/seata/server/Server.java
server/src/main/java/io/seata/server/env/ContainerHelper.java
server/src/main/java/io/seata/server/env/PortHelper.java

bugfix: fix the invalid environment variable in container env

---

changes/1.5.0.md
changes/en-us/1.5.0.md
server/src/main/java/io/seata/server/console/impl/file/GlobalSessionFileServiceImpl.java
server/src/test/java/io/seata/server/session/FileSessionManagerTest.java

file模式下的global session查询接口，当未选中“包含分支事务”时，会导致global session也无法查询。
由于file模式的分支事务信息本身就在内存中，故在file模式下忽略此条件。

optimize: global session query in file mode

---

changes/1.5.0.md
changes/en-us/1.5.0.md
server/src/main/java/io/seata/server/coordinator/DefaultCore.java
server/src/test/java/io/seata/server/coordinator/DefaultCoreTest.java
server/src/test/java/io/seata/server/event/DefaultCoreForEventBusTest.java

…alSession
GlobalSession在延迟删除的情况下，由于提前设置了Rollbacked状态导致定时任务无法即时处理。目前放弃提前设置状态，改为由DefaultCore#doGlobalRollback的执行结果来确认是否返回Rollbacked状态
In the case of delayed deletion of GlobalSession, the scheduled task cannot be processed immediately because the Rollbacked state is set in advance. At present, the advance setting state is abandoned, and the execution result of DefaultCore#doGlobalRollback is used to confirm whether to return the Rollbacked state.

bugfix: fix GlobalSession cannot be cleared normally when delayed deletion is enabled

---

changes/1.5.0.md
changes/en-us/1.5.0.md
rm-datasource/src/main/java/io/seata/rm/datasource/undo/AbstractUndoExecutor.java

bugfix:fix type conversion error for mysql BIT(M) type

---

changes/1.5.0.md
changes/en-us/1.5.0.md
common/src/main/java/io/seata/common/ConfigurationKeys.java
config/seata-config-nacos/src/main/java/io/seata/config/nacos/NacosConfiguration.java
discovery/seata-discovery-nacos/src/main/java/io/seata/discovery/registry/nacos/NacosRegistryServiceImpl.java

optimize: optimize nacos config and naming properties 
- The problem that Seata cannot use the real registry when the registry of RPC or Rest services is not the same as Seata's and the service's registry uses the -D（-D tenant.id）startup parameter to specify the highest priority access for Nacos metadata.

optimize: optimize nacos config and naming properties 

---

changes/1.5.0.md
changes/en-us/1.5.0.md
server/src/main/java/io/seata/server/console/impl/db/BranchSessionDBServiceImpl.java
server/src/main/java/io/seata/server/console/impl/db/GlobalLockDBServiceImpl.java
server/src/main/java/io/seata/server/console/impl/db/GlobalSessionDBServiceImpl.java

optimize the way to get configuration in DB mode of console

optimize: optimize the way to get configuration in DB mode of console

---

changes/1.5.0.md
changes/en-us/1.5.0.md
rm-datasource/src/main/java/io/seata/rm/datasource/DataCompareUtils.java

Detail is in [issue 4443](https://github.com/seata/seata/issues/4443)
fixes #4443

bugfix:  fix fastjson serialization of time data types

---

changes/1.5.0.md
changes/en-us/1.5.0.md
core/src/main/java/io/seata/core/auth/AuthSigner.java
core/src/main/java/io/seata/core/auth/DefaultAuthSigner.java
core/src/main/java/io/seata/core/auth/RamSignAdapter.java
core/src/main/java/io/seata/core/protocol/RegisterTMRequest.java
core/src/main/java/io/seata/core/rpc/netty/TmNettyRemotingClient.java

use HmacSHA256 instead of HmacSHA1 for ram signature

optimize: use HmacSHA256 instead of HmacSHA1 for ram signature

---

README.md
all/pom.xml
build/pom.xml
changes/2.0.0.md
changes/en-us/2.0.0.md
core/src/main/java/io/seata/core/protocol/Version.java

bugfix: replace `flatten-maven-plugin` with `easyj-maven-plugin` to fix the conflict between `shade` and `flatten`
问题修复：使用 `easyj-maven-plugin` 插件代替 `flatten-maven-plugin` 插件，以修复 `shade` 插件与 `flatten` 插件不兼容的问题，导致`seata-all.pom` 中的 `${revision}` 并没有被替换为具体的版本号，导致应用端引用后打包失败。
另外，`easyj-maven-plugin` 插件还可以简化所有pom文件。
---
fixes #4618
---
`easyj-maven-plugin` 插件源码：https://github.com/easyj-projects/easyj/blob/develop/maven-plugin/

bugfix: replace `flatten-maven-plugin` with `easyj-maven-plugin` to fix the conflict between `shade` and `flatten`

---

changes/en-us/develop.md
changes/zh-cn/develop.md
core/src/main/java/io/seata/core/rpc/netty/NettyServerConfig.java

branchResultMessageExecutor只用来处理分支事务响应
coreSize和maxSize都改为2倍核心线程数

optimize: the thread pool size of branchResultMessageExecutor

---

changes/en-us/develop.md
changes/zh-cn/develop.md
core/src/main/java/io/seata/core/rpc/netty/AbstractNettyRemotingClient.java
core/src/main/java/io/seata/core/rpc/netty/RmNettyRemotingClient.java
core/src/main/java/io/seata/core/rpc/netty/TmNettyRemotingClient.java

fix key [transport.enableRmClientBatchSendRequest ] cache penetration if not configure in env or nacos seata.properties
fixes #4666

bugfix:fix key [transport.enableRmClientBatchSendRequest ] cache penetration

---

changes/en-us/develop.md
changes/zh-cn/develop.md
server/src/main/java/io/seata/server/storage/redis/store/RedisTransactionStoreManager.java

修复RedisTransactionStoreManager中遍历Map时修改，抛出ConcurrentModificationException的问题。
fixes: https://github.com/seata/seata/issues/4667

bugfix: fix the exception in RedisTransactionStoreManager

---

changes/en-us/develop.md
changes/zh-cn/develop.md
dependencies/pom.xml
server/pom.xml

optimize: upgrade logback dependency to 1.2.9

---

changes/en-us/develop.md
changes/zh-cn/develop.md
rm-datasource/src/main/java/io/seata/rm/datasource/AsyncWorker.java
server/src/main/java/io/seata/server/storage/file/store/FileTransactionStoreManager.java

fix UT failed in AsyncWorkerTest and LockManagerTest
fixes #4672 #4673

test: fix UT failed in AsyncWorkerTest and LockManagerTest

---

changes/en-us/develop.md
changes/zh-cn/develop.md
core/src/main/java/io/seata/core/protocol/Version.java
rm-datasource/src/main/java/io/seata/rm/BaseDataSourceResource.java
rm-datasource/src/main/java/io/seata/rm/datasource/xa/ConnectionProxyXA.java
rm-datasource/src/main/java/io/seata/rm/datasource/xa/DataSourceProxyXA.java
rm-datasource/src/main/java/io/seata/rm/datasource/xa/ResourceManagerXA.java

1.mysql8.0.29允许不同的连接进行二阶段的行为，因此在此版本下无需持有连接至二阶段
mariadb经测试无法如此，所以必须和低版本的mysql一致处理
2.抽离xa兜底断开物理连接的线程池构建，只有在需要hold连接至二阶段的哪些datasource存在在进行构建线程池和任务运行

optimize: mysql 8.0.29 not should be hold for connection

---

changes/en-us/develop.md
changes/zh-cn/develop.md
distribution/Dockerfile
distribution/bin/seata-server.sh

8u332-jre-slim 支持arm64与amd64
兼容脚本，docker必须在前台运行否者会宕掉，loader.path docker 启动位置不同需要改为绝对路径
fixes #4660 
fixes #4732

feature: dockerfile support arm64

---

changes/en-us/develop.md
changes/zh-cn/develop.md
seata-spring-autoconfigure/seata-spring-autoconfigure-core/src/main/resources/META-INF/additional-spring-configuration-metadata.json

bugfix: fix in high version springboot property not Standard

bugfix: fix in high version springboot property not resolved

---

changes/en-us/develop.md
changes/zh-cn/develop.md
rm-datasource/src/main/java/io/seata/rm/datasource/exec/BaseTransactionalExecutor.java

…nding
**rename "filedSequence" to "rowSequence" for better understanding**

optimize: rename variable "filedSequence" to "rowSequence" for better understanding

---

changes/en-us/develop.md
changes/zh-cn/develop.md
saga/seata-saga-statemachine-designer/README.md
saga/seata-saga-statemachine-designer/README.zh-CN.md
saga/seata-saga-statemachine-designer/index.html
saga/seata-saga-statemachine-designer/package-lock.json
saga/seata-saga-statemachine-designer/package.json

fix some security vulnerabilities in GGEditor
The original PR could not be merged due to a CLA problem with the BOT, but the content was verified, so a new PR was submitted to solve the problem.
fixes #4796  #4576 #4464 #4412
cd saga/seata-saga-statemachine-designer
npm install
npm start
visit: http://localhost:8080/#/
import json design
```
{
"nodes": [
{
"type": "node",
"size": "39*39",
"shape": "flow-circle",
"color": "red",
"label": "Catch",
"stateId": "Catch1",
"stateType": "Catch",
"x": 592,
"y": 590,
"id": "e5a3adea",
"index": 3
},
{
"type": "node",
"size": "72*72",
"shape": "flow-circle",
"color": "#FA8C16",
"label": "Start",
"stateId": "Start1",
"stateType": "Start",
"stateProps": {
"StateMachine": {
"Name": "",
"Comment": "",
"Version": …
```

security: fix some security vulnerabilities in GGEditor

---

changes/en-us/2.0.0.md
changes/en-us/develop.md
changes/zh-cn/develop.md
spring/src/main/java/io/seata/spring/annotation/GlobalTransactionalInterceptor.java

自动降级如果一开始为false，运行中也无法通过修改配置来动态开启
fixes #4491

optimize: auto degrade unable dynamic configure

---

changes/en-us/develop.md
changes/zh-cn/develop.md
common/src/main/java/io/seata/common/ConfigurationKeys.java
seata-spring-autoconfigure/seata-spring-autoconfigure-server/src/main/java/io/seata/spring/boot/autoconfigure/properties/server/ServerRecoveryProperties.java
seata-spring-autoconfigure/seata-spring-autoconfigure-server/src/test/java/io/seata/spring/boot/autoconfigure/ServerPropertiesTest.java
server/src/main/java/io/seata/server/coordinator/DefaultCoordinator.java
server/src/main/resources/application.example.yml

optimize: fix failed to get server recovery properties

---

changes/en-us/develop.md
changes/zh-cn/develop.md
saga/seata-saga-engine/src/main/java/io/seata/saga/engine/pcext/interceptors/ServiceTaskHandlerInterceptor.java

output 表达式错误时，抛出期望的异常。而不是空指针
fixes #4948

bugfix: output expression incorrectly throws npe

---

changes/en-us/develop.md
changes/zh-cn/develop.md
dependencies/pom.xml
rm-datasource/src/main/java/io/seata/rm/datasource/undo/parser/KryoSerializerFactory.java
serializer/seata-serializer-kryo/src/main/java/io/seata/serializer/kryo/KryoSerializerFactory.java

升级 kryo依赖到5.X 4.X于2018年停止维护了
fixes https://github.com/seata/seata/issues/4961

feature: support kryo 5.3.0

---

changes/en-us/develop.md
changes/zh-cn/develop.md
rm-datasource/src/main/java/io/seata/rm/datasource/undo/parser/KryoSerializerFactory.java
serializer/seata-serializer-kryo/src/main/java/io/seata/serializer/kryo/KryoSerializerFactory.java

这是给dubbo提交pr的过程中遇到的问题 如下是kryo的官方回复
https://github.com/EsotericSoftware/kryo/issues/919

bugfix: kryo support circular reference

---

changes/en-us/develop.md
changes/zh-cn/develop.md
common/src/main/java/io/seata/common/exception/FrameworkErrorCode.java
tcc/src/main/java/io/seata/rm/tcc/TCCFenceHandler.java

RecordNotExists should be used when TCC fence records do not exist

optimize: optimize tcc fence record not exists errMessage

---

changes/en-us/develop.md
changes/zh-cn/develop.md
core/src/main/java/io/seata/core/protocol/Version.java
rm-datasource/src/main/java/io/seata/rm/datasource/DataSourceProxy.java
rm-datasource/src/main/java/io/seata/rm/datasource/exec/AbstractDMLBaseExecutor.java
rm-datasource/src/main/java/io/seata/rm/datasource/exec/mysql/MySQLUpdateJoinExecutor.java

bugfix: duplicate image row for update join

---

changes/en-us/develop.md
changes/zh-cn/develop.md
seata-spring-boot-starter/src/main/java/io/seata/spring/boot/autoconfigure/SeataSagaAutoConfiguration.java

删除SagaAsyncThreadPoolExecutorConfiguration类上的@EnableConfigurationProperties({SagaAsyncThreadPoolProperties.class})注解。
fixes #https://github.com/seata/seata/issues/5020

bugfix: remove `@EnableConfigurationProperties({SagaAsyncThreadPoolProperties.class})`

---

changes/en-us/develop.md
changes/zh-cn/develop.md
rm-datasource/src/main/java/io/seata/rm/datasource/exec/mysql/MySQLInsertOnDuplicateUpdateExecutor.java
rm-datasource/src/test/java/io/seata/rm/datasource/exec/MySQLInsertOnDuplicateUpdateExecutorTest.java

bugfix: insert value is all parsed as string in insert on duplicate 

---

.github/workflows/build.yml
build/pom.xml
dependencies/pom.xml
discovery/seata-discovery-etcd3/src/test/java/io/seata/discovery/registry/etcd/EtcdRegistryServiceImplTest.java
integration/grpc/pom.xml
serializer/seata-serializer-protobuf/pom.xml

Modified file  **.github/workflows/test.yml**, **dependencies/pom.xml**, **discovery/seata-discovery-etcd3/pom.xml**, **discovery/seata-discovery-etcd3/src/test/java/io/seata/discovery/registry/etcd/EtcdRegistryServiceImplTest.java**, i**ntegration/grpc/pom.xml** and **serializer/seata-serializer-protobuf/pom.xml** for arm64 binary
**Signed-off-by:** odidev <odidev@puresoftware.com>

optimize: require ARM64 binary

---

changes/en-us/develop.md
changes/zh-cn/develop.md
rm-datasource/src/main/java/io/seata/rm/datasource/exec/mysql/MySQLInsertOnDuplicateUpdateExecutor.java
rm-datasource/src/test/java/io/seata/rm/datasource/exec/MySQLInsertOnDuplicateUpdateExecutorTest.java

fix InsertOnDuplicateUpdateExecutor could not intercept the sql which has no primary and unique key
#5079

bugfix: fix could not intercept the sql witch has no primary and unique

---

.github/workflows/test.yml

Added arm64 test support in **.github/workflows/test.yml** file for running the test for arm64 platform.
Signed-off-by: [odidev@puresoftware.com](mailto:odidev@puresoftware.com)

test: test support for arm64

---

changes/en-us/develop.md
changes/zh-cn/develop.md
rm-datasource/src/main/java/io/seata/rm/datasource/exec/BaseTransactionalExecutor.java
rm-datasource/src/main/java/io/seata/rm/datasource/exec/mysql/MySQLUpdateJoinExecutor.java
sqlparser/seata-sqlparser-core/src/main/java/io/seata/sqlparser/JoinRecognizer.java
sqlparser/seata-sqlparser-druid/src/main/java/io/seata/sqlparser/druid/mysql/BaseMySQLRecognizer.java
sqlparser/seata-sqlparser-druid/src/main/java/io/seata/sqlparser/druid/mysql/MySQLUpdateRecognizer.java

bugfix: update join condition placeholder param error

---

changes/en-us/develop.md
changes/zh-cn/develop.md
seata-spring-autoconfigure/seata-spring-autoconfigure-client/src/main/java/io/seata/spring/boot/autoconfigure/SeataTCCFenceAutoConfiguration.java

This PR is used to ensure springboot create correct transaction manager for different ORM framework.
The original code shows that this configuration SeataTCCFenceAutoConfiguration must be executed after DataSourceTransactionManagerAutoConfiguration, but for springboot, different transaction manager for different ORM framework. this  DataSourceTransactionManagerAutoConfiguration will create DataSourceTransactionManager which works for jdbc related ORM, not work for JPA.
- JPA: JpaTransactionManager
- Hibernate: HibernateTransactionManager
- JDBC: DataSourceTransactionManager (actually the configuration DataSourceTransactionManagerAutoConfiguration is implemented with Ordered.LOWEST_PRECEDENCE)
Removed this config. It will be work because this config SeataTCCFenceAutoConfiguration already …

bugfix: fix when seata and jpa are used together, their AutoConfiguration order is incorrect

---

changes/en-us/develop.md
changes/zh-cn/develop.md
rm-datasource/src/main/java/io/seata/rm/datasource/ConnectionProxy.java
rm-datasource/src/test/java/io/seata/rm/datasource/ConnectionProxyTest.java

remove the druid dependency in ConnectionProxy

optimize: remove druid dependency in ConnectionProxy

---

changes/en-us/develop.md
changes/zh-cn/develop.md
config/seata-config-nacos/src/main/java/io/seata/config/nacos/NacosConfiguration.java
config/seata-config-nacos/src/test/java/io/seata/config/nacos/NacosConfigurationTest.java
config/seata-config-nacos/src/test/resources/registry.conf
discovery/seata-discovery-nacos/src/main/java/io/seata/discovery/registry/nacos/NacosRegistryServiceImpl.java
discovery/seata-discovery-nacos/src/test/java/io/seata/config/nacos/NacosRegistryServiceImplTest.java
discovery/seata-discovery-nacos/src/test/resources/registry.conf
script/client/conf/registry.conf
script/client/spring/application.properties
script/client/spring/application.yml
seata-spring-autoconfigure/seata-spring-autoconfigure-core/src/main/java/io/seata/spring/boot/autoconfigure/properties/config/ConfigNacosProperties.java
seata-spring-autoconfigure/seata-spring-autoconfigure-core/src/main/java/io/seata/spring/boot/autoconfigure/properties/registry/RegistryNacosProperties.java
server/src/main/resources/application.example.yml

Support passing contextPath parameter to Nacos client
fixes #5110 #5012
I provided  some screenshots of the test
Use nacos as discovery center and config center,and set the value of contextPath.

feature: support passing `contextPath` parameter to Nacos client

---

changes/en-us/develop.md
changes/zh-cn/develop.md
tcc/src/main/java/io/seata/rm/tcc/TCCFenceHandler.java
tcc/src/main/java/io/seata/rm/tcc/store/TCCFenceStore.java
tcc/src/main/java/io/seata/rm/tcc/store/db/TCCFenceStoreDataBaseDAO.java
tcc/src/main/java/io/seata/rm/tcc/store/db/sql/TCCFenceStoreSqls.java

支持oracle删除tccfence log。
在https://github.com/seata/seata/pull/4490 这个pr中对删除tccfence进行了优化，但是没考虑oracle的情况，所以用这个pr先支持oracle的删除。
特别说明：在4490pr里面新增了 query-by-date和delete-by-id之后，TCCFenceStoreDataBaseDAO .deleteTCCFenceDOByDate这个方法其实已经没有在使用，但由于初版的设计里对他也有改动，当时的pr里把deleteTCCFenceDOByDate里涉及的SQL语句和参数也增加了limit。这次把deleteTCCFenceDOByDate方法回滚还原回原来的样子直接支持oracle删除，而mysql等其他数据库由于不再使用这个dao方法也不会受影响。
fixes https://github.com/seata/seata/issues/5123

optimize: support oracle on delete tccfence logs 

---

build/pom.xml

…structing Processor object: Invalid index
2.5.14springboot在arm平台上打包时使skywalking模块打包失败，先进行降级处理
fixes #5162
```
[WARNING] The requested profile "dev" could not be activated because it does not exist.
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project apm-seata-skywalking-plugin: Compilation failure
[ERROR] 服务配置文件不正确, 或构造处理程序对象Invalid index时抛出异常错误
[ERROR] 
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project apm-seata-skywalking-plugin: Compilation failure
服务配置文件不正确, 或构造处理程序对象Invalid index时抛出异常错误
at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
at …
```

bugfix: fix bad service configuration file and compilation failure

---

changes/en-us/develop.md
changes/zh-cn/develop.md
seata-spring-boot-starter/src/main/java/io/seata/spring/boot/autoconfigure/SeataAutoConfiguration.java
seata-spring-boot-starter/src/main/java/io/seata/spring/boot/autoconfigure/SeataDataSourceAutoConfiguration.java

GlobalTransactionScanner,SeataAutoDataSourceProxyCreator declare @Bean methods as static
https://github.com/seata/seata/issues/5176

optimize: declare @Bean methods as static

---

dependencies/pom.xml

bugfix: fix issue#5174 , when seata.registry.type is eureka, ClassNotFoundException is reported after seata-server startup
bugfix: fix issue#5174 , when seata.registry.type is eureka, ClassNotFoundException is reported after seata-server startup
fixes #5174 
When seata.registry.type is eureka, you can update pom.xml , then start seata-server for verify.
update pom.xml ,then start seata-server for verify it

bugfix: fix ClassNotFoundException caused when server starts when using Eureka

---

changes/en-us/develop.md
changes/zh-cn/develop.md
common/src/main/java/io/seata/common/DefaultValues.java
core/src/main/java/io/seata/core/rpc/processor/server/ServerOnRequestProcessor.java
core/src/main/java/io/seata/core/store/db/AbstractDataSourceProvider.java
script/client/conf/file.conf
script/client/spring/application.properties
script/client/spring/application.yml
seata-spring-autoconfigure/seata-spring-autoconfigure-server/src/main/java/io/seata/spring/boot/autoconfigure/properties/server/store/StoreDBProperties.java
seata-spring-autoconfigure/seata-spring-autoconfigure-server/src/main/java/io/seata/spring/boot/autoconfigure/properties/server/store/StoreRedisProperties.java
server/src/main/java/io/seata/server/storage/db/store/DataBaseTransactionStoreManager.java
server/src/main/java/io/seata/server/storage/redis/JedisPooledFactory.java
server/src/main/java/io/seata/server/storage/redis/store/RedisTransactionStoreManager.java
server/src/main/resources/application.example.yml

optimize the default values for some switches

optimize: optimize the default values for some switches 

---

changes/en-us/develop.md
changes/zh-cn/develop.md
dependencies/pom.xml
script/server/db/oracle.sql

when create table 'lock_table' in Oracle, will report 'ORA-00907: missing right parenthesis'，because the DDL(field:status) has a worong keyword order in oracle, and DB will check it.

bugfix: wrong keyword order for oracle when creating a table

---

changes/en-us/develop.md
changes/zh-cn/develop.md
spring/src/main/java/io/seata/spring/util/SpringProxyUtils.java

Fix https://github.com/seata/seata/issues/5200

bugfix: Use Proxy.getInvocationHandler instead of reflection

---

changes/en-us/develop.md
changes/zh-cn/develop.md
script/server/db/oracle.sql

bugfix: oracle initialize script index_name is duplicate

---

changes/en-us/develop.md
changes/zh-cn/develop.md
server/src/main/java/io/seata/server/transaction/at/ATCore.java
spring/src/main/java/io/seata/spring/annotation/GlobalTransactionalInterceptor.java

optimize: Throwable#getCause once more

---

changes/en-us/develop.md
changes/zh-cn/develop.md
distribution/pom.xml

Add apm-seata-skywalking-plugin to the dependency of distribution module，so it can be built before distribution.
The reason is, we have to build ext/apm-skywalking before we move this folder to distribution folder.
fix #5245 
There is no code change.
mvn -Prelease-seata -Dmaven.test.skip=true clean install -U
We can see apm-seata-skywalking-plugin build before seata-distribution.
And we can see /ext folder under distribution/target/seata-server-1.6.1/seata

bugfix: fix the incomplete dependency of distribution module

---

build/pom.xml

引用高版本的 `protobuf-maven-plugin` 插件时，编译会出现命令行过长导致编译失败（Window x86环境下）
目前添加 `useArgumentFile` 配置项来兼容，配置项说明：
> https://www.xolstice.org/protobuf-maven-plugin/compile-mojo.html
If set to `true`, all command line arguments to protoc will be written to a file, and only a path to that file will be passed to protoc on the command line. This helps prevent Command line is too long errors when the number of .proto files is large.NOTE: This is only supported for protoc 3.5.0 and higher.
[<useArgumentFile>](https://www.xolstice.org/protobuf-maven-plugin/compile-mojo.html#useArgumentFile)	boolean	0.6.0	If set to true, all command line arguments to protoc will be written to a file, and only a path to that file will be passed to protoc on the command line. This helps prevent Command line is too long errors …

optimize:fix the problem that protobuf compilation fails

---

build/pom.xml
changes/en-us/develop.md
changes/zh-cn/develop.md

引用高版本的 `protobuf-maven-plugin` 插件时，编译会出现命令行过长导致编译失败（Window x86环境下）
目前添加 `useArgumentFile` 配置项来兼容，配置项说明：
> https://www.xolstice.org/protobuf-maven-plugin/compile-mojo.html
If set to `true`, all command line arguments to protoc will be written to a file, and only a path to that file will be passed to protoc on the command line. This helps prevent Command line is too long errors when the number of .proto files is large.NOTE: This is only supported for protoc 3.5.0 and higher.
[<useArgumentFile>](https://www.xolstice.org/protobuf-maven-plugin/compile-mojo.html#useArgumentFile)	boolean	0.6.0	If set to true, all command line arguments to protoc will be written to a file, and only a path to that file will be passed to protoc on the command line. This helps prevent Command line is too long errors …

optimize: fix the problem that protobuf compilation fails（for dev）

---

changes/en-us/2.0.0.md
changes/zh-cn/2.0.0.md
server/src/main/java/io/seata/server/console/impl/file/GlobalLockFileServiceImpl.java
server/src/test/java/io/seata/server/lock/LockManagerTest.java

bugfix: the console has queried the released lock

---

changes/en-us/develop.md
changes/zh-cn/develop.md
core/src/main/java/io/seata/core/rpc/processor/server/ServerOnRequestProcessor.java

bugfix: parallel request handle throw IndexOutOfBoundsException

---

changes/en-us/2.0.0.md
changes/zh-cn/2.0.0.md
rm-datasource/src/main/java/io/seata/rm/datasource/undo/mysql/MySQLUndoUpdateExecutor.java
server/src/main/java/io/seata/server/coordinator/DefaultCoordinator.java

1. Correct the comment on MySQLUndoUpdateExecutor#UPDATE_SQL_TEMPLATE (#5297)
2. https://github.com/seata/seata/issues/5295
fixes #5297
fixes #5295

bugfix: don't remove GlobalSession when retry rollback or retry commit timeout 

---

changes/en-us/develop.md
changes/zh-cn/develop.md
rm-datasource/src/main/java/io/seata/rm/datasource/exec/UpdateExecutor.java
rm-datasource/src/main/java/io/seata/rm/datasource/exec/mysql/MySQLUpdateJoinExecutor.java
rm-datasource/src/test/java/io/seata/rm/datasource/exec/UpdateExecutorTest.java

bugfix: that keywords don't add escaped characters

---

changes/en-us/develop.md
changes/zh-cn/develop.md
rm-datasource/src/main/java/io/seata/rm/datasource/exec/UpdateExecutor.java
rm-datasource/src/main/java/io/seata/rm/datasource/undo/mysql/MySQLUndoUpdateExecutor.java
server/src/main/java/io/seata/server/storage/file/session/FileSessionManager.java

bugfix: remove RollbackRetryTimeout sessions during in file storage recover
fix #5299

bugfix: remove RollbackRetryTimeout sessions during in file storage recover

---

changes/en-us/develop.md
changes/zh-cn/develop.md
server/src/main/java/io/seata/server/coordinator/DefaultCoordinator.java

在全局事务超时日志中添加全局事务开始时间及发起全局回滚的当前时间，方便用户排查是否应用是否存在异常以及优化相关参数配置

optimize: add time info for global transaction timeout log

---

changes/en-us/develop.md
changes/zh-cn/develop.md
dependencies/pom.xml

fix multi spring version test failed
fix #5381   
fix #5172

test: fix multi spring version test failed

---

build/pom.xml
core/pom.xml
core/src/main/java/io/seata/core/protocol/Version.java
core/src/main/java/io/seata/core/protocol/VersionInfo.java.template
core/src/test/java/io/seata/core/protocol/VersionTest.java

optimize: Unified version.
优化：统一维护版本号到`<revision>`。`Version.java` 文件中不需要再修改版本号了。

optimize: unified project version

---

changes/en-us/2.0.0.md
changes/zh-cn/2.0.0.md
core/src/main/java/io/seata/core/event/ExceptionEvent.java
metrics/seata-metrics-api/src/main/java/io/seata/metrics/IdConstants.java
server/src/main/java/io/seata/server/logging/logback/appender/MetricLogbackAppender.java
server/src/main/java/io/seata/server/metrics/MeterIdConstants.java
server/src/main/java/io/seata/server/metrics/MetricsSubscriber.java
server/src/main/resources/logback-spring.xml
server/src/main/resources/logback/metric-appender.xml

新增logback的appender，appender并不会直接上报metric，只负责触发event。由metricsubscribe统一上报。
fixes https://github.com/seata/seata/issues/4586

feature : add TC exception log appender metric 

---

.github/workflows/build.yml
.github/workflows/publishes.yml
.github/workflows/test.yml
build/pom.xml
pom.xml

optimize: upgrade `easyj-maven-plugin` to `1.1.5` for support `maven 3.9.0`, and optimize github actions
由于近期github actions的部分虚拟机使用的是maven 3.9.0，所以要兼容一下。
1. upgrade `easyj-maven-plugin` to `1.1.5` for support `maven 3.9.0`
2. 优化github actions
3. github actions里，添加打印maven版本，用于参考。

optimize: upgrade easyj-maven-plugin to 1.1.5 for support maven 3.9.0

---

.github/workflows/build.yml
.github/workflows/publishes.yml
.github/workflows/test.yml
build/pom.xml
common/src/test/java/io/seata/common/util/ReflectionUtilTest.java
console/pom.xml
pom.xml
server/pom.xml

optimize: publish images based on java `8`, `8-slim`, `17`, `17-slim`, see #5168
optimize: upgrade `easyj-maven-plugin` to `1.1.5` for support `maven-3.9.0` , see #5402

optimize: publish images based on java 8/17 and support maven-3.9.0

---

server/src/test/java/io/seata/server/session/GlobalSessionTest.java
server/src/test/java/io/seata/server/store/file/FileTransactionStoreManagerTest.java

由于时不时github action的ci跑测试用例的顺序变化,老是会出现各种各样测试用例间顺序变化造成的问题,这次问题就是因为单纯的加beforeall的FileTransactionStoreManagerTest ,没有注入applicationcontext,导致environment为npe,而sessionholder初始化需要config,这个config又是被springbootprovider代理,需要使用environment,导致了npe,以往这个测试用例并不是作为server侧第一跑的测试用例,所以在ServerApplicationListener的事件中已经对ObjectHolder赋值了environment,所以在以前就没有遇到这种情况.
目前把几个beforeall中带有sessionholder#init的地方都进行了修复
fixes #5429

bugfix: FileTransactionStoreManagerTest NPE

---

.github/workflows/build.yml
.github/workflows/codeql-analysis.yml
.github/workflows/license-checker.yaml
.github/workflows/publishes.yml
.github/workflows/test.yml

optimize: optimize github workflow

---

changes/en-us/2.0.0.md
changes/zh-cn/2.0.0.md
integration-tx-api/src/main/java/io/seata/integration/tx/api/interceptor/handler/GlobalTransactionalInterceptorHandler.java
integration-tx-api/src/main/java/io/seata/integration/tx/api/util/ClassUtils.java

fix the GlobalTransactional nullpointerexception issue.
fixes #5434

bugfix: the GlobalTransactional annotation npe issue.

---

changes/en-us/develop.md
changes/zh-cn/develop.md
spring/src/main/java/io/seata/spring/annotation/GlobalTransactionalInterceptor.java

bugfix: fix using @GlobalTransactional in provider  ShouldNverHappenException  thrown

---

changes/en-us/2.0.0.md
changes/zh-cn/2.0.0.md
core/src/main/java/io/seata/core/exception/TransactionExceptionCode.java
core/src/main/java/io/seata/core/model/GlobalStatus.java
server/src/main/java/io/seata/server/session/GlobalSession.java
tm/src/main/java/io/seata/tm/api/TransactionalTemplate.java

fix finished transaction swallows exception when committing
fix #5468

bugfix: fix finished transaction swallows exception when committing

---

core/src/main/java/io/seata/core/store/LogStore.java
core/src/main/java/io/seata/core/store/db/sql/log/LogStoreSqls.java
core/src/main/java/io/seata/core/store/db/sql/log/MysqlLogStoreSqls.java
core/src/main/java/io/seata/core/store/db/sql/log/OracleLogStoreSqls.java
core/src/main/java/io/seata/core/store/db/sql/log/PostgresqlLogStoreSqls.java
server/src/main/java/io/seata/server/coordinator/DefaultCore.java
server/src/main/java/io/seata/server/session/AbstractSessionManager.java
server/src/main/java/io/seata/server/session/GlobalSession.java
server/src/main/java/io/seata/server/storage/db/session/DataBaseSessionManager.java
server/src/main/java/io/seata/server/storage/db/store/DataBaseTransactionStoreManager.java
server/src/main/java/io/seata/server/storage/db/store/LogStoreDataBaseDAO.java
server/src/test/java/io/seata/server/session/db/DataBaseSessionManagerTest.java
server/src/test/java/io/seata/server/store/db/LogStoreDataBaseDAOTest.java

更新globalstatus的时候采用线程安全的方式，阻止预期状态不匹配的操作继续执行。
目前的思路是：rollback和commit都用乐观锁方式去更新globalsession的status，更新成功的会往下执行。没有更新成功的会遇到异常而中断。
传参expected status方式使用threadlocal
以下两个pr优化了之后，这个pr可以简化
https://github.com/seata/seata/pull/4858
https://github.com/seata/seata/pull/4881
原pr关闭
https://github.com/seata/seata/pull/4383
fixes https://github.com/seata/seata/issues/4372

optimize : change transaction state thread-safe in db mode

---

common/src/main/java/io/seata/common/util/DateUtil.java
common/src/test/java/io/seata/common/util/DateUtilTest.java
rm-datasource/src/main/java/io/seata/rm/RMHandlerAT.java
rm-datasource/src/main/java/io/seata/rm/datasource/undo/oracle/OracleUndoLogManager.java
script/client/at/db/mysql.sql
script/client/at/db/oracle.sql
script/client/at/db/postgresql.sql

fix the full table scan issue with 'setDate' condition in Oracle 10g

bugfix: fix the full table scan issue with 'setDate' condition in Oracle 10g

---

changes/en-us/develop.md
changes/zh-cn/develop.md
rm-datasource/src/main/java/io/seata/rm/datasource/undo/AbstractUndoExecutor.java
rm-datasource/src/main/java/io/seata/rm/datasource/undo/AbstractUndoLogManager.java
rm-datasource/src/test/java/io/seata/rm/datasource/undo/BaseH2Test.java
rm-datasource/src/test/java/io/seata/rm/datasource/undo/UndoExecutorTest.java

bugfix: fix mariadb rollback failed

---

changes/en-us/2.0.0.md
changes/zh-cn/2.0.0.md
common/src/main/java/io/seata/common/Constants.java
integration-tx-api/src/main/java/io/seata/integration/tx/api/fence/config/CommonFenceConfig.java
seata-spring-autoconfigure/seata-spring-autoconfigure-client/src/main/java/io/seata/spring/boot/autoconfigure/SeataSpringFenceAutoConfiguration.java
seata-spring-autoconfigure/seata-spring-autoconfigure-client/src/main/resources/META-INF/spring.factories
seata-spring-autoconfigure/seata-spring-autoconfigure-client/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
spring/src/main/java/io/seata/rm/fence/SpringFenceConfig.java
tcc/src/main/java/io/seata/rm/tcc/interceptor/TccActionInterceptorHandler.java

…nce is set to true
优化 TCC fence log 表的清理定时任务开启时机，只有当 `useTCCFence = true` 时，才进行初始化
fixes #5554

optimize: The common fence clean task is only initiated when useTCCFence is set to true

---

changes/en-us/2.0.0.md
changes/zh-cn/2.0.0.md
integration/grpc/src/main/java/io/seata/integration/grpc/interceptor/server/ServerListenerProxy.java

bugfix: grpc interceptor xid unbinding problem

---

changes/en-us/2.0.0.md
changes/zh-cn/2.0.0.md
tm/src/main/java/io/seata/tm/api/DefaultGlobalTransaction.java
tm/src/main/java/io/seata/tm/api/TransactionalTemplate.java

在事务传播过程中，如果出现Participant的情况（比如required或者support的），就会加入已存在的事务，当前逻辑在这种情况的处理存在不完善。
- 大部分情况下，核心逻辑和主要的日志写在DefaultGlobalTransaction类中，而hook处理在TransactionalTemplate（比如begin的逻辑）由于role判断写在DefaultGlobalTransaction所以没问题
- 但对于commit和rollback，日志先写在了TransactionalTemplate，没有进行role判断，所以切面第二次进入切面后TransactionalTemplate里的逻辑先不管role就打印了日志，然后进行hook，等进入DefaultGlobalTransaction后又判断了role所以其实并没有执行真正的commit/rollback。
目前的改造方式
- 把这两个关键的日志移动回DefaultGlobalTransaction内部，也就是判断完role再打印
- 优化TransactionalTemplate，日志移除，并在switch阶段就把current transaction处理干净
- hook的逻辑没有发生变化，多次进入切面依然会多次执行
不足之处讨论
- hook多次执行：加入事务在DefaultGlobalTransaction内会直接返回，但hook会再次执行，逻辑上有点奇怪，以后的改造建议是participant的情况在TransactionalTemplate就跳过去，就像斌哥说的这种情况打个日志直接execute
- 兼容性顾虑：因为按现在的逻辑加入事务也会触发hook，如果我们真的改了，用户升级时是没有感知的，如果他之前真的依赖这个hook去做重要的事情，可能带来问题
- …

bugfix: fix log in participant transaction role

---

changes/en-us/2.0.0.md
changes/zh-cn/2.0.0.md
server/src/main/java/io/seata/server/session/GlobalSession.java
server/src/main/java/io/seata/server/storage/db/store/LogStoreDataBaseDAO.java

In the db mode, the `GlobalSession.asyncCommit` and `GlobalSession.queueToRetryCommit` always failed.
在DB模式下，`GlobalSession.asyncCommit` 和 `GlobalSession.queueToRetryCommit` 两个方法总是失败。
复现 `asyncCommit` 报错：一个全局事务可以异步全局提交，就会碰到该问题。比如：全部是AT分支。
复现 `queueToRetryCommit` 报错：可以在分支提交时，设置断点，故意把RM关掉，让一个分支提交失败，让全局事务进入异步重试提交。

bugfix: fix the `asyncCommit` and `queueToRetryCommit` always failed in db mode

---

changes/en-us/2.0.0.md
changes/zh-cn/2.0.0.md
server/src/main/java/io/seata/server/coordinator/DefaultCoordinator.java

…Committing thread
fix possible conflict between asyncCommitting thread and retryCommitting thread
重试线程需要对Commited状态的全局事务做重试提交时，应该先判断该全局事务是否是DeadSession。只有DeadSession状态的才能重试提交。避免和异步提交线程的删除全局事务逻辑发生并发冲突
fixes #5605 
Original test cases can be do

optimize: possible conflict between asyncCommitting thread and retryCommitting thread

---

changes/en-us/2.0.0.md
changes/zh-cn/2.0.0.md
common/src/main/java/io/seata/common/util/StringUtils.java
rm-datasource/src/main/java/io/seata/rm/datasource/sql/struct/ColumnMeta.java
rm-datasource/src/main/java/io/seata/rm/datasource/sql/struct/TableMeta.java
rm-datasource/src/main/java/io/seata/rm/datasource/sql/struct/cache/MysqlTableMetaCache.java
rm-datasource/src/main/java/io/seata/rm/datasource/sql/struct/cache/OracleTableMetaCache.java
rm-datasource/src/main/java/io/seata/rm/datasource/sql/struct/cache/PostgresqlTableMetaCache.java

support case-sensitive attributes for table and column metadata

optimize: support case-sensitive attributes for table and column metadata

---

changes/en-us/develop.md
changes/zh-cn/develop.md
script/client/at/db/oracle.sql
script/client/at/db/postgresql.sql

bugfix: fix oracle insert undolog failed
fix #5556

bugfix: fix oracle insert undolog failed

---

changes/en-us/develop.md
changes/zh-cn/develop.md
rm-datasource/src/main/java/io/seata/rm/datasource/xa/ConnectionProxyXA.java

bugfix: fix the timeout is null when the connectionProxyXA connection is reused

---

changes/en-us/develop.md
changes/zh-cn/develop.md
rm-datasource/src/main/java/io/seata/rm/datasource/sql/handler/mysql/MySQLEscapeHandler.java
rm-datasource/src/main/java/io/seata/rm/datasource/sql/handler/oracle/OracleEscapeHandler.java
rm-datasource/src/main/java/io/seata/rm/datasource/sql/handler/postgresql/PostgresqlEscapeHandler.java
sqlparser/seata-sqlparser-core/src/main/java/io/seata/sqlparser/EscapeHandler.java

optimize escape character for case of columnNames
规则：
1. 优先取用户SQL的update原始字段
2. 对于关注全列在SQL中不存在的字段去tableMeta
TODO: check primaryKey case sensitive
CREATE TABLE "CPS_BPM_INSTANCE_TASK" (   "ID" VARCHAR2(50BYTE) NOT NULL, "FLOW_TEMPLATE_ID" VARCHAR2(50BYTE) NOT NULL, "PROCESS_INSTANCE_ID" VARCHAR2(50BYTE) NOT NULL, "DEF_TASK_ID" VARCHAR2(50BYTE) NOT NULL, "SPEC_DATE" DATE, "SUPPOSE_CYCLE" NUMBER(3,0), "TASK_STATUS" VARCHAR2(10BYTE) NOT NULL, "LAST_SUPPOSE_TIME" DATE, "CREATED_BY" VARCHAR2(32BYTE) NOT NULL, "CREATION_DATE" DATE NOT NULL, "LAST_UPDATED_BY" VARCHAR2(32BYTE) NOT NULL, "LAST_UPDATE_DATE" DATE NOT NULL, "LAST_UPDATE_IP" VARCHAR2(20BYTE) NOT NULL, "VERSION" NUMBER(16,0) NOT NULL, "ORG_IDENTITY" VARCHAR2(32BYTE) NOT NULL);
COMMENT ON COLUMN "CPS_BPM_INSTANCE_TASK"."ID" IS '主键'; …

optimize: optimize escape character for case of columnNames

---

.github/workflows/license-checker.yaml

optimize license check actions

optimize: optimize license check actions

---

changes/en-us/develop.md
changes/zh-cn/develop.md
server/src/main/java/io/seata/server/storage/db/lock/DataBaseDistributedLocker.java

optimize distributed lock log
fix  #5684

optimize: optimize distributed lock log

---

changes/en-us/2.0.0.md
changes/zh-cn/2.0.0.md
rm-datasource/src/main/java/io/seata/rm/datasource/sql/struct/TableRecords.java
sqlparser/seata-sqlparser-core/src/main/java/io/seata/sqlparser/struct/TableMeta.java

…ith the case in the table metadata, resulting in a rollback failure
修复：AT模式，在某些情况下，业务sql中主键字段名大小写与表元数据中的不一致，导致回滚失败
fixes #5734

bugfix: case of the pk col-name in the business sql is inconsistent with the case in the table metadata, resulting in a rollback failure

---

changes/en-us/develop.md
changes/zh-cn/develop.md
rm-datasource/src/main/java/io/seata/rm/datasource/sql/struct/cache/MysqlTableMetaCache.java
rm-datasource/src/main/java/io/seata/rm/datasource/sql/struct/cache/OracleTableMetaCache.java
rm-datasource/src/main/java/io/seata/rm/datasource/sql/struct/cache/PostgresqlTableMetaCache.java
rm-datasource/src/test/java/io/seata/rm/datasource/sql/struct/cache/MysqlTableMetaCacheTest.java
sqlparser/seata-sqlparser-core/src/main/java/io/seata/sqlparser/struct/IndexMeta.java

在`TableMetaCache`中，某些`filed`如`CARDINALITY`与`MySQL`的`jdbc`中类型定义不一致，可能会导致`Integer`类型溢出，需要修改二者为一致类型。
Fixes #5761

bugfix: change some fields type of  TableMetaCache to avoid integer overflow

---

changes/en-us/2.0.0.md
changes/zh-cn/2.0.0.md
changes/zh-cn/develop.md
discovery/seata-discovery-redis/src/main/java/io/seata/discovery/registry/redis/RedisRegistryServiceImpl.java

解决redis作为注册中心时cluster自定义就会报错的BUG 【no available service found in cluster 'ordos_111.56.115.158', please make sure registry config correct and keep your seata server running】
没有
该问题无法添加测试用例
如何复现错误：
使用redis作为注册中心，且当server端和client端配置同样的cluster（非default）时，导致客户端一直报错（实际上我的cluster已经注册到了redis）
通过Debug发现：
无论在配置文件中指定什么cluster，以下代码中的CLUSTER_ADDRESS_MAP都会使用default作为键，而不是自定义的cluster
``` java
#310行
if (!newAddressSet.equals(CLUSTER_ADDRESS_MAP.get(clusterName))) {
CLUSTER_ADDRESS_MAP.put(clusterName, newAddressSet);
}
```
而获取配置信息的代码处是用自定义cluster而非default作为键
``` java
#253行
return new ArrayList<>(CLUSTER_ADDRESS_MAP.getOrDefault(clusterName, Collections.emptySet()));
```
以上代码出自io.seata.discovery.registry.redis.RedisRegistryServiceImpl文件

bugfix: cluster cannot be customized when redis serves as the registry

---

changes/en-us/develop.md
changes/zh-cn/develop.md
rm-datasource/src/test/java/io/seata/rm/datasource/ColumnUtilsTest.java
sqlparser/seata-sqlparser-core/src/main/java/io/seata/sqlparser/EscapeHandler.java

fix oracle column alias cannot find
cherry-pick #5785

bugfix: fix oracle column alias cannot find

---

.github/workflows/build.yml

optimize: fix codecov chart not display

---

.github/workflows/build.yml

optimize: fix codecov chart not display 

---

changes/en-us/2.0.0.md
changes/zh-cn/2.0.0.md
rm-datasource/src/main/java/io/seata/rm/datasource/xa/ConnectionProxyXA.java

修复bug #5832 。当XA分支事务回滚后，报告给TC，避免TC不知道重试回滚
fixes #5832

bugfix: fix TC retry rollback wrongly, after the XA transaction fail and rollback

---

build/pom.xml
changes/en-us/2.0.0.md
changes/zh-cn/2.0.0.md
server/pom.xml

Adding meta information to docker image,those information will be helpful for locating problems.
```
docker image inspect registry.cn-hangzhou.aliyuncs.com/truthai/seata-server:latest
```
fixes #5653
I've tested it.

adding metainfo to docker image

---

.github/workflows/build.yml
.github/workflows/license-checker.yaml
.github/workflows/test-druid.yml
.github/workflows/test.yml
build/pom.xml
common/src/test/java/io/seata/common/util/CompressUtilTest.java
common/src/test/java/io/seata/common/util/ReflectionUtilTest.java
common/src/test/java/io/seata/common/util/StringUtilsTest.java
dependencies/pom.xml
rm-datasource/src/test/java/io/seata/rm/datasource/ConnectionProxyTest.java
rm-datasource/src/test/java/io/seata/rm/datasource/exec/AbstractDMLBaseExecutorTest.java
server/src/test/java/io/seata/server/coordinator/DefaultCoordinatorTest.java

optimize: fix unit test in java 21
优化：修复单元测试在java21下运行异常的问题。
all：https://github.com/wangliang181230/seata/actions
`build.yml`：https://github.com/wangliang181230/seata/actions/runs/6272155537
`test.yml`：https://github.com/wangliang181230/seata/actions/runs/6272155540
`test-druid.yml`：https://github.com/wangliang181230/seata/actions/runs/6272155538

optimize: fix unit test in java 21

---

changes/en-us/2.0.0.md
changes/zh-cn/2.0.0.md
console/src/main/resources/static/console-fe/package-lock.json
saga/seata-saga-statemachine-designer/package-lock.json
saga/seata-saga-statemachine-designer/package.json

fix npm package vulnerabilities

security: fix npm package vulnerabilities

---

changes/en-us/develop.md
changes/zh-cn/develop.md
server/pom.xml

remove mariadb.jdbc dependency

optimize: remove mariadb.jdbc dependency

---

changes/en-us/2.0.0.md
changes/zh-cn/2.0.0.md
rm-datasource/src/main/java/io/seata/rm/datasource/xa/ConnectionProxyXA.java

将ConnectionProxyXA中log的字符串拼接改为占位符的形式

optimize: optimize log in ConnectionProxyXA

---

changes/en-us/1.4.2.md
changes/en-us/1.5.0.md
changes/en-us/1.5.2.md
changes/en-us/1.6.0.md
changes/en-us/1.7.0.md
changes/en-us/1.7.1.md
changes/en-us/develop.md
changes/zh-cn/1.4.2.md
changes/zh-cn/1.5.0.md
changes/zh-cn/1.5.2.md
changes/zh-cn/1.6.0.md
changes/zh-cn/1.7.0.md
changes/zh-cn/1.7.1.md
changes/zh-cn/develop.md
rm-datasource/src/main/java/io/seata/rm/datasource/sql/handler/dm/DmEscapeHandler.java

bugfix: dm escaped characters for upper and lower case column names

---

.github/workflows/test.yml
changes/en-us/1.7.1.md
changes/en-us/develop.md
changes/zh-cn/1.7.1.md
changes/zh-cn/develop.md

optimize: optimize change log

---

changes/en-us/develop.md
changes/zh-cn/develop.md
codecov.yml

standardized the properties of codecov.yml

optimize: standardized the properties of codecov.yml

---

changes/en-us/develop.md
changes/zh-cn/develop.md
config/seata-config-apollo/src/main/java/io/seata/config/apollo/ApolloConfiguration.java
script/client/conf/registry.conf
script/client/spring/application.properties
script/client/spring/application.yml

optimize: optimize some scripts related to Apollo
优化一些与 Apollo 相关的脚本。

optimize: optimize some scripts related to Apollo

---

changes/en-us/develop.md
changes/zh-cn/develop.md
discovery/seata-discovery-zk/src/main/java/io/seata/discovery/registry/zk/ZookeeperRegisterServiceImpl.java
discovery/seata-discovery-zk/src/test/java/io/seata/discovery/registry/zk/ZookeeperRegisterServiceImplTest.java

remove the method `buildZkTest` because the logic already cover in `testAll`
#5923

bugfix: fix zookeeper unit test error

---

changes/en-us/develop.md
changes/zh-cn/develop.md
distribution/bin/seata-server.bat
distribution/bin/seata-setup.sh

fixes #5269
1. `export JMX_ENABLE=true`
2.  run in local machine, check the opts

optimize: support jmx port in seata

---

.github/workflows/build.yml

optimize: fix build action warning

---

changes/en-us/develop.md
changes/zh-cn/develop.md
dependencies/pom.xml
seata-spring-autoconfigure/seata-spring-autoconfigure-core/src/main/resources/META-INF/additional-spring-configuration-metadata.json
server/pom.xml

test: fixed jedis version for `seata-server`
固定用于 `seata-server` 的jedis版本号。
fixes #5978

test: fixed jedis version for `seata-server`
